function J_ar = J_ar(in1,in2)
%J_ar
%    J_ar = J_ar(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    06-May-2022 12:24:08

P1_2 = in2(4);
P1_3 = in2(7);
P2_2 = in2(5);
P2_3 = in2(8);
P2_4 = in2(11);
P3_2 = in2(6);
P3_3 = in2(9);
P3_4 = in2(12);
R1 = in1(1,:);
R2 = in1(2,:);
R3 = in1(3,:);
R5 = in1(5,:);
R6 = in1(6,:);
t2 = cos(R5);
t3 = cos(R6);
t4 = sin(R5);
t5 = sin(R6);
t6 = P2_4+R3;
t7 = P2_2.*t3;
t8 = P2_3.*t3;
t9 = R2.*t3;
t10 = P1_2.*t5;
t11 = P1_3.*t5;
t12 = R1.*t5;
t13 = -t8;
t14 = -t9;
t15 = t7+t10+t11+t12+t13+t14;
J_ar = reshape([t2.*t3,-t5,-t3.*t4,t2.*t5,t3,-t4.*t5,t4,0.0,t2,0.0,0.0,0.0,P3_2.*t2+P3_3.*t2-P3_4.*t2+t2.*t6-P1_2.*t3.*t4-P1_3.*t3.*t4+P2_2.*t4.*t5-P2_3.*t4.*t5-R1.*t3.*t4-R2.*t4.*t5,0.0,-P3_2.*t4-P3_3.*t4+P3_4.*t4-t4.*t6-P1_2.*t2.*t3-P1_3.*t2.*t3+P2_2.*t2.*t5-P2_3.*t2.*t5-R1.*t2.*t3-R2.*t2.*t5,-t2.*t15,-P1_2.*t3-P1_3.*t3+P2_2.*t5-P2_3.*t5-R1.*t3-R2.*t5,t4.*t15],[3,6]);
