function J_arP = J_arP(x,y,z,b,c,xP,yP,zP,bP,cP,mx,my,mz,tx,ty,tz,px,p_y,pz,d1,d2,t_l)
%J_arP
%    J_arP = J_arP(X,Y,Z,B,C,xP,yP,zP,bP,cP,MX,MY,MZ,TX,TY,TZ,PX,P_Y,PZ,D1,D2,T_L)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    05-May-2022 10:12:06

t2 = cos(b);
t3 = cos(c);
t4 = sin(b);
t5 = sin(c);
t6 = d1.*t2;
t7 = mx.*t2;
t8 = mz.*t2;
t9 = d1.*t4;
t10 = t2.*t_l;
t11 = t2.*x;
t12 = t2.*z;
t13 = mx.*t4;
t14 = mz.*t4;
t15 = t4.*t_l;
t16 = t4.*x;
t17 = t4.*z;
t18 = -t7;
t19 = -t12;
t20 = -t16;
t21 = -t17;
t22 = t6+t8+t10+t13+t19+t20;
t23 = t9+t11+t14+t15+t18+t21;
mt1 = [-bP.*t3.*t4-cP.*t2.*t5,-bP.*t4.*t5+cP.*t2.*t3,bP.*t2,-cP.*t3,-cP.*t5,0.0,-bP.*t2.*t3+cP.*t4.*t5,-bP.*t2.*t5-cP.*t3.*t4,-bP.*t4,-bP.*t3.*t23-cP.*t5.*t22-t3.*t4.*xP-t2.*t3.*zP,-bP.*t5.*t23+cP.*t3.*t22-t4.*t5.*xP-t2.*t5.*zP,bP.*t6+bP.*t8+bP.*t10+bP.*t13+bP.*t19+bP.*t20+t2.*xP-t4.*zP,-t3.*yP+cP.*(my.*t5+t3.*t7-t3.*t9-t3.*t11-t3.*t14-t3.*t15+t3.*t17+t5.*y)-bP.*t5.*t22-t2.*t5.*xP+t4.*t5.*zP];
mt2 = [-t5.*yP-cP.*(my.*t3+t5.*t9+t5.*t11+t5.*t14+t5.*t15+t5.*t18+t5.*t21+t3.*y)+bP.*t3.*t22+t2.*t3.*xP-t3.*t4.*zP,0.0];
J_arP = reshape([mt1,mt2],3,5);
