function J_arPP = J_arPP(x,y,z,b,c,xP,yP,zP,bP,cP,xPP,yPP,zPP,bPP,cPP,mx,my,mz,tx,ty,tz,px,p_y,pz,d1,d2,t_l)
%J_arPP
%    J_arPP = J_arPP(X,Y,Z,B,C,xP,yP,zP,bP,cP,xPP,yPP,zPP,bPP,cPP,MX,MY,MZ,TX,TY,TZ,PX,P_Y,PZ,D1,D2,T_L)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    04-May-2022 15:58:18

t2 = cos(b);
t3 = cos(c);
t4 = sin(b);
t5 = sin(c);
t6 = bP.^2;
t7 = cP.^2;
et1 = t2.*zPP-bPP.*d2.*t4-bPP.*pz.*t4+bPP.*t4.*t_l-bPP.*t4.*tz-d2.*t2.*t6-bPP.*t4.*z-bP.*t4.*zP.*2.0-pz.*t2.*t6+t2.*t6.*t_l-t2.*t6.*tz-t3.*t4.*xPP-t4.*t5.*yPP-t2.*t6.*z-bPP.*p_y.*t2.*t5-bPP.*px.*t2.*t3-cPP.*p_y.*t3.*t4+cPP.*px.*t4.*t5-bPP.*t2.*t3.*tx+bPP.*t2.*t5.*ty+cPP.*t4.*t5.*tx+cPP.*t3.*t4.*ty-bPP.*t2.*t3.*x-bP.*t2.*t3.*xP.*2.0-bPP.*t2.*t5.*y+cPP.*t4.*t5.*x-bP.*t2.*t5.*yP.*2.0+cP.*t4.*t5.*xP.*2.0-cPP.*t3.*t4.*y-cP.*t3.*t4.*yP.*2.0+p_y.*t4.*t5.*t6+p_y.*t4.*t5.*t7+px.*t3.*t4.*t6+px.*t3.*t4.*t7;
et2 = t3.*t4.*t6.*tx+t3.*t4.*t7.*tx-t4.*t5.*t6.*ty-t4.*t5.*t7.*ty+t3.*t4.*t6.*x+t3.*t4.*t7.*x+t4.*t5.*t6.*y+t4.*t5.*t7.*y-bP.*cP.*p_y.*t2.*t3.*2.0+bP.*cP.*px.*t2.*t5.*2.0+bP.*cP.*t2.*t5.*tx.*2.0+bP.*cP.*t2.*t3.*ty.*2.0+bP.*cP.*t2.*t5.*x.*2.0-bP.*cP.*t2.*t3.*y.*2.0;
et3 = -t2.*t5.*xPP+t2.*t3.*yPP-bPP.*p_y.*t3.*t4+bPP.*px.*t4.*t5-cPP.*p_y.*t2.*t5-cPP.*px.*t2.*t3+bPP.*t4.*t5.*tx+bPP.*t3.*t4.*ty-cPP.*t2.*t3.*tx+cPP.*t2.*t5.*ty+bPP.*t4.*t5.*x+bP.*t4.*t5.*xP.*2.0-cPP.*t2.*t3.*x-bPP.*t3.*t4.*y-cP.*t2.*t3.*xP.*2.0-bP.*t3.*t4.*yP.*2.0-cPP.*t2.*t5.*y-cP.*t2.*t5.*yP.*2.0-p_y.*t2.*t3.*t6-p_y.*t2.*t3.*t7+px.*t2.*t5.*t6+px.*t2.*t5.*t7+t2.*t5.*t6.*tx+t2.*t5.*t7.*tx+t2.*t3.*t6.*ty+t2.*t3.*t7.*ty+t2.*t5.*t6.*x+t2.*t5.*t7.*x-t2.*t3.*t6.*y-t2.*t3.*t7.*y+bP.*cP.*p_y.*t4.*t5.*2.0+bP.*cP.*px.*t3.*t4.*2.0+bP.*cP.*t3.*t4.*tx.*2.0;
et4 = bP.*cP.*t4.*t5.*ty.*-2.0+bP.*cP.*t3.*t4.*x.*2.0+bP.*cP.*t4.*t5.*y.*2.0;
et5 = -t4.*zPP-bPP.*d2.*t2-bPP.*pz.*t2+bPP.*t2.*t_l-bPP.*t2.*tz+d2.*t4.*t6-bPP.*t2.*z-bP.*t2.*zP.*2.0+pz.*t4.*t6-t4.*t6.*t_l+t4.*t6.*tz-t2.*t3.*xPP-t2.*t5.*yPP+t4.*t6.*z+bPP.*p_y.*t4.*t5+bPP.*px.*t3.*t4-cPP.*p_y.*t2.*t3+cPP.*px.*t2.*t5+bPP.*t3.*t4.*tx-bPP.*t4.*t5.*ty+cPP.*t2.*t5.*tx+cPP.*t2.*t3.*ty+bPP.*t3.*t4.*x+bP.*t3.*t4.*xP.*2.0+cPP.*t2.*t5.*x+bPP.*t4.*t5.*y+cP.*t2.*t5.*xP.*2.0+bP.*t4.*t5.*yP.*2.0-cPP.*t2.*t3.*y-cP.*t2.*t3.*yP.*2.0+p_y.*t2.*t5.*t6+p_y.*t2.*t5.*t7+px.*t2.*t3.*t6+px.*t2.*t3.*t7+t2.*t3.*t6.*tx+t2.*t3.*t7.*tx;
et6 = -t2.*t5.*t6.*ty-t2.*t5.*t7.*ty+t2.*t3.*t6.*x+t2.*t3.*t7.*x+t2.*t5.*t6.*y+t2.*t5.*t7.*y+bP.*cP.*p_y.*t3.*t4.*2.0-bP.*cP.*px.*t4.*t5.*2.0-bP.*cP.*t4.*t5.*tx.*2.0-bP.*cP.*t3.*t4.*ty.*2.0-bP.*cP.*t4.*t5.*x.*2.0+bP.*cP.*t3.*t4.*y.*2.0;
et7 = t4.*t5.*xPP-t3.*t4.*yPP-bPP.*p_y.*t2.*t3+bPP.*px.*t2.*t5+cPP.*p_y.*t4.*t5+cPP.*px.*t3.*t4+bPP.*t2.*t5.*tx+bPP.*t2.*t3.*ty+cPP.*t3.*t4.*tx-cPP.*t4.*t5.*ty+bPP.*t2.*t5.*x+bP.*t2.*t5.*xP.*2.0-bPP.*t2.*t3.*y+cPP.*t3.*t4.*x-bP.*t2.*t3.*yP.*2.0+cP.*t3.*t4.*xP.*2.0+cPP.*t4.*t5.*y+cP.*t4.*t5.*yP.*2.0+p_y.*t3.*t4.*t6+p_y.*t3.*t4.*t7-px.*t4.*t5.*t6-px.*t4.*t5.*t7-t4.*t5.*t6.*tx-t4.*t5.*t7.*tx-t3.*t4.*t6.*ty-t3.*t4.*t7.*ty-t4.*t5.*t6.*x-t4.*t5.*t7.*x+t3.*t4.*t6.*y+t3.*t4.*t7.*y+bP.*cP.*p_y.*t2.*t5.*2.0+bP.*cP.*px.*t2.*t3.*2.0+bP.*cP.*t2.*t3.*tx.*2.0;
et8 = bP.*cP.*t2.*t5.*ty.*-2.0+bP.*cP.*t2.*t3.*x.*2.0+bP.*cP.*t2.*t5.*y.*2.0;
mt1 = [-bPP.*t3.*t4-cPP.*t2.*t5-t2.*t3.*t6-t2.*t3.*t7+bP.*cP.*t4.*t5.*2.0,-cPP.*t3+t5.*t7,-bPP.*t2.*t3+cPP.*t4.*t5+t3.*t4.*t6+t3.*t4.*t7+bP.*cP.*t2.*t5.*2.0,-bPP.*t4.*t5+cPP.*t2.*t3-t2.*t5.*t6-t2.*t5.*t7-bP.*cP.*t3.*t4.*2.0,-cPP.*t5-t3.*t7,-bPP.*t2.*t5-cPP.*t3.*t4+t4.*t5.*t6+t4.*t5.*t7-bP.*cP.*t2.*t3.*2.0,bPP.*t2-t4.*t6,0.0,-bPP.*t4-t2.*t6,et1+et2,0.0,et5+et6,et3+et4];
mt2 = [-t3.*xPP-t5.*yPP-cPP.*p_y.*t3+cPP.*px.*t5+cPP.*t5.*tx+cPP.*t3.*ty+cPP.*t5.*x+cP.*t5.*xP.*2.0-cPP.*t3.*y-cP.*t3.*yP.*2.0+p_y.*t5.*t7+px.*t3.*t7+t3.*t7.*tx-t5.*t7.*ty+t3.*t7.*x+t5.*t7.*y,et7+et8];
J_arPP = reshape([mt1,mt2],3,5);
