function J_ar = J_ar(x,y,z,b,c,mx,my,mz,tx,ty,tz,px,p_y,pz,d1,d2,t_l)
%J_ar
%    J_ar = J_ar(X,Y,Z,B,C,MX,MY,MZ,TX,TY,TZ,PX,P_Y,PZ,D1,D2,T_L)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    04-May-2022 15:58:17

t2 = cos(b);
t3 = cos(c);
t4 = sin(b);
t5 = sin(c);
t6 = d2+z;
t7 = p_y.*t3;
t8 = t3.*ty;
t9 = t3.*y;
t10 = px.*t5;
t11 = t5.*tx;
t12 = t5.*x;
t13 = -t7;
t14 = -t9;
t15 = t8+t10+t11+t12+t13+t14;
J_ar = reshape([t2.*t3,-t5,-t3.*t4,t2.*t5,t3,-t4.*t5,t4,0.0,t2,pz.*t2+t2.*t6-t2.*t_l+t2.*tz-p_y.*t4.*t5-px.*t3.*t4-t3.*t4.*tx+t4.*t5.*ty-t3.*t4.*x-t4.*t5.*y,0.0,-pz.*t4-t4.*t6+t4.*t_l-t4.*tz-p_y.*t2.*t5-px.*t2.*t3-t2.*t3.*tx+t2.*t5.*ty-t2.*t3.*x-t2.*t5.*y,-t2.*t15,-p_y.*t5-px.*t3-t3.*tx+t5.*ty-t3.*x-t5.*y,t4.*t15],[3,5]);
