function J_arP = J_arP(x,y,z,b,c,xP,yP,zP,bP,cP,mx,my,mz,tx,ty,tz,px,p_y,pz,d1,d2,t_l)
%J_arP
%    J_arP = J_arP(X,Y,Z,B,C,xP,yP,zP,bP,cP,MX,MY,MZ,TX,TY,TZ,PX,P_Y,PZ,D1,D2,T_L)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    04-May-2022 15:58:17

t2 = cos(b);
t3 = cos(c);
t4 = sin(b);
t5 = sin(c);
t6 = d2+z;
t7 = p_y.*t3;
t8 = px.*t3;
t9 = t3.*tx;
t10 = t3.*ty;
t11 = t3.*x;
t12 = t3.*y;
t13 = p_y.*t5;
t14 = px.*t5;
t15 = t5.*tx;
t16 = t5.*ty;
t17 = t5.*x;
t18 = t5.*y;
t19 = -t7;
t20 = -t12;
t21 = -t16;
t22 = t8+t9+t11+t13+t18+t21;
t23 = t10+t14+t15+t17+t19+t20;
mt1 = [-bP.*t3.*t4-cP.*t2.*t5,-cP.*t3,-bP.*t2.*t3+cP.*t4.*t5,-bP.*t4.*t5+cP.*t2.*t3,-cP.*t5,-bP.*t2.*t5-cP.*t3.*t4,bP.*t2,0.0,-bP.*t4,t2.*zP-bP.*(pz.*t4+t2.*t8+t4.*t6+t2.*t9+t2.*t11+t2.*t13+t2.*t18+t2.*t21-t4.*t_l+t4.*tz)+cP.*t4.*t23-t3.*t4.*xP-t4.*t5.*yP,0.0,-t4.*zP+bP.*(-pz.*t2-t2.*t6+t4.*t8+t4.*t9+t4.*t11+t4.*t13+t4.*t18+t4.*t21+t2.*t_l-t2.*tz)+cP.*t2.*t23-t2.*t3.*xP-t2.*t5.*yP];
mt2 = [bP.*t4.*t23-cP.*t2.*t22-t2.*t5.*xP+t2.*t3.*yP,cP.*t10+cP.*t14+cP.*t15+cP.*t17+cP.*t19+cP.*t20-t3.*xP-t5.*yP,bP.*t2.*t23+cP.*t4.*t22+t4.*t5.*xP-t3.*t4.*yP];
J_arP = reshape([mt1,mt2],3,5);
