function J_arPP = J_arPP(x,y,z,b,c,xP,yP,zP,bP,cP,xPP,yPP,zPP,bPP,cPP,mx,my,mz,tx,ty,tz,px,p_y,pz,d1,d2,t_l)
%J_arPP
%    J_arPP = J_arPP(X,Y,Z,B,C,xP,yP,zP,bP,cP,xPP,yPP,zPP,bPP,cPP,MX,MY,MZ,TX,TY,TZ,PX,P_Y,PZ,D1,D2,T_L)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    05-May-2022 10:12:07

t2 = cos(b);
t3 = cos(c);
t4 = sin(b);
t5 = sin(c);
t6 = bP.^2;
t7 = cP.^2;
et1 = -t3.*t4.*xPP-t2.*t3.*zPP-bPP.*d1.*t3.*t4-cPP.*d1.*t2.*t5+bPP.*mx.*t2.*t3-bPP.*mz.*t3.*t4-cPP.*mx.*t4.*t5-cPP.*mz.*t2.*t5-bPP.*t3.*t4.*t_l-cPP.*t2.*t5.*t_l-d1.*t2.*t3.*t6-d1.*t2.*t3.*t7-bPP.*t2.*t3.*x-bP.*t2.*t3.*xP.*2.0+cPP.*t4.*t5.*x+cP.*t4.*t5.*xP.*2.0+bPP.*t3.*t4.*z+bP.*t3.*t4.*zP.*2.0+cPP.*t2.*t5.*z+cP.*t2.*t5.*zP.*2.0-mx.*t3.*t4.*t6-mx.*t3.*t4.*t7-mz.*t2.*t3.*t6-mz.*t2.*t3.*t7-t2.*t3.*t6.*t_l-t2.*t3.*t7.*t_l+t3.*t4.*t6.*x+t3.*t4.*t7.*x+t2.*t3.*t6.*z+t2.*t3.*t7.*z+bP.*cP.*d1.*t4.*t5.*2.0;
et2 = bP.*cP.*mx.*t2.*t5.*-2.0+bP.*cP.*mz.*t4.*t5.*2.0+bP.*cP.*t4.*t5.*t_l.*2.0+bP.*cP.*t2.*t5.*x.*2.0-bP.*cP.*t4.*t5.*z.*2.0;
et3 = -t3.*yPP+cPP.*my.*t5+cPP.*t5.*y+cP.*t5.*yP.*2.0+my.*t3.*t7-t2.*t5.*xPP+t3.*t7.*y+t4.*t5.*zPP-bPP.*d1.*t2.*t5-cPP.*d1.*t3.*t4-bPP.*mx.*t4.*t5-bPP.*mz.*t2.*t5+cPP.*mx.*t2.*t3-cPP.*mz.*t3.*t4-bPP.*t2.*t5.*t_l-cPP.*t3.*t4.*t_l+d1.*t4.*t5.*t6+d1.*t4.*t5.*t7+bPP.*t4.*t5.*x+bP.*t4.*t5.*xP.*2.0-cPP.*t2.*t3.*x-cP.*t2.*t3.*xP.*2.0+bPP.*t2.*t5.*z+bP.*t2.*t5.*zP.*2.0+cPP.*t3.*t4.*z+cP.*t3.*t4.*zP.*2.0-mx.*t2.*t5.*t6-mx.*t2.*t5.*t7+mz.*t4.*t5.*t6+mz.*t4.*t5.*t7+t4.*t5.*t6.*t_l+t4.*t5.*t7.*t_l+t2.*t5.*t6.*x+t2.*t5.*t7.*x-t4.*t5.*t6.*z;
et4 = -t4.*t5.*t7.*z-bP.*cP.*d1.*t2.*t3.*2.0-bP.*cP.*mx.*t3.*t4.*2.0-bP.*cP.*mz.*t2.*t3.*2.0-bP.*cP.*t2.*t3.*t_l.*2.0+bP.*cP.*t3.*t4.*x.*2.0+bP.*cP.*t2.*t3.*z.*2.0;
et5 = -t4.*t5.*xPP-t2.*t5.*zPP-bPP.*d1.*t4.*t5+cPP.*d1.*t2.*t3+bPP.*mx.*t2.*t5-bPP.*mz.*t4.*t5+cPP.*mx.*t3.*t4+cPP.*mz.*t2.*t3-bPP.*t4.*t5.*t_l+cPP.*t2.*t3.*t_l-d1.*t2.*t5.*t6-d1.*t2.*t5.*t7-bPP.*t2.*t5.*x-bP.*t2.*t5.*xP.*2.0-cPP.*t3.*t4.*x-cP.*t3.*t4.*xP.*2.0+bPP.*t4.*t5.*z+bP.*t4.*t5.*zP.*2.0-cPP.*t2.*t3.*z-cP.*t2.*t3.*zP.*2.0-mx.*t4.*t5.*t6-mx.*t4.*t5.*t7-mz.*t2.*t5.*t6-mz.*t2.*t5.*t7-t2.*t5.*t6.*t_l-t2.*t5.*t7.*t_l+t4.*t5.*t6.*x+t4.*t5.*t7.*x+t2.*t5.*t6.*z+t2.*t5.*t7.*z-bP.*cP.*d1.*t3.*t4.*2.0;
et6 = bP.*cP.*mx.*t2.*t3.*2.0-bP.*cP.*mz.*t3.*t4.*2.0-bP.*cP.*t3.*t4.*t_l.*2.0-bP.*cP.*t2.*t3.*x.*2.0+bP.*cP.*t3.*t4.*z.*2.0;
et7 = -t5.*yPP-cPP.*my.*t3-cPP.*t3.*y-cP.*t3.*yP.*2.0+my.*t5.*t7+t2.*t3.*xPP+t5.*t7.*y-t3.*t4.*zPP+bPP.*d1.*t2.*t3-cPP.*d1.*t4.*t5+bPP.*mx.*t3.*t4+bPP.*mz.*t2.*t3+cPP.*mx.*t2.*t5-cPP.*mz.*t4.*t5+bPP.*t2.*t3.*t_l-cPP.*t4.*t5.*t_l-d1.*t3.*t4.*t6-d1.*t3.*t4.*t7-bPP.*t3.*t4.*x-bP.*t3.*t4.*xP.*2.0-cPP.*t2.*t5.*x-cP.*t2.*t5.*xP.*2.0-bPP.*t2.*t3.*z-bP.*t2.*t3.*zP.*2.0+cPP.*t4.*t5.*z+cP.*t4.*t5.*zP.*2.0+mx.*t2.*t3.*t6+mx.*t2.*t3.*t7-mz.*t3.*t4.*t6-mz.*t3.*t4.*t7-t3.*t4.*t6.*t_l-t3.*t4.*t7.*t_l-t2.*t3.*t6.*x;
et8 = -t2.*t3.*t7.*x+t3.*t4.*t6.*z+t3.*t4.*t7.*z-bP.*cP.*d1.*t2.*t5.*2.0-bP.*cP.*mx.*t4.*t5.*2.0-bP.*cP.*mz.*t2.*t5.*2.0-bP.*cP.*t2.*t5.*t_l.*2.0+bP.*cP.*t4.*t5.*x.*2.0+bP.*cP.*t2.*t5.*z.*2.0;
mt1 = [-bPP.*t3.*t4-cPP.*t2.*t5-t2.*t3.*t6-t2.*t3.*t7+bP.*cP.*t4.*t5.*2.0,-bPP.*t4.*t5+cPP.*t2.*t3-t2.*t5.*t6-t2.*t5.*t7-bP.*cP.*t3.*t4.*2.0,bPP.*t2-t4.*t6,-cPP.*t3+t5.*t7,-cPP.*t5-t3.*t7,0.0,-bPP.*t2.*t3+cPP.*t4.*t5+t3.*t4.*t6+t3.*t4.*t7+bP.*cP.*t2.*t5.*2.0,-bPP.*t2.*t5-cPP.*t3.*t4+t4.*t5.*t6+t4.*t5.*t7-bP.*cP.*t2.*t3.*2.0,-bPP.*t4-t2.*t6,et1+et2,et5+et6];
mt2 = [t2.*xPP-t4.*zPP+bPP.*d1.*t2+bPP.*mx.*t4+bPP.*mz.*t2+bPP.*t2.*t_l-d1.*t4.*t6-bPP.*t4.*x-bP.*t4.*xP.*2.0-bPP.*t2.*z-bP.*t2.*zP.*2.0+mx.*t2.*t6-mz.*t4.*t6-t4.*t6.*t_l-t2.*t6.*x+t4.*t6.*z,et3+et4,et7+et8,0.0];
J_arPP = reshape([mt1,mt2],3,5);
