function J_ar = J_ar(x,y,z,b,c,mx,my,mz,tx,ty,tz,px,p_y,pz,d1,d2,t_l)
%J_ar
%    J_ar = J_ar(X,Y,Z,B,C,MX,MY,MZ,TX,TY,TZ,PX,P_Y,PZ,D1,D2,T_L)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    05-May-2022 10:12:05

t2 = cos(b);
t3 = cos(c);
t4 = sin(b);
t5 = sin(c);
t6 = d1.*t2;
t7 = mz.*t2;
t8 = t2.*t_l;
t9 = t2.*z;
t10 = mx.*t4;
t11 = t4.*x;
t12 = -t9;
t13 = -t11;
t14 = t6+t7+t8+t10+t12+t13;
J_ar = reshape([t2.*t3,t2.*t5,t4,-t5,t3,0.0,-t3.*t4,-t4.*t5,t2,t3.*t14,t5.*t14,d1.*t4-mx.*t2+mz.*t4+t4.*t_l+t2.*x-t4.*z,-my.*t3-t3.*y-d1.*t4.*t5+mx.*t2.*t5-mz.*t4.*t5-t4.*t5.*t_l-t2.*t5.*x+t4.*t5.*z,-my.*t5-t5.*y+d1.*t3.*t4-mx.*t2.*t3+mz.*t3.*t4+t3.*t4.*t_l+t2.*t3.*x-t3.*t4.*z,0.0],[3,5]);
