function J_arPP = J_arPP(in1,in2,in3,in4)
%J_arPP
%    J_arPP = J_arPP(IN1,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    13-May-2022 12:40:36

P1_2 = in4(4);
P1_3 = in4(7);
P2_2 = in4(5);
P2_3 = in4(8);
P2_4 = in4(11);
P3_2 = in4(6);
P3_3 = in4(9);
P3_4 = in4(12);
R1 = in1(1,:);
R2 = in1(2,:);
R3 = in1(3,:);
R5 = in1(5,:);
R6 = in1(6,:);
Rp1 = in2(1,:);
Rp2 = in2(2,:);
Rp3 = in2(3,:);
Rp5 = in2(5,:);
Rp6 = in2(6,:);
Rpp1 = in3(1,:);
Rpp2 = in3(2,:);
Rpp3 = in3(3,:);
Rpp5 = in3(5,:);
Rpp6 = in3(6,:);
t2 = cos(R5);
t3 = cos(R6);
t4 = sin(R5);
t5 = sin(R6);
t6 = Rp5.^2;
t7 = Rp6.^2;
et1 = Rpp3.*t2-P2_4.*Rpp5.*t4-P3_2.*Rpp5.*t4-P3_3.*Rpp5.*t4+P3_4.*Rpp5.*t4-R3.*Rpp5.*t4-Rp3.*Rp5.*t4.*2.0-P2_4.*t2.*t6-P3_2.*t2.*t6-P3_3.*t2.*t6+P3_4.*t2.*t6-R3.*t2.*t6-Rpp1.*t3.*t4-Rpp2.*t4.*t5+P1_2.*t3.*t4.*t6+P1_2.*t3.*t4.*t7+P1_3.*t3.*t4.*t6+P1_3.*t3.*t4.*t7-P2_2.*t4.*t5.*t6-P2_2.*t4.*t5.*t7+P2_3.*t4.*t5.*t6+P2_3.*t4.*t5.*t7+R1.*t3.*t4.*t6+R1.*t3.*t4.*t7+R2.*t4.*t5.*t6+R2.*t4.*t5.*t7-P1_2.*Rpp5.*t2.*t3-P1_3.*Rpp5.*t2.*t3+P1_2.*Rpp6.*t4.*t5+P1_3.*Rpp6.*t4.*t5+P2_2.*Rpp5.*t2.*t5+P2_2.*Rpp6.*t3.*t4-P2_3.*Rpp5.*t2.*t5-P2_3.*Rpp6.*t3.*t4-R1.*Rpp5.*t2.*t3;
et2 = -R2.*Rpp5.*t2.*t5-R2.*Rpp6.*t3.*t4+R1.*Rpp6.*t4.*t5-Rp1.*Rp5.*t2.*t3.*2.0-Rp2.*Rp5.*t2.*t5.*2.0-Rp2.*Rp6.*t3.*t4.*2.0+Rp1.*Rp6.*t4.*t5.*2.0+P1_2.*Rp5.*Rp6.*t2.*t5.*2.0+P1_3.*Rp5.*Rp6.*t2.*t5.*2.0+P2_2.*Rp5.*Rp6.*t2.*t3.*2.0-P2_3.*Rp5.*Rp6.*t2.*t3.*2.0-R2.*Rp5.*Rp6.*t2.*t3.*2.0+R1.*Rp5.*Rp6.*t2.*t5.*2.0;
et3 = Rpp2.*t2.*t3-Rpp1.*t2.*t5+P1_2.*t2.*t5.*t6+P1_2.*t2.*t5.*t7+P1_3.*t2.*t5.*t6+P1_3.*t2.*t5.*t7+P2_2.*t2.*t3.*t6+P2_2.*t2.*t3.*t7-P2_3.*t2.*t3.*t6-P2_3.*t2.*t3.*t7-R2.*t2.*t3.*t6+R1.*t2.*t5.*t6-R2.*t2.*t3.*t7+R1.*t2.*t5.*t7-P1_2.*Rpp6.*t2.*t3-P1_3.*Rpp6.*t2.*t3+P1_2.*Rpp5.*t4.*t5+P1_3.*Rpp5.*t4.*t5+P2_2.*Rpp5.*t3.*t4+P2_2.*Rpp6.*t2.*t5-P2_3.*Rpp5.*t3.*t4-P2_3.*Rpp6.*t2.*t5-R1.*Rpp6.*t2.*t3-R2.*Rpp5.*t3.*t4+R1.*Rpp5.*t4.*t5-R2.*Rpp6.*t2.*t5-Rp1.*Rp6.*t2.*t3.*2.0-Rp2.*Rp5.*t3.*t4.*2.0+Rp1.*Rp5.*t4.*t5.*2.0-Rp2.*Rp6.*t2.*t5.*2.0+P1_2.*Rp5.*Rp6.*t3.*t4.*2.0+P1_3.*Rp5.*Rp6.*t3.*t4.*2.0;
et4 = P2_2.*Rp5.*Rp6.*t4.*t5.*-2.0+P2_3.*Rp5.*Rp6.*t4.*t5.*2.0+R1.*Rp5.*Rp6.*t3.*t4.*2.0+R2.*Rp5.*Rp6.*t4.*t5.*2.0;
et5 = -Rpp3.*t4-P2_4.*Rpp5.*t2-P3_2.*Rpp5.*t2-P3_3.*Rpp5.*t2+P3_4.*Rpp5.*t2-R3.*Rpp5.*t2-Rp3.*Rp5.*t2.*2.0+P2_4.*t4.*t6+P3_2.*t4.*t6+P3_3.*t4.*t6-P3_4.*t4.*t6+R3.*t4.*t6-Rpp1.*t2.*t3-Rpp2.*t2.*t5+P1_2.*t2.*t3.*t6+P1_2.*t2.*t3.*t7+P1_3.*t2.*t3.*t6+P1_3.*t2.*t3.*t7-P2_2.*t2.*t5.*t6-P2_2.*t2.*t5.*t7+P2_3.*t2.*t5.*t6+P2_3.*t2.*t5.*t7+R1.*t2.*t3.*t6+R1.*t2.*t3.*t7+R2.*t2.*t5.*t6+R2.*t2.*t5.*t7+P1_2.*Rpp5.*t3.*t4+P1_2.*Rpp6.*t2.*t5+P1_3.*Rpp5.*t3.*t4+P1_3.*Rpp6.*t2.*t5+P2_2.*Rpp6.*t2.*t3-P2_3.*Rpp6.*t2.*t3-P2_2.*Rpp5.*t4.*t5+P2_3.*Rpp5.*t4.*t5+R1.*Rpp5.*t3.*t4-R2.*Rpp6.*t2.*t3+R1.*Rpp6.*t2.*t5;
et6 = R2.*Rpp5.*t4.*t5+Rp1.*Rp5.*t3.*t4.*2.0-Rp2.*Rp6.*t2.*t3.*2.0+Rp1.*Rp6.*t2.*t5.*2.0+Rp2.*Rp5.*t4.*t5.*2.0-P1_2.*Rp5.*Rp6.*t4.*t5.*2.0-P1_3.*Rp5.*Rp6.*t4.*t5.*2.0-P2_2.*Rp5.*Rp6.*t3.*t4.*2.0+P2_3.*Rp5.*Rp6.*t3.*t4.*2.0+R2.*Rp5.*Rp6.*t3.*t4.*2.0-R1.*Rp5.*Rp6.*t4.*t5.*2.0;
et7 = -Rpp2.*t3.*t4+Rpp1.*t4.*t5-P1_2.*t4.*t5.*t6-P1_2.*t4.*t5.*t7-P1_3.*t4.*t5.*t6-P1_3.*t4.*t5.*t7-P2_2.*t3.*t4.*t6-P2_2.*t3.*t4.*t7+P2_3.*t3.*t4.*t6+P2_3.*t3.*t4.*t7+R2.*t3.*t4.*t6-R1.*t4.*t5.*t6+R2.*t3.*t4.*t7-R1.*t4.*t5.*t7+P1_2.*Rpp5.*t2.*t5+P1_2.*Rpp6.*t3.*t4+P1_3.*Rpp5.*t2.*t5+P1_3.*Rpp6.*t3.*t4+P2_2.*Rpp5.*t2.*t3-P2_3.*Rpp5.*t2.*t3-P2_2.*Rpp6.*t4.*t5+P2_3.*Rpp6.*t4.*t5-R2.*Rpp5.*t2.*t3+R1.*Rpp5.*t2.*t5+R1.*Rpp6.*t3.*t4+R2.*Rpp6.*t4.*t5-Rp2.*Rp5.*t2.*t3.*2.0+Rp1.*Rp5.*t2.*t5.*2.0+Rp1.*Rp6.*t3.*t4.*2.0+Rp2.*Rp6.*t4.*t5.*2.0+P1_2.*Rp5.*Rp6.*t2.*t3.*2.0+P1_3.*Rp5.*Rp6.*t2.*t3.*2.0-P2_2.*Rp5.*Rp6.*t2.*t5.*2.0;
et8 = P2_3.*Rp5.*Rp6.*t2.*t5.*2.0+R1.*Rp5.*Rp6.*t2.*t3.*2.0+R2.*Rp5.*Rp6.*t2.*t5.*2.0;
mt1 = [-Rpp5.*t3.*t4-Rpp6.*t2.*t5-t2.*t3.*t6-t2.*t3.*t7+Rp5.*Rp6.*t4.*t5.*2.0,-Rpp6.*t3+t5.*t7,-Rpp5.*t2.*t3+Rpp6.*t4.*t5+t3.*t4.*t6+t3.*t4.*t7+Rp5.*Rp6.*t2.*t5.*2.0,Rpp6.*t2.*t3-Rpp5.*t4.*t5-t2.*t5.*t6-t2.*t5.*t7-Rp5.*Rp6.*t3.*t4.*2.0,-Rpp6.*t5-t3.*t7,-Rpp5.*t2.*t5-Rpp6.*t3.*t4+t4.*t5.*t6+t4.*t5.*t7-Rp5.*Rp6.*t2.*t3.*2.0,Rpp5.*t2-t4.*t6,0.0,-Rpp5.*t4-t2.*t6,0.0,0.0,0.0,et1+et2,0.0,et5+et6,et3+et4];
mt2 = [-Rpp1.*t3-Rpp2.*t5+P1_2.*Rpp6.*t5+P1_3.*Rpp6.*t5+P2_2.*Rpp6.*t3-P2_3.*Rpp6.*t3-R2.*Rpp6.*t3+R1.*Rpp6.*t5-Rp2.*Rp6.*t3.*2.0+Rp1.*Rp6.*t5.*2.0+P1_2.*t3.*t7+P1_3.*t3.*t7-P2_2.*t5.*t7+P2_3.*t5.*t7+R1.*t3.*t7+R2.*t5.*t7,et7+et8];
J_arPP = reshape([mt1,mt2],3,6);
