function J_arP = J_arP(in1,in2,in3)
%J_arP
%    J_arP = J_arP(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    06-May-2022 12:39:04

P1_2 = in3(4);
P1_3 = in3(7);
P2_2 = in3(5);
P2_3 = in3(8);
P2_4 = in3(11);
P3_2 = in3(6);
P3_3 = in3(9);
P3_4 = in3(12);
R1 = in1(1,:);
R2 = in1(2,:);
R3 = in1(3,:);
R5 = in1(5,:);
R6 = in1(6,:);
Rp1 = in2(1,:);
Rp2 = in2(2,:);
Rp3 = in2(3,:);
Rp5 = in2(5,:);
Rp6 = in2(6,:);
t2 = cos(R5);
t3 = cos(R6);
t4 = sin(R5);
t5 = sin(R6);
t6 = P2_4+R3;
t7 = P1_2.*t3;
t8 = P1_3.*t3;
t9 = P2_2.*t3;
t10 = P2_3.*t3;
t11 = R1.*t3;
t12 = R2.*t3;
t13 = P1_2.*t5;
t14 = P1_3.*t5;
t15 = P2_2.*t5;
t16 = P2_3.*t5;
t17 = R1.*t5;
t18 = R2.*t5;
t19 = -t10;
t20 = -t12;
t21 = -t15;
t22 = t7+t8+t11+t16+t18+t21;
t23 = t9+t13+t14+t17+t19+t20;
mt1 = [-Rp5.*t3.*t4-Rp6.*t2.*t5,-Rp6.*t3,-Rp5.*t2.*t3+Rp6.*t4.*t5,Rp6.*t2.*t3-Rp5.*t4.*t5,-Rp6.*t5,-Rp5.*t2.*t5-Rp6.*t3.*t4,Rp5.*t2,0.0,-Rp5.*t4,0.0,0.0,0.0,Rp3.*t2-Rp5.*(P3_2.*t4+P3_3.*t4-P3_4.*t4+t2.*t7+t2.*t8+t4.*t6+t2.*t11+t2.*t16+t2.*t18+t2.*t21)-Rp1.*t3.*t4-Rp2.*t4.*t5+Rp6.*t4.*t23,0.0,-Rp3.*t4+Rp5.*(-P3_2.*t2-P3_3.*t2+P3_4.*t2-t2.*t6+t4.*t7+t4.*t8+t4.*t11+t4.*t16+t4.*t18+t4.*t21)-Rp1.*t2.*t3-Rp2.*t2.*t5+Rp6.*t2.*t23];
mt2 = [Rp2.*t2.*t3-Rp1.*t2.*t5-Rp6.*t2.*t22+Rp5.*t4.*t23,-Rp1.*t3-Rp2.*t5+Rp6.*t9+Rp6.*t13+Rp6.*t14+Rp6.*t17+Rp6.*t19+Rp6.*t20,-Rp2.*t3.*t4+Rp1.*t4.*t5+Rp5.*t2.*t23+Rp6.*t4.*t22];
J_arP = reshape([mt1,mt2],3,6);
