function JP_ar = kin_JP_ar_xyzbc(in1,in2,in3)
%kin_JP_ar_xyzbc
%    JP_ar = kin_JP_ar_xyzbc(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 9.1.
%    30-Aug-2023 15:04:00

%Jacobian first derivative ( backward ) : 
%INPUTS : 
%	r_r : 5 x 1 : pose vector ( relative )
%	v_r : 5 x 1 : speed vector ( relative )
%	a_a : 5 x 1 : acceleration vector( relative )
%	p   : 5 x 1 : parameters
%OUTPUTS : 
%	M   : 5 x 5 : resulting matrix
%#codegen
P1_2 = in3(4);
P1_3 = in3(7);
P2_2 = in3(5);
P2_3 = in3(8);
P2_4 = in3(11);
P3_2 = in3(6);
P3_3 = in3(9);
P3_4 = in3(12);
R1 = in1(1,:);
R2 = in1(2,:);
R3 = in1(3,:);
R4 = in1(4,:);
R5 = in1(5,:);
Rp1 = in2(1,:);
Rp2 = in2(2,:);
Rp3 = in2(3,:);
Rp4 = in2(4,:);
Rp5 = in2(5,:);
t2 = cos(R4);
t3 = cos(R5);
t4 = sin(R4);
t5 = sin(R5);
t6 = P2_4+R3;
t19 = -P3_4;
t7 = P1_2.*t3;
t8 = P1_3.*t3;
t9 = P2_2.*t3;
t10 = P2_3.*t3;
t11 = R1.*t3;
t12 = R2.*t3;
t13 = P1_2.*t5;
t14 = P1_3.*t5;
t15 = P2_2.*t5;
t16 = P2_3.*t5;
t17 = R1.*t5;
t18 = R2.*t5;
t20 = P3_2+t19;
t21 = -t10;
t22 = -t12;
t23 = -t15;
t24 = t7+t8+t11+t16+t18+t23;
t25 = t9+t13+t14+t17+t21+t22;
mt1 = [-Rp4.*t3.*t4-Rp5.*t2.*t5,-Rp5.*t3,-Rp4.*t2.*t3+Rp5.*t4.*t5,0.0,0.0,Rp5.*t2.*t3-Rp4.*t4.*t5,-Rp5.*t5,-Rp4.*t2.*t5-Rp5.*t3.*t4,0.0,0.0,Rp4.*t2,0.0,-Rp4.*t4,0.0,0.0,Rp3.*t2-Rp4.*(P3_3.*t4+t2.*t7+t2.*t8+t4.*t6+t2.*t11+t2.*t16+t2.*t18+t4.*t20+t2.*t23)-Rp1.*t3.*t4-Rp2.*t4.*t5+Rp5.*t4.*t25,0.0,-Rp3.*t4+Rp4.*(-P3_3.*t2-t2.*t6+t4.*t7+t4.*t8+t4.*t11+t4.*t16-t2.*t20+t4.*t18+t4.*t23)-Rp1.*t2.*t3-Rp2.*t2.*t5+Rp5.*t2.*t25,0.0,0.0];
mt2 = [Rp2.*t2.*t3-Rp1.*t2.*t5-Rp5.*t2.*t24+Rp4.*t4.*t25,-Rp1.*t3-Rp2.*t5+Rp5.*t9+Rp5.*t13+Rp5.*t14+Rp5.*t17+Rp5.*t21+Rp5.*t22,-Rp2.*t3.*t4+Rp1.*t4.*t5+Rp4.*t2.*t25+Rp5.*t4.*t24,0.0,0.0];
JP_ar = reshape([mt1,mt2],5,5);
