function MGD = kin_forward_xyzbc(in1,in2)
%KIN_FORWARD_XYZBC
%    MGD = KIN_FORWARD_XYZBC(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    13-Jun-2022 18:00:01

%Forward Kinematics ( Direct Geometrique Model )  : 
%INPUTS : 
%	r_a : 5 x 1 : pose vector( joint )
%	p   : 5 x 1 : parameters
%OUTPUTS : 
%	r_r : 5 x 1 : pose vector ( relative )
%#codegen
P1_1 = in2(1);
P1_2 = in2(4);
P1_3 = in2(7);
P1_4 = in2(10);
P2_1 = in2(2);
P2_2 = in2(5);
P2_3 = in2(8);
P2_4 = in2(11);
P3_1 = in2(3);
P3_2 = in2(6);
P3_3 = in2(9);
P3_4 = in2(12);
R1 = in1(1,:);
R3 = in1(3,:);
R4 = in1(4,:);
R5 = in1(5,:);
t2 = cos(R4);
t3 = cos(R5);
t4 = sin(R4);
t5 = sin(R5);
MGD = [-P1_2-P1_3-P2_1.*t5-R1.*t5-P1_1.*t2.*t3+P1_4.*t3.*t4+P3_1.*t3.*t4+P3_4.*t3.*t4+R1.*t2.*t3-R3.*t3.*t4;P2_2-P2_3+P2_1.*t3+R1.*t3-P1_1.*t2.*t5+P1_4.*t4.*t5+P3_1.*t4.*t5+P3_4.*t4.*t5+R1.*t2.*t5-R3.*t4.*t5;-P2_4-P3_2-P3_3+P3_4-P1_1.*t4-P1_4.*t2-P3_1.*t2-P3_4.*t2+R1.*t4+R3.*t2;R4;R5];
