function joint = kin_xyzbc_tt_inverse(in1,in2)
%KIN_XYZBC_TT_INVERSE
%    JOINT = KIN_XYZBC_TT_INVERSE(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.1.
%    07-Nov-2023 14:54:32

%Inverse Kinematics : 
%INPUTS : 
%	r_t    (5x1) : pose vector ( piece frame )
%	p      (3x5) : parameters
%OUTPUTS : 
%	r_j    (5x1) : pose vector( joint space )
%#codegen
b = in1(4,:);
c = in1(5,:);
offB1 = in2(10);
offC1 = in2(13);
offB3 = in2(12);
offC2 = in2(14);
offC3 = in2(15);
offM1 = in2(1);
offM2 = in2(2);
offM3 = in2(3);
offP1 = in2(7);
offP2 = in2(8);
offP3 = in2(9);
offT1 = in2(4);
offT2 = in2(5);
offT3 = in2(6);
x = in1(1,:);
y = in1(2,:);
z = in1(3,:);
t2 = cos(b);
t3 = cos(c);
t4 = sin(b);
t5 = sin(c);
t6 = offP1+x;
t7 = offP2+y;
t8 = offP3+z;
joint = [-offB1-offC1+offM1-offT1+offB1.*t2+offB3.*t4+offC3.*t4+t4.*t8+offC1.*t2.*t3-offC2.*t2.*t5+t2.*t3.*t6-t2.*t5.*t7;-offC2+offM2-offT2+offC2.*t3+offC1.*t5+t3.*t7+t5.*t6;-offB3-offC3+offM3-offT3-offB1.*t4+offB3.*t2+offC3.*t2+t2.*t8-offC1.*t3.*t4+offC2.*t4.*t5-t3.*t4.*t6+t4.*t5.*t7;b;c];
