function J2P_ra = kin_J2P_ra_xyzbc(in1,in2,in3,in4)
%kin_J2P_ra_xyzbc
%    J2P_ra = kin_J2P_ra_xyzbc(IN1,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    13-Jun-2022 18:00:02

%Jacobian second derivative ( forward ) : 
%INPUTS : 
%	r_a : 5 x 1 : pose vector( joint )
%	v_a : 5 x 1 : speed vector( joint )
%	a_a : 5 x 1 : acceleration vector( joint )
%	j_a : 5 x 1 : jerk vector( joint )
%	p   : 5 x 1 : parameters
%OUTPUTS : 
%	M   : 5 x 5 : resulting matrix
%#codegen
P1_1 = in4(1);
P1_4 = in4(10);
P2_1 = in4(2);
P3_1 = in4(3);
P3_4 = in4(12);
R1 = in1(1,:);
R3 = in1(3,:);
R4 = in1(4,:);
R5 = in1(5,:);
Rp1 = in2(1,:);
Rp3 = in2(3,:);
Rp4 = in2(4,:);
Rp5 = in2(5,:);
Rpp1 = in3(1,:);
Rpp3 = in3(3,:);
Rpp4 = in3(4,:);
Rpp5 = in3(5,:);
t2 = cos(R4);
t3 = cos(R5);
t4 = sin(R4);
t5 = sin(R5);
t6 = Rp4.^2;
t7 = Rp5.^2;
et1 = -Rpp1.*t3.*t4-Rpp3.*t2.*t3-P1_1.*t3.*t4.*t6-P1_1.*t3.*t4.*t7-P1_4.*t2.*t3.*t6-P1_4.*t2.*t3.*t7-P3_1.*t2.*t3.*t6-P3_1.*t2.*t3.*t7-P3_4.*t2.*t3.*t6-P3_4.*t2.*t3.*t7+R1.*t3.*t4.*t6+R3.*t2.*t3.*t6+R1.*t3.*t4.*t7+R3.*t2.*t3.*t7+P1_1.*Rpp4.*t2.*t3-P1_1.*Rpp5.*t4.*t5-P1_4.*Rpp4.*t3.*t4-P1_4.*Rpp5.*t2.*t5-P3_1.*Rpp4.*t3.*t4-P3_1.*Rpp5.*t2.*t5-P3_4.*Rpp4.*t3.*t4-P3_4.*Rpp5.*t2.*t5-R1.*Rpp4.*t2.*t3+R3.*Rpp4.*t3.*t4+R1.*Rpp5.*t4.*t5+R3.*Rpp5.*t2.*t5-Rp1.*Rp4.*t2.*t3.*2.0+Rp3.*Rp4.*t3.*t4.*2.0+Rp1.*Rp5.*t4.*t5.*2.0+Rp3.*Rp5.*t2.*t5.*2.0-P1_1.*Rp4.*Rp5.*t2.*t5.*2.0;
et2 = P1_4.*Rp4.*Rp5.*t4.*t5.*2.0+P3_1.*Rp4.*Rp5.*t4.*t5.*2.0+P3_4.*Rp4.*Rp5.*t4.*t5.*2.0+R1.*Rp4.*Rp5.*t2.*t5.*2.0-R3.*Rp4.*Rp5.*t4.*t5.*2.0;
et3 = -Rpp1.*t3+P2_1.*Rpp5.*t5+R1.*Rpp5.*t5+Rp1.*Rp5.*t5.*2.0+P2_1.*t3.*t7+R1.*t3.*t7-Rpp1.*t2.*t5+Rpp3.*t4.*t5-P1_1.*t2.*t5.*t6-P1_1.*t2.*t5.*t7+P1_4.*t4.*t5.*t6+P1_4.*t4.*t5.*t7+P3_1.*t4.*t5.*t6+P3_1.*t4.*t5.*t7+P3_4.*t4.*t5.*t6+P3_4.*t4.*t5.*t7+R1.*t2.*t5.*t6+R1.*t2.*t5.*t7-R3.*t4.*t5.*t6-R3.*t4.*t5.*t7+P1_1.*Rpp5.*t2.*t3-P1_1.*Rpp4.*t4.*t5-P1_4.*Rpp4.*t2.*t5-P1_4.*Rpp5.*t3.*t4-P3_1.*Rpp4.*t2.*t5-P3_1.*Rpp5.*t3.*t4-P3_4.*Rpp4.*t2.*t5-P3_4.*Rpp5.*t3.*t4-R1.*Rpp5.*t2.*t3+R1.*Rpp4.*t4.*t5+R3.*Rpp4.*t2.*t5+R3.*Rpp5.*t3.*t4-Rp1.*Rp5.*t2.*t3.*2.0+Rp1.*Rp4.*t4.*t5.*2.0+Rp3.*Rp4.*t2.*t5.*2.0;
et4 = Rp3.*Rp5.*t3.*t4.*2.0-P1_1.*Rp4.*Rp5.*t3.*t4.*2.0-P1_4.*Rp4.*Rp5.*t2.*t3.*2.0-P3_1.*Rp4.*Rp5.*t2.*t3.*2.0-P3_4.*Rp4.*Rp5.*t2.*t3.*2.0+R1.*Rp4.*Rp5.*t3.*t4.*2.0+R3.*Rp4.*Rp5.*t2.*t3.*2.0;
et5 = -Rpp1.*t4.*t5-Rpp3.*t2.*t5-P1_1.*t4.*t5.*t6-P1_1.*t4.*t5.*t7-P1_4.*t2.*t5.*t6-P1_4.*t2.*t5.*t7-P3_1.*t2.*t5.*t6-P3_1.*t2.*t5.*t7-P3_4.*t2.*t5.*t6-P3_4.*t2.*t5.*t7+R1.*t4.*t5.*t6+R3.*t2.*t5.*t6+R1.*t4.*t5.*t7+R3.*t2.*t5.*t7+P1_1.*Rpp4.*t2.*t5+P1_1.*Rpp5.*t3.*t4+P1_4.*Rpp5.*t2.*t3-P1_4.*Rpp4.*t4.*t5+P3_1.*Rpp5.*t2.*t3-P3_1.*Rpp4.*t4.*t5+P3_4.*Rpp5.*t2.*t3-P3_4.*Rpp4.*t4.*t5-R1.*Rpp4.*t2.*t5-R1.*Rpp5.*t3.*t4-R3.*Rpp5.*t2.*t3+R3.*Rpp4.*t4.*t5-Rp1.*Rp4.*t2.*t5.*2.0-Rp1.*Rp5.*t3.*t4.*2.0-Rp3.*Rp5.*t2.*t3.*2.0+Rp3.*Rp4.*t4.*t5.*2.0+P1_1.*Rp4.*Rp5.*t2.*t3.*2.0;
et6 = P1_4.*Rp4.*Rp5.*t3.*t4.*-2.0-P3_1.*Rp4.*Rp5.*t3.*t4.*2.0-P3_4.*Rp4.*Rp5.*t3.*t4.*2.0-R1.*Rp4.*Rp5.*t2.*t3.*2.0+R3.*Rp4.*Rp5.*t3.*t4.*2.0;
et7 = -Rpp1.*t5-P2_1.*Rpp5.*t3-R1.*Rpp5.*t3-Rp1.*Rp5.*t3.*2.0+P2_1.*t5.*t7+R1.*t5.*t7+Rpp1.*t2.*t3-Rpp3.*t3.*t4+P1_1.*t2.*t3.*t6+P1_1.*t2.*t3.*t7-P1_4.*t3.*t4.*t6-P1_4.*t3.*t4.*t7-P3_1.*t3.*t4.*t6-P3_1.*t3.*t4.*t7-P3_4.*t3.*t4.*t6-P3_4.*t3.*t4.*t7-R1.*t2.*t3.*t6-R1.*t2.*t3.*t7+R3.*t3.*t4.*t6+R3.*t3.*t4.*t7+P1_1.*Rpp4.*t3.*t4+P1_1.*Rpp5.*t2.*t5+P1_4.*Rpp4.*t2.*t3-P1_4.*Rpp5.*t4.*t5+P3_1.*Rpp4.*t2.*t3+P3_4.*Rpp4.*t2.*t3-P3_1.*Rpp5.*t4.*t5-P3_4.*Rpp5.*t4.*t5-R1.*Rpp4.*t3.*t4-R3.*Rpp4.*t2.*t3-R1.*Rpp5.*t2.*t5+R3.*Rpp5.*t4.*t5-Rp1.*Rp4.*t3.*t4.*2.0;
et8 = Rp3.*Rp4.*t2.*t3.*-2.0-Rp1.*Rp5.*t2.*t5.*2.0+Rp3.*Rp5.*t4.*t5.*2.0-P1_1.*Rp4.*Rp5.*t4.*t5.*2.0-P1_4.*Rp4.*Rp5.*t2.*t5.*2.0-P3_1.*Rp4.*Rp5.*t2.*t5.*2.0-P3_4.*Rp4.*Rp5.*t2.*t5.*2.0+R1.*Rp4.*Rp5.*t4.*t5.*2.0+R3.*Rp4.*Rp5.*t2.*t5.*2.0;
mt1 = [-Rpp5.*t3+t5.*t7-Rpp4.*t3.*t4-Rpp5.*t2.*t5-t2.*t3.*t6-t2.*t3.*t7+Rp4.*Rp5.*t4.*t5.*2.0,-Rpp5.*t5-t3.*t7+Rpp5.*t2.*t3-Rpp4.*t4.*t5-t2.*t5.*t6-t2.*t5.*t7-Rp4.*Rp5.*t3.*t4.*2.0,Rpp4.*t2-t4.*t6,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-Rpp4.*t2.*t3+Rpp5.*t4.*t5+t3.*t4.*t6+t3.*t4.*t7+Rp4.*Rp5.*t2.*t5.*2.0,-Rpp4.*t2.*t5-Rpp5.*t3.*t4+t4.*t5.*t6+t4.*t5.*t7-Rp4.*Rp5.*t2.*t3.*2.0,-Rpp4.*t4-t2.*t6,0.0,0.0,et1+et2,et5+et6];
mt2 = [Rpp1.*t2-Rpp3.*t4+P1_1.*Rpp4.*t4+P1_4.*Rpp4.*t2+P3_1.*Rpp4.*t2+P3_4.*Rpp4.*t2-R1.*Rpp4.*t4-R3.*Rpp4.*t2-Rp1.*Rp4.*t4.*2.0-Rp3.*Rp4.*t2.*2.0+P1_1.*t2.*t6-P1_4.*t4.*t6-P3_1.*t4.*t6-P3_4.*t4.*t6-R1.*t2.*t6+R3.*t4.*t6,0.0,0.0,et3+et4,et7+et8,0.0,0.0,0.0];
J2P_ra = reshape([mt1,mt2],5,5);
