function J_ra = kin_J_ra_xyzbc(in1,in2)
%kin_J_ra_xyzbc
%    J_ra = kin_J_ra_xyzbc(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    13-Jun-2022 18:00:01

%Jacobian Kinematics ( forward ) : 
%INPUTS : 
%	r_a : 5 x 1 : pose vector( joint )
%	v_a : 5 x 1 : speed vector( joint )
%	p   : 5 x 1 : parameters
%OUTPUTS : 
%	M   : 5 x 5 : resulting matrix
%#codegen
P1_1 = in2(1);
P1_4 = in2(10);
P2_1 = in2(2);
P3_1 = in2(3);
P3_4 = in2(12);
R1 = in1(1,:);
R3 = in1(3,:);
R4 = in1(4,:);
R5 = in1(5,:);
t2 = cos(R4);
t3 = cos(R5);
t4 = sin(R4);
t5 = sin(R5);
t6 = P1_4.*t2;
t7 = P3_1.*t2;
t8 = P3_4.*t2;
t9 = R3.*t2;
t10 = P1_1.*t4;
t11 = R1.*t4;
t12 = -t9;
t13 = -t11;
t14 = t6+t7+t8+t10+t12+t13;
J_ra = reshape([-t5+t2.*t3,t3+t2.*t5,t4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-t3.*t4,-t4.*t5,t2,0.0,0.0,t3.*t14,t5.*t14,-P1_1.*t2+P1_4.*t4+P3_1.*t4+P3_4.*t4+R1.*t2-R3.*t4,1.0,0.0,-P2_1.*t3-R1.*t3+P1_1.*t2.*t5-P1_4.*t4.*t5-P3_1.*t4.*t5-P3_4.*t4.*t5-R1.*t2.*t5+R3.*t4.*t5,-P2_1.*t5-R1.*t5-P1_1.*t2.*t3+P1_4.*t3.*t4+P3_1.*t3.*t4+P3_4.*t3.*t4+R1.*t2.*t3-R3.*t3.*t4,0.0,0.0,1.0],[5,5]);
