function J2P_ra = kin_J2P_ra_xyzbc(in1,in2,in3,in4)
%kin_J2P_ra_xyzbc
%    J2P_ra = kin_J2P_ra_xyzbc(IN1,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 9.1.
%    30-Aug-2023 15:04:01

%Jacobian second derivative ( forward ) : 
%INPUTS : 
%	r_a : 5 x 1 : pose vector( joint )
%	v_a : 5 x 1 : speed vector( joint )
%	a_a : 5 x 1 : acceleration vector( joint )
%	j_a : 5 x 1 : jerk vector( joint )
%	p   : 5 x 1 : parameters
%OUTPUTS : 
%	M   : 5 x 5 : resulting matrix
%#codegen
A1 = in1(1,:);
A2 = in1(2,:);
A3 = in1(3,:);
A4 = in1(4,:);
A5 = in1(5,:);
Ap1 = in2(1,:);
Ap2 = in2(2,:);
Ap3 = in2(3,:);
Ap4 = in2(4,:);
Ap5 = in2(5,:);
App1 = in3(1,:);
App2 = in3(2,:);
App3 = in3(3,:);
App4 = in3(4,:);
App5 = in3(5,:);
P1_1 = in4(1);
P1_4 = in4(10);
P2_1 = in4(2);
P3_1 = in4(3);
P3_4 = in4(12);
t2 = cos(A4);
t3 = cos(A5);
t4 = sin(A4);
t5 = sin(A5);
t6 = Ap4.^2;
t7 = Ap5.^2;
et1 = -App1.*t3.*t4-App3.*t2.*t3-P1_1.*t3.*t4.*t6-P1_1.*t3.*t4.*t7-P1_4.*t2.*t3.*t6-P1_4.*t2.*t3.*t7-P3_1.*t2.*t3.*t6-P3_1.*t2.*t3.*t7-P3_4.*t2.*t3.*t6-P3_4.*t2.*t3.*t7-A1.*App4.*t2.*t3+A3.*App4.*t3.*t4+A1.*App5.*t4.*t5+A3.*App5.*t2.*t5-Ap1.*Ap4.*t2.*t3.*2.0+Ap3.*Ap4.*t3.*t4.*2.0+Ap1.*Ap5.*t4.*t5.*2.0+Ap3.*Ap5.*t2.*t5.*2.0+App4.*P1_1.*t2.*t3-App4.*P1_4.*t3.*t4-App5.*P1_1.*t4.*t5-App5.*P1_4.*t2.*t5-App4.*P3_1.*t3.*t4-App5.*P3_1.*t2.*t5-App4.*P3_4.*t3.*t4-App5.*P3_4.*t2.*t5+A1.*t3.*t4.*t6+A3.*t2.*t3.*t6+A1.*t3.*t4.*t7+A3.*t2.*t3.*t7+A1.*Ap4.*Ap5.*t2.*t5.*2.0;
et2 = A3.*Ap4.*Ap5.*t4.*t5.*-2.0-Ap4.*Ap5.*P1_1.*t2.*t5.*2.0+Ap4.*Ap5.*P1_4.*t4.*t5.*2.0+Ap4.*Ap5.*P3_1.*t4.*t5.*2.0+Ap4.*Ap5.*P3_4.*t4.*t5.*2.0;
et3 = -App2.*t3+A2.*App5.*t5+Ap2.*Ap5.*t5.*2.0+App5.*P2_1.*t5+A2.*t3.*t7-App1.*t2.*t5+App3.*t4.*t5+P2_1.*t3.*t7-P1_1.*t2.*t5.*t6-P1_1.*t2.*t5.*t7+P1_4.*t4.*t5.*t6+P1_4.*t4.*t5.*t7+P3_1.*t4.*t5.*t6+P3_1.*t4.*t5.*t7+P3_4.*t4.*t5.*t6+P3_4.*t4.*t5.*t7-A1.*App5.*t2.*t3+A1.*App4.*t4.*t5+A3.*App4.*t2.*t5+A3.*App5.*t3.*t4-Ap1.*Ap5.*t2.*t3.*2.0+Ap1.*Ap4.*t4.*t5.*2.0+Ap3.*Ap4.*t2.*t5.*2.0+Ap3.*Ap5.*t3.*t4.*2.0+App5.*P1_1.*t2.*t3-App4.*P1_1.*t4.*t5-App4.*P1_4.*t2.*t5-App5.*P1_4.*t3.*t4-App4.*P3_1.*t2.*t5-App5.*P3_1.*t3.*t4-App4.*P3_4.*t2.*t5-App5.*P3_4.*t3.*t4+A1.*t2.*t5.*t6+A1.*t2.*t5.*t7-A3.*t4.*t5.*t6;
et4 = -A3.*t4.*t5.*t7+A1.*Ap4.*Ap5.*t3.*t4.*2.0+A3.*Ap4.*Ap5.*t2.*t3.*2.0-Ap4.*Ap5.*P1_1.*t3.*t4.*2.0-Ap4.*Ap5.*P1_4.*t2.*t3.*2.0-Ap4.*Ap5.*P3_1.*t2.*t3.*2.0-Ap4.*Ap5.*P3_4.*t2.*t3.*2.0;
et5 = -App1.*t4.*t5-App3.*t2.*t5-P1_1.*t4.*t5.*t6-P1_1.*t4.*t5.*t7-P1_4.*t2.*t5.*t6-P1_4.*t2.*t5.*t7-P3_1.*t2.*t5.*t6-P3_1.*t2.*t5.*t7-P3_4.*t2.*t5.*t6-P3_4.*t2.*t5.*t7-A1.*App4.*t2.*t5-A1.*App5.*t3.*t4-A3.*App5.*t2.*t3+A3.*App4.*t4.*t5-Ap1.*Ap4.*t2.*t5.*2.0-Ap1.*Ap5.*t3.*t4.*2.0-Ap3.*Ap5.*t2.*t3.*2.0+Ap3.*Ap4.*t4.*t5.*2.0+App4.*P1_1.*t2.*t5+App5.*P1_1.*t3.*t4+App5.*P1_4.*t2.*t3-App4.*P1_4.*t4.*t5+App5.*P3_1.*t2.*t3-App4.*P3_1.*t4.*t5+App5.*P3_4.*t2.*t3-App4.*P3_4.*t4.*t5+A1.*t4.*t5.*t6+A3.*t2.*t5.*t6+A1.*t4.*t5.*t7+A3.*t2.*t5.*t7-A1.*Ap4.*Ap5.*t2.*t3.*2.0;
et6 = A3.*Ap4.*Ap5.*t3.*t4.*2.0+Ap4.*Ap5.*P1_1.*t2.*t3.*2.0-Ap4.*Ap5.*P1_4.*t3.*t4.*2.0-Ap4.*Ap5.*P3_1.*t3.*t4.*2.0-Ap4.*Ap5.*P3_4.*t3.*t4.*2.0;
et7 = -App2.*t5-A2.*App5.*t3-Ap2.*Ap5.*t3.*2.0-App5.*P2_1.*t3+A2.*t5.*t7+App1.*t2.*t3-App3.*t3.*t4+P2_1.*t5.*t7+P1_1.*t2.*t3.*t6+P1_1.*t2.*t3.*t7-P1_4.*t3.*t4.*t6-P1_4.*t3.*t4.*t7-P3_1.*t3.*t4.*t6-P3_1.*t3.*t4.*t7-P3_4.*t3.*t4.*t6-P3_4.*t3.*t4.*t7-A1.*App4.*t3.*t4-A3.*App4.*t2.*t3-A1.*App5.*t2.*t5+A3.*App5.*t4.*t5-Ap1.*Ap4.*t3.*t4.*2.0-Ap3.*Ap4.*t2.*t3.*2.0-Ap1.*Ap5.*t2.*t5.*2.0+Ap3.*Ap5.*t4.*t5.*2.0+App4.*P1_1.*t3.*t4+App4.*P1_4.*t2.*t3+App5.*P1_1.*t2.*t5-App5.*P1_4.*t4.*t5+App4.*P3_1.*t2.*t3+App4.*P3_4.*t2.*t3-App5.*P3_1.*t4.*t5-App5.*P3_4.*t4.*t5-A1.*t2.*t3.*t6;
et8 = -A1.*t2.*t3.*t7+A3.*t3.*t4.*t6+A3.*t3.*t4.*t7+A1.*Ap4.*Ap5.*t4.*t5.*2.0+A3.*Ap4.*Ap5.*t2.*t5.*2.0-Ap4.*Ap5.*P1_1.*t4.*t5.*2.0-Ap4.*Ap5.*P1_4.*t2.*t5.*2.0-Ap4.*Ap5.*P3_1.*t2.*t5.*2.0-Ap4.*Ap5.*P3_4.*t2.*t5.*2.0;
mt1 = [-App4.*t3.*t4-App5.*t2.*t5-t2.*t3.*t6-t2.*t3.*t7+Ap4.*Ap5.*t4.*t5.*2.0,App5.*t2.*t3-App4.*t4.*t5-t2.*t5.*t6-t2.*t5.*t7-Ap4.*Ap5.*t3.*t4.*2.0,App4.*t2-t4.*t6,0.0,0.0,-App5.*t3+t5.*t7,-App5.*t5-t3.*t7,0.0,0.0,0.0,-App4.*t2.*t3+App5.*t4.*t5+t3.*t4.*t6+t3.*t4.*t7+Ap4.*Ap5.*t2.*t5.*2.0,-App4.*t2.*t5-App5.*t3.*t4+t4.*t5.*t6+t4.*t5.*t7-Ap4.*Ap5.*t2.*t3.*2.0,-App4.*t4-t2.*t6,0.0,0.0,et1+et2,et5+et6];
mt2 = [App1.*t2-App3.*t4-A1.*App4.*t4-A3.*App4.*t2-Ap1.*Ap4.*t4.*2.0-Ap3.*Ap4.*t2.*2.0+App4.*P1_1.*t4+App4.*P1_4.*t2+App4.*P3_1.*t2+App4.*P3_4.*t2-A1.*t2.*t6+A3.*t4.*t6+P1_1.*t2.*t6-P1_4.*t4.*t6-P3_1.*t4.*t6-P3_4.*t4.*t6,0.0,0.0,et3+et4,et7+et8,0.0,0.0,0.0];
J2P_ra = reshape([mt1,mt2],5,5);
