function J2P_jt = kin_xyzbc_tt_J2P_jt(in1,in2,in3,in4)
%kin_xyzbc_tt_J2P_jt
%    J2P_jt = kin_xyzbc_tt_J2P_jt(IN1,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 9.1.
%    07-Nov-2023 14:54:38

%Jacobian second derivative ( Inverse Kinematics ) : 
%INPUTS : 
%	r_t    (5x1) : pose vector ( piece frame )
%	v_t    (5x1) : speed vector ( piece frame )
%	a_t    (5x1) : acceleration vector( piece frame )
%	j_t    (5x1) : jerk vector( piece frame )
%	p      (3x5) : parameters
%OUTPUTS : 
%	M      (5x5) : resulting matrix
%#codegen
b = in1(4,:);
c = in1(5,:);
offB1 = in4(10);
offC1 = in4(13);
offB3 = in4(12);
offC2 = in4(14);
offC3 = in4(15);
offP1 = in4(7);
offP2 = in4(8);
offP3 = in4(9);
tp1 = in2(1,:);
tp2 = in2(2,:);
tp3 = in2(3,:);
tp4 = in2(4,:);
tp5 = in2(5,:);
tpp1 = in3(1,:);
tpp2 = in3(2,:);
tpp3 = in3(3,:);
tpp4 = in3(4,:);
tpp5 = in3(5,:);
x = in1(1,:);
y = in1(2,:);
z = in1(3,:);
t2 = cos(b);
t3 = cos(c);
t4 = sin(b);
t5 = sin(c);
t6 = tp4.^2;
t7 = tp5.^2;
et1 = t2.*tpp3+offB1.*t4.*t6-offB3.*t2.*t6-offC3.*t2.*t6-offP3.*t2.*t6-offB1.*t2.*tpp4-offB3.*t4.*tpp4-offC3.*t4.*tpp4-offP3.*t4.*tpp4-t3.*t4.*tpp1+t4.*t5.*tpp2-t4.*tp3.*tp4.*2.0-t2.*t6.*z-t4.*tpp4.*z+offC1.*t3.*t4.*t6+offC1.*t3.*t4.*t7-offC2.*t4.*t5.*t6-offC2.*t4.*t5.*t7+offP1.*t3.*t4.*t6+offP1.*t3.*t4.*t7-offP2.*t4.*t5.*t6-offP2.*t4.*t5.*t7-offC1.*t2.*t3.*tpp4+offC2.*t2.*t5.*tpp4+offC2.*t3.*t4.*tpp5+offC1.*t4.*t5.*tpp5-offP1.*t2.*t3.*tpp4+offP2.*t2.*t5.*tpp4+offP2.*t3.*t4.*tpp5+offP1.*t4.*t5.*tpp5-t2.*t3.*tp1.*tp4.*2.0+t2.*t5.*tp2.*tp4.*2.0+t3.*t4.*tp2.*tp5.*2.0+t4.*t5.*tp1.*tp5.*2.0+t3.*t4.*t6.*x;
et2 = t3.*t4.*t7.*x-t2.*t3.*tpp4.*x+t4.*t5.*tpp5.*x-t4.*t5.*t6.*y-t4.*t5.*t7.*y+t2.*t5.*tpp4.*y+t3.*t4.*tpp5.*y+offC2.*t2.*t3.*tp4.*tp5.*2.0+offC1.*t2.*t5.*tp4.*tp5.*2.0+offP2.*t2.*t3.*tp4.*tp5.*2.0+offP1.*t2.*t5.*tp4.*tp5.*2.0+t2.*t5.*tp4.*tp5.*x.*2.0+t2.*t3.*tp4.*tp5.*y.*2.0;
et3 = -t2.*t3.*tpp2-t2.*t5.*tpp1+offC2.*t2.*t3.*t6+offC1.*t2.*t5.*t6+offC2.*t2.*t3.*t7+offC1.*t2.*t5.*t7+offP2.*t2.*t3.*t6+offP1.*t2.*t5.*t6+offP2.*t2.*t3.*t7+offP1.*t2.*t5.*t7-offC1.*t2.*t3.*tpp5+offC2.*t3.*t4.*tpp4+offC1.*t4.*t5.*tpp4+offC2.*t2.*t5.*tpp5-offP1.*t2.*t3.*tpp5+offP2.*t3.*t4.*tpp4+offP1.*t4.*t5.*tpp4+offP2.*t2.*t5.*tpp5-t2.*t3.*tp1.*tp5.*2.0+t3.*t4.*tp2.*tp4.*2.0+t2.*t5.*tp2.*tp5.*2.0+t4.*t5.*tp1.*tp4.*2.0+t2.*t5.*t6.*x+t2.*t5.*t7.*x-t2.*t3.*tpp5.*x+t4.*t5.*tpp4.*x+t2.*t3.*t6.*y+t2.*t3.*t7.*y+t3.*t4.*tpp4.*y+t2.*t5.*tpp5.*y+offC1.*t3.*t4.*tp4.*tp5.*2.0-offC2.*t4.*t5.*tp4.*tp5.*2.0+offP1.*t3.*t4.*tp4.*tp5.*2.0-offP2.*t4.*t5.*tp4.*tp5.*2.0+t3.*t4.*tp4.*tp5.*x.*2.0;
et4 = t4.*t5.*tp4.*tp5.*y.*-2.0;
et5 = -t4.*tpp3+offB1.*t2.*t6+offB3.*t4.*t6+offC3.*t4.*t6+offP3.*t4.*t6+offB1.*t4.*tpp4-offB3.*t2.*tpp4-offC3.*t2.*tpp4-offP3.*t2.*tpp4-t2.*t3.*tpp1+t2.*t5.*tpp2-t2.*tp3.*tp4.*2.0+t4.*t6.*z-t2.*tpp4.*z+offC1.*t2.*t3.*t6+offC1.*t2.*t3.*t7-offC2.*t2.*t5.*t6-offC2.*t2.*t5.*t7+offP1.*t2.*t3.*t6+offP1.*t2.*t3.*t7-offP2.*t2.*t5.*t6-offP2.*t2.*t5.*t7+offC1.*t3.*t4.*tpp4+offC2.*t2.*t3.*tpp5+offC1.*t2.*t5.*tpp5-offC2.*t4.*t5.*tpp4+offP1.*t3.*t4.*tpp4+offP2.*t2.*t3.*tpp5+offP1.*t2.*t5.*tpp5-offP2.*t4.*t5.*tpp4+t2.*t3.*tp2.*tp5.*2.0+t3.*t4.*tp1.*tp4.*2.0+t2.*t5.*tp1.*tp5.*2.0-t4.*t5.*tp2.*tp4.*2.0+t2.*t3.*t6.*x+t2.*t3.*t7.*x;
et6 = t3.*t4.*tpp4.*x+t2.*t5.*tpp5.*x-t2.*t5.*t6.*y-t2.*t5.*t7.*y+t2.*t3.*tpp5.*y-t4.*t5.*tpp4.*y-offC2.*t3.*t4.*tp4.*tp5.*2.0-offC1.*t4.*t5.*tp4.*tp5.*2.0-offP2.*t3.*t4.*tp4.*tp5.*2.0-offP1.*t4.*t5.*tp4.*tp5.*2.0-t4.*t5.*tp4.*tp5.*x.*2.0-t3.*t4.*tp4.*tp5.*y.*2.0;
et7 = t3.*t4.*tpp2+t4.*t5.*tpp1-offC2.*t3.*t4.*t6-offC1.*t4.*t5.*t6-offC2.*t3.*t4.*t7-offC1.*t4.*t5.*t7-offP2.*t3.*t4.*t6-offP1.*t4.*t5.*t6-offP2.*t3.*t4.*t7-offP1.*t4.*t5.*t7+offC2.*t2.*t3.*tpp4+offC1.*t2.*t5.*tpp4+offC1.*t3.*t4.*tpp5-offC2.*t4.*t5.*tpp5+offP2.*t2.*t3.*tpp4+offP1.*t2.*t5.*tpp4+offP1.*t3.*t4.*tpp5-offP2.*t4.*t5.*tpp5+t2.*t3.*tp2.*tp4.*2.0+t2.*t5.*tp1.*tp4.*2.0+t3.*t4.*tp1.*tp5.*2.0-t4.*t5.*tp2.*tp5.*2.0-t4.*t5.*t6.*x-t4.*t5.*t7.*x+t2.*t5.*tpp4.*x+t3.*t4.*tpp5.*x-t3.*t4.*t6.*y-t3.*t4.*t7.*y+t2.*t3.*tpp4.*y-t4.*t5.*tpp5.*y+offC1.*t2.*t3.*tp4.*tp5.*2.0-offC2.*t2.*t5.*tp4.*tp5.*2.0;
et8 = offP1.*t2.*t3.*tp4.*tp5.*2.0-offP2.*t2.*t5.*tp4.*tp5.*2.0+t2.*t3.*tp4.*tp5.*x.*2.0-t2.*t5.*tp4.*tp5.*y.*2.0;
mt1 = [-t2.*t3.*t6-t2.*t3.*t7-t3.*t4.*tpp4-t2.*t5.*tpp5+t4.*t5.*tp4.*tp5.*2.0,-t5.*t7+t3.*tpp5,t3.*t4.*t6+t3.*t4.*t7-t2.*t3.*tpp4+t4.*t5.*tpp5+t2.*t5.*tp4.*tp5.*2.0,0.0,0.0,t2.*t5.*t6+t2.*t5.*t7-t2.*t3.*tpp5+t4.*t5.*tpp4+t3.*t4.*tp4.*tp5.*2.0,-t3.*t7-t5.*tpp5,-t4.*t5.*t6-t4.*t5.*t7+t2.*t5.*tpp4+t3.*t4.*tpp5+t2.*t3.*tp4.*tp5.*2.0,0.0,0.0,-t4.*t6+t2.*tpp4,0.0,-t2.*t6-t4.*tpp4,0.0,0.0,et1+et2,0.0,et5+et6,0.0,0.0,et3+et4];
mt2 = [t3.*tpp1-t5.*tpp2-offC1.*t3.*t7+offC2.*t5.*t7-offP1.*t3.*t7+offP2.*t5.*t7-offC2.*t3.*tpp5-offC1.*t5.*tpp5-offP2.*t3.*tpp5-offP1.*t5.*tpp5-t3.*tp2.*tp5.*2.0-t5.*tp1.*tp5.*2.0-t3.*t7.*x-t5.*tpp5.*x+t5.*t7.*y-t3.*tpp5.*y,et7+et8,0.0,0.0];
J2P_jt = reshape([mt1,mt2],5,5);
