function speed_j = kin_inverse_jacobian_xyzbc(in1,in2,in3)
%KIN_INVERSE_JACOBIAN_XYZBC
%    SPEED_J = KIN_INVERSE_JACOBIAN_XYZBC(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    16-Jun-2022 10:26:19

P1_2 = in3(4);
P1_3 = in3(7);
P2_2 = in3(5);
P2_3 = in3(8);
P2_4 = in3(11);
P3_2 = in3(6);
P3_3 = in3(9);
P3_4 = in3(12);
R1 = in1(1,:);
R2 = in1(2,:);
R3 = in1(3,:);
R5 = in1(5,:);
R6 = in1(6,:);
Rp1 = in2(1,:);
Rp2 = in2(2,:);
Rp3 = in2(3,:);
Rp5 = in2(5,:);
Rp6 = in2(6,:);
t2 = cos(R5);
t3 = cos(R6);
t4 = sin(R5);
t5 = sin(R6);
t6 = P2_4+R3;
t13 = -P3_4;
t7 = P2_2.*t3;
t8 = P2_3.*t3;
t9 = R2.*t3;
t10 = P1_2.*t5;
t11 = P1_3.*t5;
t12 = R1.*t5;
t14 = P3_2+t13;
t15 = -t8;
t16 = -t9;
t17 = t7+t10+t11+t12+t15+t16;
speed_j = [Rp3.*t4-Rp5.*(-P3_3.*t2-t2.*t6-t2.*t14+P1_2.*t3.*t4+P1_3.*t3.*t4-P2_2.*t4.*t5+P2_3.*t4.*t5+R1.*t3.*t4+R2.*t4.*t5)+Rp1.*t2.*t3+Rp2.*t2.*t5-Rp6.*t2.*t17;Rp2.*t3-Rp1.*t5-Rp6.*(P1_2.*t3+P1_3.*t3-P2_2.*t5+P2_3.*t5+R1.*t3+R2.*t5);Rp3.*t2-Rp5.*(P3_3.*t4+t4.*t6+t4.*t14+P1_2.*t2.*t3+P1_3.*t2.*t3-P2_2.*t2.*t5+P2_3.*t2.*t5+R1.*t2.*t3+R2.*t2.*t5)-Rp1.*t3.*t4-Rp2.*t4.*t5+Rp6.*t4.*t17];
