function JP_ra = kin_JP_ra_xyzbc(in1,in2,in3)
%kin_JP_ra_xyzbc
%    JP_ra = kin_JP_ra_xyzbc(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    17-Jun-2022 14:39:09

%Jacobian first derivative ( forward ) : 
%INPUTS : 
%	r_a : 5 x 1 : pose vector( joint )
%	v_a : 5 x 1 : speed vector( joint )
%	a_a : 5 x 1 : acceleration vector( joint )
%	p   : 5 x 1 : parameters
%OUTPUTS : 
%	M   : 5 x 5 : resulting matrix
%#codegen
Ap1 = in2(1,:);
Ap3 = in2(3,:);
Ap4 = in2(4,:);
Ap5 = in2(5,:);
P1_1 = in3(1);
P1_4 = in3(10);
P2_1 = in3(2);
P3_1 = in3(3);
P3_4 = in3(12);
R1 = in1(1,:);
R3 = in1(3,:);
R4 = in1(4,:);
R5 = in1(5,:);
t2 = cos(R4);
t3 = cos(R5);
t4 = sin(R4);
t5 = sin(R5);
t6 = P1_1.*t2;
t7 = P1_4.*t2;
t8 = P3_1.*t2;
t9 = P3_4.*t2;
t10 = R1.*t2;
t11 = R3.*t2;
t12 = P1_1.*t4;
t13 = P1_4.*t4;
t14 = P3_1.*t4;
t15 = P3_4.*t4;
t16 = R1.*t4;
t17 = R3.*t4;
t18 = t2.*t3;
t19 = t2.*t5;
t20 = -t6;
t21 = -t11;
t22 = -t16;
t23 = -t17;
t24 = -t18;
t25 = t3+t19;
t26 = t5+t24;
t27 = t10+t13+t14+t15+t20+t23;
t28 = t7+t8+t9+t12+t21+t22;
mt1 = [-Ap5.*t25-Ap4.*t3.*t4,-Ap5.*t26-Ap4.*t4.*t5,Ap4.*t2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Ap4.*t24+Ap5.*t4.*t5,-Ap4.*t19-Ap5.*t3.*t4,-Ap4.*t4,0.0,0.0,Ap3.*t24-Ap1.*t3.*t4-Ap4.*t3.*t27-Ap5.*t5.*t28,-Ap3.*t19-Ap1.*t4.*t5-Ap4.*t5.*t27+Ap5.*t3.*t28,Ap1.*t2-Ap3.*t4+Ap4.*t7+Ap4.*t8+Ap4.*t9+Ap4.*t12+Ap4.*t21+Ap4.*t22,0.0,0.0,-Ap1.*t25+Ap5.*(P2_1.*t5+R1.*t5+t3.*t6-t3.*t10-t3.*t13-t3.*t14-t3.*t15+t3.*t17)+Ap3.*t4.*t5-Ap4.*t5.*t28];
mt2 = [-Ap1.*t26-Ap5.*(P2_1.*t3+R1.*t3+t5.*t10+t5.*t13+t5.*t14+t5.*t15+t5.*t20+t5.*t23)-Ap3.*t3.*t4+Ap4.*t3.*t28,0.0,0.0,0.0];
JP_ra = reshape([mt1,mt2],5,5);
