function J_ar = kin_J_ar_xyzbc(in1,in2)
%kin_J_ar_xyzbc
%    J_ar = kin_J_ar_xyzbc(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    17-Jun-2022 14:39:08

%Jacobian Kinematics ( backward ) : 
%INPUTS : 
%	r_r : 5 x 1 : pose vector ( relative )
%	v_r : 5 x 1 : speed vector ( relative )
%	p   : 5 x 1 : parameters
%OUTPUTS : 
%	M   : 5 x 5 : resulting matrix
%#codegen
P1_2 = in2(4);
P1_3 = in2(7);
P2_2 = in2(5);
P2_3 = in2(8);
P2_4 = in2(11);
P3_2 = in2(6);
P3_3 = in2(9);
P3_4 = in2(12);
R1 = in1(1,:);
R2 = in1(2,:);
R3 = in1(3,:);
R4 = in1(4,:);
R5 = in1(5,:);
t2 = cos(R4);
t3 = cos(R5);
t4 = sin(R4);
t5 = sin(R5);
t6 = P2_4+R3;
t13 = -P3_4;
t7 = P2_2.*t3;
t8 = P2_3.*t3;
t9 = R2.*t3;
t10 = P1_2.*t5;
t11 = P1_3.*t5;
t12 = R1.*t5;
t14 = P3_2+t13;
t15 = -t8;
t16 = -t9;
t17 = t7+t10+t11+t12+t15+t16;
J_ar = reshape([t2.*t3,-t5,-t3.*t4,0.0,0.0,t2.*t5,t3,-t4.*t5,0.0,0.0,t4,0.0,t2,0.0,0.0,P3_3.*t2+t2.*t6+t2.*t14-P1_2.*t3.*t4-P1_3.*t3.*t4+P2_2.*t4.*t5-P2_3.*t4.*t5-R1.*t3.*t4-R2.*t4.*t5,0.0,-P3_3.*t4-t4.*t6-t4.*t14-P1_2.*t2.*t3-P1_3.*t2.*t3+P2_2.*t2.*t5-P2_3.*t2.*t5-R1.*t2.*t3-R2.*t2.*t5,1.0,0.0,-t2.*t17,-P1_2.*t3-P1_3.*t3+P2_2.*t5-P2_3.*t5-R1.*t3-R2.*t5,t4.*t17,0.0,1.0],[5,5]);
