function J_ra = kin_J_ra_xyzbc(in1,in2)
%kin_J_ra_xyzbc
%    J_ra = kin_J_ra_xyzbc(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.1.
%    01-Sep-2023 14:01:21

%Jacobian Kinematics ( forward ) : 
%INPUTS : 
%	r_a : 5 x 1 : pose vector( joint )
%	v_a : 5 x 1 : speed vector( joint )
%	p   : 5 x 1 : parameters
%OUTPUTS : 
%	M   : 5 x 5 : resulting matrix
%#codegen
A1 = in1(1,:);
A2 = in1(2,:);
A3 = in1(3,:);
A4 = in1(4,:);
A5 = in1(5,:);
P1_1 = in2(1);
P1_4 = in2(10);
P2_1 = in2(2);
P3_1 = in2(3);
P3_4 = in2(12);
t2 = cos(A4);
t3 = cos(A5);
t4 = sin(A4);
t5 = sin(A5);
t6 = A3.*t2;
t7 = P1_4.*t2;
t8 = P3_1.*t2;
t9 = P3_4.*t2;
t10 = A1.*t4;
t11 = P1_1.*t4;
t12 = -t6;
t13 = -t10;
t14 = t7+t8+t9+t11+t12+t13;
J_ra = reshape([t2.*t3,t2.*t5,t4,0.0,0.0,-t5,t3,0.0,0.0,0.0,-t3.*t4,-t4.*t5,t2,0.0,0.0,t3.*t14,t5.*t14,A1.*t2-A3.*t4-P1_1.*t2+P1_4.*t4+P3_1.*t4+P3_4.*t4,1.0,0.0,-A2.*t3-P2_1.*t3-A1.*t2.*t5+A3.*t4.*t5+P1_1.*t2.*t5-P1_4.*t4.*t5-P3_1.*t4.*t5-P3_4.*t4.*t5,-A2.*t5-P2_1.*t5+A1.*t2.*t3-A3.*t3.*t4-P1_1.*t2.*t3+P1_4.*t3.*t4+P3_1.*t3.*t4+P3_4.*t3.*t4,0.0,0.0,1.0],[5,5]);
