function joint = kin_inverse_xyzbc(in1,in2)
%KIN_INVERSE_XYZBC
%    JOINT = KIN_INVERSE_XYZBC(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.1.
%    01-Sep-2023 14:01:21

%Backward Kinematics ( Inverse Geometrique Model ) : 
%INPUTS : 
%	r_r : 5 x 1 : pose vector ( relative )
%	p   : 5 x 1 : parameters
%OUTPUTS : 
%	r_a : 5 x 1 : pose vector( joint )
%#codegen
P1_1 = in2(1);
P1_2 = in2(4);
P1_3 = in2(7);
P1_4 = in2(10);
P2_1 = in2(2);
P2_2 = in2(5);
P2_3 = in2(8);
P2_4 = in2(11);
P3_1 = in2(3);
P3_2 = in2(6);
P3_3 = in2(9);
P3_4 = in2(12);
R1 = in1(1,:);
R2 = in1(2,:);
R3 = in1(3,:);
R4 = in1(4,:);
R5 = in1(5,:);
t2 = cos(R4);
t3 = cos(R5);
t4 = sin(R4);
t5 = sin(R5);
t6 = P2_4+R3;
t7 = -P3_4;
t8 = P3_2+t7;
joint = [P1_1+P3_3.*t4+t4.*t6+t4.*t8+P1_2.*t2.*t3+P1_3.*t2.*t3-P2_2.*t2.*t5+P2_3.*t2.*t5+R1.*t2.*t3+R2.*t2.*t5,-P2_1-P1_2.*t5-P1_3.*t5-P2_2.*t3+P2_3.*t3+R2.*t3-R1.*t5,P1_4+P3_1+P3_4+P3_3.*t2+t2.*t6+t2.*t8-P1_2.*t3.*t4-P1_3.*t3.*t4+P2_2.*t4.*t5-P2_3.*t4.*t5-R1.*t3.*t4-R2.*t4.*t5,R4,R5];
