function speed_w = kin_forward_jacobian_xyzbc(in1,in2,in3)
%KIN_FORWARD_JACOBIAN_XYZBC
%    SPEED_W = KIN_FORWARD_JACOBIAN_XYZBC(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    16-Jun-2022 10:26:18

A1 = in1(1,:);
A2 = in1(2,:);
A3 = in1(3,:);
A5 = in1(5,:);
A6 = in1(6,:);
Ap1 = in2(1,:);
Ap2 = in2(2,:);
Ap3 = in2(3,:);
Ap5 = in2(5,:);
Ap6 = in2(6,:);
P1_1 = in3(1);
P1_4 = in3(10);
P2_1 = in3(2);
P3_1 = in3(3);
P3_4 = in3(12);
t2 = cos(A5);
t3 = cos(A6);
t4 = sin(A5);
t5 = sin(A6);
t6 = A3.*t2;
t7 = P1_4.*t2;
t8 = P3_1.*t2;
t9 = P3_4.*t2;
t10 = A1.*t4;
t11 = P1_1.*t4;
t12 = -t6;
t13 = -t10;
t14 = t7+t8+t9+t11+t12+t13;
speed_w = [-Ap2.*t5-Ap6.*(A2.*t3+P2_1.*t3+A1.*t2.*t5-A3.*t4.*t5-P1_1.*t2.*t5+P1_4.*t4.*t5+P3_1.*t4.*t5+P3_4.*t4.*t5)+Ap1.*t2.*t3-Ap3.*t3.*t4+Ap5.*t3.*t14;Ap2.*t3-Ap6.*(A2.*t5+P2_1.*t5-A1.*t2.*t3+A3.*t3.*t4+P1_1.*t2.*t3-P1_4.*t3.*t4-P3_1.*t3.*t4-P3_4.*t3.*t4)+Ap1.*t2.*t5-Ap3.*t4.*t5+Ap5.*t5.*t14;Ap1.*t4+Ap3.*t2+Ap5.*(A1.*t2-A3.*t4-P1_1.*t2+P1_4.*t4+P3_1.*t4+P3_4.*t4)];
