function speed_w = kin_forward_jacobian_xyzbc(in1,in2,in3)
%KIN_FORWARD_JACOBIAN_XYZBC
%    SPEED_W = KIN_FORWARD_JACOBIAN_XYZBC(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    09-Jun-2022 16:57:50

speed_w = [0.0;0.0;0.0];
