function acc_w = kin_forward_jacobian_1pd_xyzbc(in1,in2,in3,in4)
%KIN_FORWARD_JACOBIAN_1PD_XYZBC
%    ACC_W = KIN_FORWARD_JACOBIAN_1PD_XYZBC(IN1,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    09-Jun-2022 16:57:52

acc_w = [0.0;0.0;0.0];
