function J2P_ar = kin_J2P_ar_xyzbc(in1,in2,in3,in4)
%kin_J2P_ar_xyzbc
%    J2P_ar = kin_J2P_ar_xyzbc(IN1,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 9.1.
%    29-Aug-2023 15:26:12

%Jacobian second derivative ( backward ) : 
%INPUTS : 
%	r_r : 5 x 1 : pose vector ( relative )
%	v_r : 5 x 1 : speed vector ( relative )
%	a_a : 5 x 1 : acceleration vector( relative )
%	j_r : 5 x 1 : jerk vector( relative )
%	p   : 5 x 1 : parameters
%OUTPUTS : 
%	M   : 5 x 5 : resulting matrix
%#codegen
P1_2 = in4(4);
P1_3 = in4(7);
P2_2 = in4(5);
P2_3 = in4(8);
P2_4 = in4(11);
P3_2 = in4(6);
P3_3 = in4(9);
P3_4 = in4(12);
R1 = in1(1,:);
R2 = in1(2,:);
R3 = in1(3,:);
R4 = in1(4,:);
R5 = in1(5,:);
Rp1 = in2(1,:);
Rp2 = in2(2,:);
Rp3 = in2(3,:);
Rp4 = in2(4,:);
Rp5 = in2(5,:);
Rpp1 = in3(1,:);
Rpp2 = in3(2,:);
Rpp3 = in3(3,:);
Rpp4 = in3(4,:);
Rpp5 = in3(5,:);
t2 = cos(R4);
t3 = cos(R5);
t4 = sin(R4);
t5 = sin(R5);
t6 = Rp4.^2;
t7 = Rp5.^2;
et1 = Rpp3.*t2-P2_4.*Rpp4.*t4-P3_2.*Rpp4.*t4-P3_3.*Rpp4.*t4+P3_4.*Rpp4.*t4-R3.*Rpp4.*t4-Rp3.*Rp4.*t4.*2.0-P2_4.*t2.*t6-P3_2.*t2.*t6-P3_3.*t2.*t6+P3_4.*t2.*t6-R3.*t2.*t6-Rpp1.*t3.*t4-Rpp2.*t4.*t5+P1_2.*t3.*t4.*t6+P1_2.*t3.*t4.*t7+P1_3.*t3.*t4.*t6+P1_3.*t3.*t4.*t7-P2_2.*t4.*t5.*t6-P2_2.*t4.*t5.*t7+P2_3.*t4.*t5.*t6+P2_3.*t4.*t5.*t7+R1.*t3.*t4.*t6+R1.*t3.*t4.*t7+R2.*t4.*t5.*t6+R2.*t4.*t5.*t7-P1_2.*Rpp4.*t2.*t3-P1_3.*Rpp4.*t2.*t3+P1_2.*Rpp5.*t4.*t5+P1_3.*Rpp5.*t4.*t5+P2_2.*Rpp4.*t2.*t5+P2_2.*Rpp5.*t3.*t4-P2_3.*Rpp4.*t2.*t5-P2_3.*Rpp5.*t3.*t4-R1.*Rpp4.*t2.*t3;
et2 = -R2.*Rpp4.*t2.*t5-R2.*Rpp5.*t3.*t4+R1.*Rpp5.*t4.*t5-Rp1.*Rp4.*t2.*t3.*2.0-Rp2.*Rp4.*t2.*t5.*2.0-Rp2.*Rp5.*t3.*t4.*2.0+Rp1.*Rp5.*t4.*t5.*2.0+P1_2.*Rp4.*Rp5.*t2.*t5.*2.0+P1_3.*Rp4.*Rp5.*t2.*t5.*2.0+P2_2.*Rp4.*Rp5.*t2.*t3.*2.0-P2_3.*Rp4.*Rp5.*t2.*t3.*2.0-R2.*Rp4.*Rp5.*t2.*t3.*2.0+R1.*Rp4.*Rp5.*t2.*t5.*2.0;
et3 = Rpp2.*t2.*t3-Rpp1.*t2.*t5+P1_2.*t2.*t5.*t6+P1_2.*t2.*t5.*t7+P1_3.*t2.*t5.*t6+P1_3.*t2.*t5.*t7+P2_2.*t2.*t3.*t6+P2_2.*t2.*t3.*t7-P2_3.*t2.*t3.*t6-P2_3.*t2.*t3.*t7-R2.*t2.*t3.*t6+R1.*t2.*t5.*t6-R2.*t2.*t3.*t7+R1.*t2.*t5.*t7-P1_2.*Rpp5.*t2.*t3-P1_3.*Rpp5.*t2.*t3+P1_2.*Rpp4.*t4.*t5+P1_3.*Rpp4.*t4.*t5+P2_2.*Rpp4.*t3.*t4+P2_2.*Rpp5.*t2.*t5-P2_3.*Rpp4.*t3.*t4-P2_3.*Rpp5.*t2.*t5-R1.*Rpp5.*t2.*t3-R2.*Rpp4.*t3.*t4+R1.*Rpp4.*t4.*t5-R2.*Rpp5.*t2.*t5-Rp1.*Rp5.*t2.*t3.*2.0-Rp2.*Rp4.*t3.*t4.*2.0+Rp1.*Rp4.*t4.*t5.*2.0-Rp2.*Rp5.*t2.*t5.*2.0+P1_2.*Rp4.*Rp5.*t3.*t4.*2.0+P1_3.*Rp4.*Rp5.*t3.*t4.*2.0;
et4 = P2_2.*Rp4.*Rp5.*t4.*t5.*-2.0+P2_3.*Rp4.*Rp5.*t4.*t5.*2.0+R1.*Rp4.*Rp5.*t3.*t4.*2.0+R2.*Rp4.*Rp5.*t4.*t5.*2.0;
et5 = -Rpp3.*t4-P2_4.*Rpp4.*t2-P3_2.*Rpp4.*t2-P3_3.*Rpp4.*t2+P3_4.*Rpp4.*t2-R3.*Rpp4.*t2-Rp3.*Rp4.*t2.*2.0+P2_4.*t4.*t6+P3_2.*t4.*t6+P3_3.*t4.*t6-P3_4.*t4.*t6+R3.*t4.*t6-Rpp1.*t2.*t3-Rpp2.*t2.*t5+P1_2.*t2.*t3.*t6+P1_2.*t2.*t3.*t7+P1_3.*t2.*t3.*t6+P1_3.*t2.*t3.*t7-P2_2.*t2.*t5.*t6-P2_2.*t2.*t5.*t7+P2_3.*t2.*t5.*t6+P2_3.*t2.*t5.*t7+R1.*t2.*t3.*t6+R1.*t2.*t3.*t7+R2.*t2.*t5.*t6+R2.*t2.*t5.*t7+P1_2.*Rpp4.*t3.*t4+P1_2.*Rpp5.*t2.*t5+P1_3.*Rpp4.*t3.*t4+P1_3.*Rpp5.*t2.*t5+P2_2.*Rpp5.*t2.*t3-P2_3.*Rpp5.*t2.*t3-P2_2.*Rpp4.*t4.*t5+P2_3.*Rpp4.*t4.*t5+R1.*Rpp4.*t3.*t4-R2.*Rpp5.*t2.*t3+R1.*Rpp5.*t2.*t5;
et6 = R2.*Rpp4.*t4.*t5+Rp1.*Rp4.*t3.*t4.*2.0-Rp2.*Rp5.*t2.*t3.*2.0+Rp1.*Rp5.*t2.*t5.*2.0+Rp2.*Rp4.*t4.*t5.*2.0-P1_2.*Rp4.*Rp5.*t4.*t5.*2.0-P1_3.*Rp4.*Rp5.*t4.*t5.*2.0-P2_2.*Rp4.*Rp5.*t3.*t4.*2.0+P2_3.*Rp4.*Rp5.*t3.*t4.*2.0+R2.*Rp4.*Rp5.*t3.*t4.*2.0-R1.*Rp4.*Rp5.*t4.*t5.*2.0;
et7 = -Rpp2.*t3.*t4+Rpp1.*t4.*t5-P1_2.*t4.*t5.*t6-P1_2.*t4.*t5.*t7-P1_3.*t4.*t5.*t6-P1_3.*t4.*t5.*t7-P2_2.*t3.*t4.*t6-P2_2.*t3.*t4.*t7+P2_3.*t3.*t4.*t6+P2_3.*t3.*t4.*t7+R2.*t3.*t4.*t6-R1.*t4.*t5.*t6+R2.*t3.*t4.*t7-R1.*t4.*t5.*t7+P1_2.*Rpp4.*t2.*t5+P1_2.*Rpp5.*t3.*t4+P1_3.*Rpp4.*t2.*t5+P1_3.*Rpp5.*t3.*t4+P2_2.*Rpp4.*t2.*t3-P2_3.*Rpp4.*t2.*t3-P2_2.*Rpp5.*t4.*t5+P2_3.*Rpp5.*t4.*t5-R2.*Rpp4.*t2.*t3+R1.*Rpp4.*t2.*t5+R1.*Rpp5.*t3.*t4+R2.*Rpp5.*t4.*t5-Rp2.*Rp4.*t2.*t3.*2.0+Rp1.*Rp4.*t2.*t5.*2.0+Rp1.*Rp5.*t3.*t4.*2.0+Rp2.*Rp5.*t4.*t5.*2.0+P1_2.*Rp4.*Rp5.*t2.*t3.*2.0+P1_3.*Rp4.*Rp5.*t2.*t3.*2.0-P2_2.*Rp4.*Rp5.*t2.*t5.*2.0;
et8 = P2_3.*Rp4.*Rp5.*t2.*t5.*2.0+R1.*Rp4.*Rp5.*t2.*t3.*2.0+R2.*Rp4.*Rp5.*t2.*t5.*2.0;
mt1 = [-Rpp4.*t3.*t4-Rpp5.*t2.*t5-t2.*t3.*t6-t2.*t3.*t7+Rp4.*Rp5.*t4.*t5.*2.0,-Rpp5.*t3+t5.*t7,-Rpp4.*t2.*t3+Rpp5.*t4.*t5+t3.*t4.*t6+t3.*t4.*t7+Rp4.*Rp5.*t2.*t5.*2.0,0.0,0.0,Rpp5.*t2.*t3-Rpp4.*t4.*t5-t2.*t5.*t6-t2.*t5.*t7-Rp4.*Rp5.*t3.*t4.*2.0,-Rpp5.*t5-t3.*t7,-Rpp4.*t2.*t5-Rpp5.*t3.*t4+t4.*t5.*t6+t4.*t5.*t7-Rp4.*Rp5.*t2.*t3.*2.0,0.0,0.0,Rpp4.*t2-t4.*t6,0.0,-Rpp4.*t4-t2.*t6,0.0,0.0,et1+et2,0.0,et5+et6,0.0,0.0,et3+et4];
mt2 = [-Rpp1.*t3-Rpp2.*t5+P1_2.*Rpp5.*t5+P1_3.*Rpp5.*t5+P2_2.*Rpp5.*t3-P2_3.*Rpp5.*t3-R2.*Rpp5.*t3+R1.*Rpp5.*t5-Rp2.*Rp5.*t3.*2.0+Rp1.*Rp5.*t5.*2.0+P1_2.*t3.*t7+P1_3.*t3.*t7-P2_2.*t5.*t7+P2_3.*t5.*t7+R1.*t3.*t7+R2.*t5.*t7,et7+et8,0.0,0.0];
J2P_ar = reshape([mt1,mt2],5,5);
