function speed_j = kin_inverse_jacobian_xyzbc(in1,in2,in3)
%KIN_INVERSE_JACOBIAN_XYZBC
%    SPEED_J = KIN_INVERSE_JACOBIAN_XYZBC(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    09-Jun-2022 16:57:51

speed_j = [0.0;0.0;0.0];
