function J_tj = kin_xyzbc_tt_J_tj(in1,in2)
%kin_xyzbc_tt_J_tj
%    J_tj = kin_xyzbc_tt_J_tj(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.1.
%    07-Nov-2023 14:54:34

%Jacobian Kinematics ( Forward Kinematics ) : 
%INPUTS : 
%	r_j    (5x1) : pose vector( joint space )
%	v_j    (5x1) : speed vector( joint space )
%	p      (3x5) : parameters
%OUTPUTS : 
%	M      (5x5) : resulting matrix
%#codegen
b = in1(4,:);
c = in1(5,:);
offB1 = in2(10);
offB2 = in2(11);
offC1 = in2(13);
offB3 = in2(12);
offC2 = in2(14);
offC3 = in2(15);
offM1 = in2(1);
offM2 = in2(2);
offM3 = in2(3);
offT1 = in2(4);
offT2 = in2(5);
offT3 = in2(6);
x = in1(1,:);
y = in1(2,:);
z = in1(3,:);
t2 = cos(b);
t3 = cos(c);
t4 = sin(b);
t5 = sin(c);
t6 = -offM1;
t7 = -offM2;
t8 = -offM3;
t9 = offB1+offC1+offT1+t6+x;
t10 = offB2+offC2+offT2+t7+y;
t11 = offB3+offC3+offT3+t8+z;
J_tj = reshape([t2.*t3,-t2.*t5,t4,0.0,0.0,t5,t3,0.0,0.0,0.0,-t3.*t4,t4.*t5,t2,0.0,0.0,-t2.*t3.*t11-t3.*t4.*t9,t2.*t5.*t11+t4.*t5.*t9,t2.*t9-t4.*t11,1.0,0.0,-offB2.*t3+offB1.*t5+t3.*t10-t2.*t5.*t9+t4.*t5.*t11,offB1.*t3+offB2.*t5-t5.*t10-t2.*t3.*t9+t3.*t4.*t11,0.0,0.0,1.0],[5,5]);
