function JP_ra = kin_JP_ra_xyzbc(in1,in2,in3)
%kin_JP_ra_xyzbc
%    JP_ra = kin_JP_ra_xyzbc(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 9.1.
%    29-Aug-2023 15:26:11

%Jacobian first derivative ( forward ) : 
%INPUTS : 
%	r_a : 5 x 1 : pose vector( joint )
%	v_a : 5 x 1 : speed vector( joint )
%	a_a : 5 x 1 : acceleration vector( joint )
%	p   : 5 x 1 : parameters
%OUTPUTS : 
%	M   : 5 x 5 : resulting matrix
%#codegen
A1 = in1(1,:);
A2 = in1(2,:);
A3 = in1(3,:);
A4 = in1(4,:);
A5 = in1(5,:);
Ap1 = in2(1,:);
Ap2 = in2(2,:);
Ap3 = in2(3,:);
Ap4 = in2(4,:);
Ap5 = in2(5,:);
P1_1 = in3(1);
P1_4 = in3(10);
P2_1 = in3(2);
P3_1 = in3(3);
P3_4 = in3(12);
t2 = cos(A4);
t3 = cos(A5);
t4 = sin(A4);
t5 = sin(A5);
t6 = A1.*t2;
t7 = A3.*t2;
t8 = P1_1.*t2;
t9 = P1_4.*t2;
t10 = P3_1.*t2;
t11 = P3_4.*t2;
t12 = A1.*t4;
t13 = A3.*t4;
t14 = P1_1.*t4;
t15 = P1_4.*t4;
t16 = P3_1.*t4;
t17 = P3_4.*t4;
t18 = -t7;
t19 = -t8;
t20 = -t12;
t21 = -t13;
t22 = t9+t10+t11+t14+t18+t20;
t23 = t6+t15+t16+t17+t19+t21;
mt1 = [-Ap4.*t3.*t4-Ap5.*t2.*t5,Ap5.*t2.*t3-Ap4.*t4.*t5,Ap4.*t2,0.0,0.0,-Ap5.*t3,-Ap5.*t5,0.0,0.0,0.0,-Ap4.*t2.*t3+Ap5.*t4.*t5,-Ap4.*t2.*t5-Ap5.*t3.*t4,-Ap4.*t4,0.0,0.0,-Ap1.*t3.*t4-Ap3.*t2.*t3-Ap4.*t3.*t23-Ap5.*t5.*t22,-Ap1.*t4.*t5-Ap3.*t2.*t5+Ap5.*t3.*t22-Ap4.*t5.*t23,Ap1.*t2-Ap3.*t4+Ap4.*t9+Ap4.*t10+Ap4.*t11+Ap4.*t14+Ap4.*t18+Ap4.*t20,0.0,0.0];
mt2 = [-Ap2.*t3+Ap5.*(A2.*t5+P2_1.*t5-t3.*t6+t3.*t8+t3.*t13-t3.*t15-t3.*t16-t3.*t17)-Ap1.*t2.*t5+Ap3.*t4.*t5-Ap4.*t5.*t22,-Ap2.*t5-Ap5.*(A2.*t3+P2_1.*t3+t5.*t6+t5.*t15+t5.*t16+t5.*t17+t5.*t19+t5.*t21)+Ap1.*t2.*t3-Ap3.*t3.*t4+Ap4.*t3.*t22,0.0,0.0,0.0];
JP_ra = reshape([mt1,mt2],5,5);
