function jerk_w = kin_forward_jacobian_2pd_xyzbc(in1,in2,in3,in4,in5)
%KIN_FORWARD_JACOBIAN_2PD_XYZBC
%    JERK_W = KIN_FORWARD_JACOBIAN_2PD_XYZBC(IN1,IN2,IN3,IN4,IN5)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    09-Jun-2022 16:57:53

jerk_w = [0.0;0.0;0.0];
