function J_jt = kin_xyzbc_tt_J_jt(in1,in2)
%kin_xyzbc_tt_J_jt
%    J_jt = kin_xyzbc_tt_J_jt(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.1.
%    07-Nov-2023 14:54:34

%Jacobian Kinematics ( Inverse Kinematics ) : 
%INPUTS : 
%	r_j    (5x1) : pose vector( joint space )
%	v_j    (5x1) : speed vector( joint space )
%	p      (3x5) : parameters
%OUTPUTS : 
%	M      (5x5) : resulting matrix
%#codegen
b = in1(4,:);
c = in1(5,:);
offB1 = in2(10);
offC1 = in2(13);
offB3 = in2(12);
offC2 = in2(14);
offC3 = in2(15);
offP1 = in2(7);
offP2 = in2(8);
offP3 = in2(9);
x = in1(1,:);
y = in1(2,:);
z = in1(3,:);
t2 = cos(b);
t3 = cos(c);
t4 = sin(b);
t5 = sin(c);
t6 = offP1+x;
t7 = offP2+y;
t8 = offP3+z;
J_jt = reshape([t2.*t3,t5,-t3.*t4,0.0,0.0,-t2.*t5,t3,t4.*t5,0.0,0.0,t4,0.0,t2,0.0,0.0,-offB1.*t4+offB3.*t2+offC3.*t2+t2.*t8-offC1.*t3.*t4+offC2.*t4.*t5-t3.*t4.*t6+t4.*t5.*t7,0.0,-offB1.*t2-offB3.*t4-offC3.*t4-t4.*t8-offC1.*t2.*t3+offC2.*t2.*t5-t2.*t3.*t6+t2.*t5.*t7,1.0,0.0,-offC2.*t2.*t3-offC1.*t2.*t5-t2.*t3.*t7-t2.*t5.*t6,offC1.*t3-offC2.*t5+t3.*t6-t5.*t7,offC2.*t3.*t4+offC1.*t4.*t5+t3.*t4.*t7+t4.*t5.*t6,0.0,1.0],[5,5]);
