function r_r = MGD(x,y,z,b,c,mx,my,mz,tx,ty,tz,px,p_y,pz,d1,d2,t_l)
%MGD
%    R_R = MGD(X,Y,Z,B,C,MX,MY,MZ,TX,TY,TZ,PX,P_Y,PZ,D1,D2,T_L)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    05-May-2022 10:11:57

t2 = cos(b);
t3 = cos(c);
t4 = sin(b);
t5 = sin(c);
r_r = [-px-my.*t5-t5.*y+d1.*t3.*t4-mx.*t2.*t3+mz.*t3.*t4+t3.*t4.*t_l+t2.*t3.*x-t3.*t4.*z,p_y+my.*t3+t3.*y+d1.*t4.*t5-mx.*t2.*t5+mz.*t4.*t5+t4.*t5.*t_l+t2.*t5.*x-t4.*t5.*z,d1-pz-d1.*t2-mx.*t4-mz.*t2-t2.*t_l+t4.*x+t2.*z,b,c];
