function MGD = MGD(in1,in2)
%MGD
%    MGD = MGD(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    06-May-2022 12:24:03

P1_1 = in2(1);
P1_3 = in2(7);
P1_4 = in2(10);
P2_1 = in2(2);
P2_3 = in2(8);
P3_1 = in2(3);
P3_3 = in2(9);
P3_4 = in2(12);
R1 = in1(1,:);
R3 = in1(3,:);
R5 = in1(5,:);
R6 = in1(6,:);
t2 = cos(R5);
t3 = cos(R6);
t4 = sin(R5);
t5 = sin(R6);
MGD = [-P1_3-P2_1.*t5-R1.*t5-P1_1.*t2.*t3+P1_4.*t3.*t4+P3_1.*t3.*t4+P3_4.*t3.*t4+R1.*t2.*t3-R3.*t3.*t4,P2_3+P2_1.*t3+R1.*t3-P1_1.*t2.*t5+P1_4.*t4.*t5+P3_1.*t4.*t5+P3_4.*t4.*t5+R1.*t2.*t5-R3.*t4.*t5,P1_4-P3_3-P1_1.*t4-P1_4.*t2-P3_1.*t2-P3_4.*t2+R1.*t4+R3.*t2,R5,R6];
