function r_a = MGI(x,y,z,b,c,mx,my,mz,tx,ty,tz,px,p_y,pz,d1,d2,t_l)
%MGI
%    R_A = MGI(X,Y,Z,B,C,MX,MY,MZ,TX,TY,TZ,PX,P_Y,PZ,D1,D2,T_L)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    04-May-2022 15:58:16

t2 = cos(b);
t3 = cos(c);
t4 = sin(b);
t5 = sin(c);
t6 = d2+z;
r_a = [mx+pz.*t4+t4.*t6-t4.*t_l+t4.*tz+p_y.*t2.*t5+px.*t2.*t3+t2.*t3.*tx-t2.*t5.*ty+t2.*t3.*x+t2.*t5.*y,-my+p_y.*t3-px.*t5-t5.*tx-t3.*ty-t5.*x+t3.*y,d1+mz+t_l+pz.*t2+t2.*t6-t2.*t_l+t2.*tz-p_y.*t4.*t5-px.*t3.*t4-t3.*t4.*tx+t4.*t5.*ty-t3.*t4.*x-t4.*t5.*y,b,c];
