function [ cfg ] = FeedoptDefaultConfig()

coder.inline("never");

tol_col_compress_deg    = 30;
tol_col_smooth_deg      = 10;

% Computation of Gauss-Legendre knots and weights for numerical integration
GaussLegendreN = 5;  % number of evaluation points
[GaussLegendreX, GaussLegendreW] = lgwt(GaussLegendreN, -1, 1); % normalized to integration interval [-1, 1]
GaussLegendreX = flipud(GaussLegendreX);

LP = struct(...
    'Type', 'LP', ...
    'EnableFindReasonInfeasibility', true,...
    'ACC_RAMP_OVER_WINDOWS', 1.0 - 1E-3,...
    'VEL_RAMP_OVER_WINDOWS', 1.0 - 1E-3,...
    'SLACK_PENALTY', 10000, ...
    'USE_LINPROG', false);

if( ~coder.target('MATLAB') )
    coder.cstructname( LP,          StructTypeName.LPCfg );
end

machine_off = [0; 0; 0]; % mx, my, mz
piece_off   = [0; 0; -24.8760]; % px, py, pz
tool_off    = [0; 0; 0]; % tx, ty, tz
other_off   = [24.8760; 0; 0]; % d1, d2, tool_length


kin_params = [machine_off, piece_off, tool_off, other_off];

cfg = struct(...
    'maskTot',  logical( [ 1, 1, 1, 0, 1, 1 ] ),... % [X,Y,Z,A,B,C]
    'maskCart', logical( 0 ),...                    % Do not modify
    'maskRot',  logical( 0 ),...                    % Do not modify
    'indCart', int32( 0 ), ...                      % Do not modify
    'indRot',  int32( 0 ),...                       % Do not modify
    'NumberAxis', int32( 0 ), ...                   % Do not modify
    'NCart',   int32( 0 ), ...                      % Do not modify
    'NRot',    int32( 0 ), ...                      % Do not modify
    'D', 0, ...                                     % Do not modify
    'coeffD', 1, ...                                % Coefficient between cartésian and rotativ axis
    'kin_params', reshape( kin_params, [], 1 ), ...
    'kin_type', 'xyzbc', ...
    'NDiscr', int32( 10 ),...
    'NBreak', int32( 5 ),...
    'UseDynamicBreakpoints',false,...       % Use a variable number of breakpoints for different lengths
    'UseLinearBreakpoints',false,...        % Use a linear distribution of breakpoints (else sinspace)
    'DynamicBreakpointsDistance', 0.1,...   % Distance between two breakpoints in mm
    'NHorz', int32( 10 ),...
    'fmax', 1000,...
    'smax', 75000,...
    'vmax', [500,500,800,0, 40,50],... %[mm] [rad]
    'amax', [15000,15000,15000,0, 200,1000],...
    'jmax', [750000,750000,3000000,0,10000,50000],...
    'LeeSplineDegree', int32( 4 ),...
    'SplineDegree',    int32( 3 ),...
    'CutOff', 1E-3,...
    'LSplit',  0.5,...
    'LSplitZero', 1E-3,...
    'LThresholdMax', 5.0,...
    'LThresholdMin', 1E-3,...
    'v_0', 0, 'at_0', 0,...
    'v_1', 0, 'at_1', 0,...
    'dt', 1e-2, ...
    'ZeroStartAccLimit', 0.01, ...
    'ZeroStartJerkLimit', 1E6, ...
    'ZeroStartVelLimit', 0.5, ...
    'source', repmat(char(0), [1, 1024]),...
    'DebugCutZero', false,...
    'Cusp', struct(...
    'Skip', false,...
    'CuspThreshold', 70 ),...
    'Compressing', struct(...
    'Skip', false,...
    'ColTolCosLee',     cosd(tol_col_compress_deg)),...
    'Smoothing', struct( ...
    'Skip', false,...
    'ColTolCosSmooth',  cosd(tol_col_smooth_deg), ...
    'ColTolSmooth',     1E-5 ),...
    'GaussLegendreN', GaussLegendreN, ...
    'GaussLegendreX', GaussLegendreX, ...
    'GaussLegendreW', GaussLegendreW, ...
    'opt', LP,...
    'LogFileName', 'logs/logs');

coder.varsize( 'cfg.indCart',   StructTypeName.dimInd{ : } );
coder.varsize( 'cfg.indRot',    StructTypeName.dimInd{ : } );
coder.varsize( 'cfg.maskTot',   StructTypeName.dimMask{ : } );
coder.varsize( 'cfg.maskCart',  StructTypeName.dimMask{ : } );
coder.varsize( 'cfg.maskRot',   StructTypeName.dimMask{ : } );
coder.varsize( 'cfg.D',         StructTypeName.dimD{ : } );
coder.varsize( 'cfg.kin_params',StructTypeName.dimKinParams{ : } );
coder.cstructname( cfg,         StructTypeName.FeedoptCfg );

[ cfg ] = setMachineAxisInConfig( cfg, cfg.maskTot );

end

