; config.ini

[Extreme values]
amax_min=1.0e4                  ; [mm/s²]
amax_max=3.0e4                  ; [mm/s²]
jmax_min=1.0e6                  ; [mm/s³]
jmax_max=2.0e6              	; [mm/s³]
CutOff_min=0.5                  ; [mm]
CutOff_max=0.15                 ; [mm]

[Max constrains tolerances]     ; [%]
vmax_norm_tol=5
amax_xyz_tol=5
jmax_xyz_tol=5

[Time optimality tolerance]     ; [%]
TimeOpt_tol=95
