amax = [1e4 1e4 1e4;...
        3e4 3e4 3e4];       % [mm/s²]
    
jmax = [1e6 1e6 1e6;...
        2e6 2e6 2e6];       % [mm/s³]
    
CutOff = [0.5 0.15];        % [mm]

      

vmax_norm_tol = 0.05;
amax_xyz_tol  = 0.05;
jmax_xyz_tol  = 0.20;

TOpt_tol      = 0.20;       % bang-bang

ProfiledFcts = {'FeedoptPlanRun';...
                'ReadGCode';...
                'CheckCurvStructs';...
                'CompressCurvStructs';...
                'SmoothCurvStructs';...
                'SplitCurvStructs';...
                'FeedratePlanning_v4';...
                'ResampleNoCtx'};
