function J_arPP = Fct_J_arPP(x,y,z,b,c,xP,yP,zP,bP,cP,xPP,yPP,zPP,bPP,cPP,mx,my,mz,tx,ty,tz,px,p_y,pz,d1,d2,t_l)
%Fct_J_arPP
%    J_arPP = Fct_J_arPP(X,Y,Z,B,C,xP,yP,zP,bP,cP,xPP,yPP,zPP,bPP,cPP,MX,MY,MZ,TX,TY,TZ,PX,P_Y,PZ,D1,D2,T_L)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    02-May-2022 14:59:55

t2 = conj(b);
t3 = conj(c);
t4 = conj(d2);
t5 = conj(p_y);
t6 = conj(px);
t7 = conj(pz);
t8 = conj(t_l);
t9 = conj(tx);
t10 = conj(ty);
t11 = conj(tz);
t12 = conj(x);
t13 = conj(y);
t14 = conj(z);
t19 = bP.^2;
t20 = cP.^2;
t15 = cos(t2);
t16 = cos(t3);
t17 = sin(t2);
t18 = sin(t3);
et1 = t15.*zPP-bPP.*t4.*t17-bPP.*t7.*t17+bPP.*t8.*t17-bPP.*t11.*t17-bPP.*t14.*t17-bP.*t17.*zP.*2.0-t4.*t15.*t19-t7.*t15.*t19+t8.*t15.*t19-t11.*t15.*t19-t14.*t15.*t19-t16.*t17.*xPP-t17.*t18.*yPP-bPP.*t6.*t15.*t16-bPP.*t5.*t15.*t18-bPP.*t9.*t15.*t16+bPP.*t10.*t15.*t18-bPP.*t12.*t15.*t16-bPP.*t13.*t15.*t18-cPP.*t5.*t16.*t17+cPP.*t6.*t17.*t18+cPP.*t10.*t16.*t17+cPP.*t9.*t17.*t18-cPP.*t13.*t16.*t17+cPP.*t12.*t17.*t18-bP.*t15.*t16.*xP.*2.0-bP.*t15.*t18.*yP.*2.0+cP.*t17.*t18.*xP.*2.0-cP.*t16.*t17.*yP.*2.0+t6.*t16.*t17.*t19+t5.*t17.*t18.*t19+t6.*t16.*t17.*t20+t5.*t17.*t18.*t20;
et2 = t9.*t16.*t17.*t19+t9.*t16.*t17.*t20-t10.*t17.*t18.*t19+t12.*t16.*t17.*t19-t10.*t17.*t18.*t20+t12.*t16.*t17.*t20+t13.*t17.*t18.*t19+t13.*t17.*t18.*t20-bP.*cP.*t5.*t15.*t16.*2.0+bP.*cP.*t6.*t15.*t18.*2.0+bP.*cP.*t10.*t15.*t16.*2.0+bP.*cP.*t9.*t15.*t18.*2.0-bP.*cP.*t13.*t15.*t16.*2.0+bP.*cP.*t12.*t15.*t18.*2.0;
et3 = -t15.*t18.*xPP+t15.*t16.*yPP-bPP.*t5.*t16.*t17+bPP.*t6.*t17.*t18+bPP.*t10.*t16.*t17+bPP.*t9.*t17.*t18-bPP.*t13.*t16.*t17+bPP.*t12.*t17.*t18-cPP.*t6.*t15.*t16-cPP.*t5.*t15.*t18-cPP.*t9.*t15.*t16+cPP.*t10.*t15.*t18-cPP.*t12.*t15.*t16-cPP.*t13.*t15.*t18+bP.*t17.*t18.*xP.*2.0-cP.*t15.*t16.*xP.*2.0-bP.*t16.*t17.*yP.*2.0-cP.*t15.*t18.*yP.*2.0-t5.*t15.*t16.*t19-t5.*t15.*t16.*t20+t6.*t15.*t18.*t19+t6.*t15.*t18.*t20+t10.*t15.*t16.*t19+t9.*t15.*t18.*t19+t10.*t15.*t16.*t20+t9.*t15.*t18.*t20-t13.*t15.*t16.*t19+t12.*t15.*t18.*t19-t13.*t15.*t16.*t20+t12.*t15.*t18.*t20+bP.*cP.*t6.*t16.*t17.*2.0+bP.*cP.*t5.*t17.*t18.*2.0+bP.*cP.*t9.*t16.*t17.*2.0;
et4 = bP.*cP.*t10.*t17.*t18.*-2.0+bP.*cP.*t12.*t16.*t17.*2.0+bP.*cP.*t13.*t17.*t18.*2.0;
et5 = -t17.*zPP-bPP.*t4.*t15-bPP.*t7.*t15+bPP.*t8.*t15-bPP.*t11.*t15-bPP.*t14.*t15-bP.*t15.*zP.*2.0+t4.*t17.*t19+t7.*t17.*t19-t8.*t17.*t19+t11.*t17.*t19+t14.*t17.*t19-t15.*t16.*xPP-t15.*t18.*yPP+bPP.*t6.*t16.*t17+bPP.*t5.*t17.*t18+bPP.*t9.*t16.*t17-bPP.*t10.*t17.*t18+bPP.*t12.*t16.*t17+bPP.*t13.*t17.*t18-cPP.*t5.*t15.*t16+cPP.*t6.*t15.*t18+cPP.*t10.*t15.*t16+cPP.*t9.*t15.*t18-cPP.*t13.*t15.*t16+cPP.*t12.*t15.*t18+bP.*t16.*t17.*xP.*2.0+cP.*t15.*t18.*xP.*2.0+bP.*t17.*t18.*yP.*2.0-cP.*t15.*t16.*yP.*2.0+t6.*t15.*t16.*t19+t5.*t15.*t18.*t19+t6.*t15.*t16.*t20+t5.*t15.*t18.*t20+t9.*t15.*t16.*t19+t9.*t15.*t16.*t20;
et6 = -t10.*t15.*t18.*t19+t12.*t15.*t16.*t19-t10.*t15.*t18.*t20+t12.*t15.*t16.*t20+t13.*t15.*t18.*t19+t13.*t15.*t18.*t20+bP.*cP.*t5.*t16.*t17.*2.0-bP.*cP.*t6.*t17.*t18.*2.0-bP.*cP.*t10.*t16.*t17.*2.0-bP.*cP.*t9.*t17.*t18.*2.0+bP.*cP.*t13.*t16.*t17.*2.0-bP.*cP.*t12.*t17.*t18.*2.0;
et7 = t17.*t18.*xPP-t16.*t17.*yPP-bPP.*t5.*t15.*t16+bPP.*t6.*t15.*t18+bPP.*t10.*t15.*t16+bPP.*t9.*t15.*t18-bPP.*t13.*t15.*t16+bPP.*t12.*t15.*t18+cPP.*t6.*t16.*t17+cPP.*t5.*t17.*t18+cPP.*t9.*t16.*t17-cPP.*t10.*t17.*t18+cPP.*t12.*t16.*t17+cPP.*t13.*t17.*t18+bP.*t15.*t18.*xP.*2.0-bP.*t15.*t16.*yP.*2.0+cP.*t16.*t17.*xP.*2.0+cP.*t17.*t18.*yP.*2.0+t5.*t16.*t17.*t19+t5.*t16.*t17.*t20-t6.*t17.*t18.*t19-t6.*t17.*t18.*t20-t10.*t16.*t17.*t19-t9.*t17.*t18.*t19-t10.*t16.*t17.*t20-t9.*t17.*t18.*t20+t13.*t16.*t17.*t19-t12.*t17.*t18.*t19+t13.*t16.*t17.*t20-t12.*t17.*t18.*t20+bP.*cP.*t6.*t15.*t16.*2.0+bP.*cP.*t5.*t15.*t18.*2.0+bP.*cP.*t9.*t15.*t16.*2.0;
et8 = bP.*cP.*t10.*t15.*t18.*-2.0+bP.*cP.*t12.*t15.*t16.*2.0+bP.*cP.*t13.*t15.*t18.*2.0;
mt1 = [-bPP.*t16.*t17-cPP.*t15.*t18-t15.*t16.*t19-t15.*t16.*t20+bP.*cP.*t17.*t18.*2.0,-cPP.*t16+t18.*t20,-bPP.*t15.*t16+cPP.*t17.*t18+t16.*t17.*t19+t16.*t17.*t20+bP.*cP.*t15.*t18.*2.0,-bPP.*t17.*t18+cPP.*t15.*t16-t15.*t18.*t19-t15.*t18.*t20-bP.*cP.*t16.*t17.*2.0,-cPP.*t18-t16.*t20,-bPP.*t15.*t18-cPP.*t16.*t17+t17.*t18.*t19+t17.*t18.*t20-bP.*cP.*t15.*t16.*2.0,bPP.*t15-t17.*t19,0.0,-bPP.*t17-t15.*t19,et1+et2,0.0,et5+et6,et3+et4];
mt2 = [-t16.*xPP-t18.*yPP-cPP.*t5.*t16+cPP.*t6.*t18+cPP.*t10.*t16+cPP.*t9.*t18-cPP.*t13.*t16+cPP.*t12.*t18+cP.*t18.*xP.*2.0-cP.*t16.*yP.*2.0+t6.*t16.*t20+t5.*t18.*t20+t9.*t16.*t20-t10.*t18.*t20+t12.*t16.*t20+t13.*t18.*t20,et7+et8];
J_arPP = reshape([mt1,mt2],3,5);
