function J_arP = Fct_J_arP(x,y,z,b,c,xP,yP,zP,bP,cP,mx,my,mz,tx,ty,tz,px,p_y,pz,d1,d2,t_l)
%Fct_J_arP
%    J_arP = Fct_J_arP(X,Y,Z,B,C,xP,yP,zP,bP,cP,MX,MY,MZ,TX,TY,TZ,PX,P_Y,PZ,D1,D2,T_L)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    02-May-2022 14:59:52

t2 = conj(b);
t3 = conj(c);
t4 = conj(d2);
t5 = conj(p_y);
t6 = conj(px);
t7 = conj(pz);
t8 = conj(t_l);
t9 = conj(tx);
t10 = conj(ty);
t11 = conj(tz);
t12 = conj(x);
t13 = conj(y);
t14 = conj(z);
t15 = cos(t2);
t16 = cos(t3);
t17 = sin(t2);
t18 = sin(t3);
t19 = t5.*t16;
t20 = t6.*t16;
t21 = t9.*t16;
t22 = t10.*t16;
t23 = t12.*t16;
t24 = t13.*t16;
t25 = t5.*t18;
t26 = t6.*t18;
t27 = t9.*t18;
t28 = t10.*t18;
t29 = t12.*t18;
t30 = t13.*t18;
t31 = -t19;
t32 = -t24;
t33 = -t28;
t34 = t20+t21+t23+t25+t30+t33;
t35 = t22+t26+t27+t29+t31+t32;
mt1 = [-bP.*t16.*t17-cP.*t15.*t18,-cP.*t16,-bP.*t15.*t16+cP.*t17.*t18,-bP.*t17.*t18+cP.*t15.*t16,-cP.*t18,-bP.*t15.*t18-cP.*t16.*t17,bP.*t15,0.0,-bP.*t17,t15.*zP-bP.*t4.*t17-bP.*t7.*t17+bP.*t8.*t17-bP.*t11.*t17-bP.*t14.*t17-bP.*t15.*t20-bP.*t15.*t21-bP.*t15.*t23-bP.*t15.*t25+bP.*t15.*t28-bP.*t15.*t30+cP.*t17.*t22+cP.*t17.*t26+cP.*t17.*t27+cP.*t17.*t29+cP.*t17.*t31+cP.*t17.*t32-t16.*t17.*xP-t17.*t18.*yP,0.0];
mt2 = [-t17.*zP-bP.*t4.*t15-bP.*t7.*t15+bP.*t8.*t15-bP.*t11.*t15-bP.*t14.*t15+bP.*t17.*t20+bP.*t17.*t21+bP.*t17.*t23+bP.*t17.*t25+bP.*t17.*t30+bP.*t17.*t33+cP.*t15.*t22+cP.*t15.*t26+cP.*t15.*t27+cP.*t15.*t29+cP.*t15.*t31+cP.*t15.*t32-t15.*t16.*xP-t15.*t18.*yP,bP.*t17.*t35-cP.*t15.*t34-t15.*t18.*xP+t15.*t16.*yP,cP.*t22+cP.*t26+cP.*t27+cP.*t29+cP.*t31+cP.*t32-t16.*xP-t18.*yP,bP.*t15.*t35+cP.*t17.*t34+t17.*t18.*xP-t16.*t17.*yP];
J_arP = reshape([mt1,mt2],3,5);
