function r_a = Fct_MGI(x,y,z,b,c,mx,my,mz,tx,ty,tz,px,p_y,pz,d1,d2,t_l)
%Fct_MGI
%    R_A = Fct_MGI(X,Y,Z,B,C,MX,MY,MZ,TX,TY,TZ,PX,P_Y,PZ,D1,D2,T_L)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    02-May-2022 14:59:40

t2 = conj(b);
t3 = conj(c);
t4 = conj(d2);
t5 = conj(p_y);
t6 = conj(px);
t7 = conj(pz);
t8 = conj(t_l);
t9 = conj(tx);
t10 = conj(ty);
t11 = conj(tz);
t12 = conj(x);
t13 = conj(y);
t14 = conj(z);
t15 = cos(t2);
t16 = cos(t3);
t17 = sin(t2);
t18 = sin(t3);
t19 = t4+t14;
r_a = [conj(mx)+t7.*t17-t8.*t17+t11.*t17+t17.*t19+t6.*t15.*t16+t5.*t15.*t18+t9.*t15.*t16-t10.*t15.*t18+t12.*t15.*t16+t13.*t15.*t18,-conj(my)+t5.*t16-t6.*t18-t10.*t16-t9.*t18+t13.*t16-t12.*t18,t8+conj(d1)+conj(mz)+t7.*t15-t8.*t15+t11.*t15+t15.*t19-t6.*t16.*t17-t5.*t17.*t18-t9.*t16.*t17+t10.*t17.*t18-t12.*t16.*t17-t13.*t17.*t18,t2,t3];
