function J_ar = J_ar(x,y,z,b,c,mx,my,mz,tx,ty,tz,px,p_y,pz,d1,d2,t_l)
%J_ar
%    J_ar = J_ar(X,Y,Z,B,C,MX,MY,MZ,TX,TY,TZ,PX,P_Y,PZ,D1,D2,T_L)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    03-May-2022 10:13:57

t2 = conj(b);
t3 = conj(c);
t4 = conj(d2);
t5 = conj(p_y);
t6 = conj(px);
t7 = conj(pz);
t8 = conj(t_l);
t9 = conj(tx);
t10 = conj(ty);
t11 = conj(tz);
t12 = conj(x);
t13 = conj(y);
t14 = conj(z);
t15 = cos(t2);
t16 = cos(t3);
t17 = sin(t2);
t18 = sin(t3);
t19 = t4+t14;
t20 = t5.*t16;
t21 = t10.*t16;
t22 = t13.*t16;
t23 = t6.*t18;
t24 = t9.*t18;
t25 = t12.*t18;
t26 = -t20;
t27 = -t22;
t28 = t21+t23+t24+t25+t26+t27;
J_ar = reshape([t15.*t16,-t18,-t16.*t17,t15.*t18,t16,-t17.*t18,t17,0.0,t15,t7.*t15-t8.*t15+t11.*t15+t15.*t19-t6.*t16.*t17-t5.*t17.*t18-t9.*t16.*t17+t10.*t17.*t18-t12.*t16.*t17-t13.*t17.*t18,0.0,-t7.*t17+t8.*t17-t11.*t17-t17.*t19-t6.*t15.*t16-t5.*t15.*t18-t9.*t15.*t16+t10.*t15.*t18-t12.*t15.*t16-t13.*t15.*t18,-t15.*t28,-t6.*t16-t5.*t18-t9.*t16+t10.*t18-t12.*t16-t13.*t18,t17.*t28],[3,5]);
