function CStrct = ConstrCurvStruct(Type, ZSpdMode, P0, P1, Cprim, delta, evec, theta, pitch, CoeffP5, FeedRate)

% ctxType = coder.OutputType('InitFeedoptPlan');
 
CStrct = struct('Type', Type, ...
                'zspdmode', ZSpdMode, ...
                'P0', P0, ...
                'P1', P1, ...
				'CorrectedHelixCenter', Cprim, ...
                'delta', delta, ...
                'evec', evec, ...
                'theta', theta, ...
                'pitch', pitch, ...
                'CoeffP5', CoeffP5, ...
                'sp_index', int32(1), ...
                'FeedRate', FeedRate, ...
                'SpindleSpeed', 0, ...
                'MaxConstantFeedRate', 0,...
                'i_begin_sp', int32(0), ...
                'i_end_sp', int32(0), ...
                'gcode_source_line', int32(0),...
                'index_smooth', int32(0),...
                'UseConstJerk', false,...
                'ConstJerk', 0,...
                'ConstJerkMaxIterations', int32(0),...
                'Coeff', zeros(0, 1), ...
                'a_param', 1, ...
                'b_param', 0, ...
                'sp', struct('CoeffX', 0, ...
                    'CoeffY', 0, ...
                    'CoeffZ', 0, ...
                    'Bl', struct(...
                        'ncoeff', int32(0),...
                        'breakpoints', zeros(1, 0),...
                        'handle', uint64(0),...
                        'degree', int32(0)),...
                    'knots', 0));
         
if ~coder.target('matlab')
coder.cstructname(CStrct, 'CurvStruct');
coder.cstructname(CStrct.sp, 'SplineStruct');
coder.cstructname(CStrct.sp.Bl, 'SplineBase');

coder.varsize('CStrct.sp.Bl.breakpoints', [1, Inf], [0, 1]);

coder.varsize('CStrct.Coeff', [Inf, 1], [1, 0]);
coder.varsize('CStrct.sp.CoeffX', [1, Inf], [0, 1]);
coder.varsize('CStrct.sp.CoeffY', [1, Inf], [0, 1]);
coder.varsize('CStrct.sp.CoeffZ', [1, Inf], [0, 1]);
coder.varsize('CStrct.sp.knots',  [1, Inf], [0, 1]);
coder.varsize('CStrct.CoeffP5', [3, 6], [0, 0]);
end
