function Q = CreateQueue(DefaultValue, SoftMax, HardMax)
    Q = struct('Values', repmat(DefaultValue, 1, HardMax),...
        'HardMax', int32(HardMax),...
        'SoftMax', int32(SoftMax),...
        'Size', int32(0));
end
