function cfg = FeedoptDefaultConfig()

coder.inline("never");

tol_col_compress_deg = 1e-2;
tol_col_smooth_deg = 1e-2;

% Computation of Gauss-Legendre knots and weights for numerical integration
GaussLegendreN = 5;  % number of evaluation points
[GaussLegendreX, GaussLegendreW] = lgwt(GaussLegendreN, -1, 1); % normalized to integration interval [-1, 1]
GaussLegendreX = flipud(GaussLegendreX);

cfg = struct(...
		'NDiscr', int32(20),...
		'NBreak', int32(10),...
        'UseDynamicBreakpoints',false,... % Use a variable number of breakpoints for different lengths
        'UseLinearBreakpoints',false,...   % Use a linear distribution of breakpoints (else sinspace)
        'DynamicBreakpointsDistance', 0.1,... % Distance between two breakpoints in mm
		'NHorz', int32(5),...
		'vmax', 150,...
		'amax', [20000,20000,20000],...
		'jmax', [1500000,1500000,1500000],...
		'SplineDegree', int32(4),...
        'CutOff', 0.1,...
        'LSplit', 3.0,...
        'LThreshold', 0.3,...
        'CuspThreshold', 45,...
        'v_0', 0.1, 'at_0', 0,...
        'v_1', 0.1, 'at_1', 0,...
        'dt', 1e-4, ...
        'ZeroStartAccLimit', 0.01, ...
        'ZeroStartJerkLimit', 1, ...
        'ZeroStartVelLimit', 0.5, ...
        'source', repmat(char(0), [1, 1024]),...
        'DebugCutZero', false,...
        'Compressing', struct(...
            'Skip', false,...
            'ColTolCos', cosd(tol_col_compress_deg)),...
        'ColTolCos', cosd(tol_col_smooth_deg), ...
        'GaussLegendreN', GaussLegendreN, ...
        'GaussLegendreX', GaussLegendreX, ...
        'GaussLegendreW', GaussLegendreW, ...
        'LogFileName', 'logs', ...
        'Simplex_params', [1e-6; 1e-6; 1; 1e-6]); % 1: Dual; 2: Barrier; 3: Primal
%     coder.varsize('cfg.source', [1024, 1], [0,1]);;
%         'MaxNHorz', FeedoptLimits.MaxNHorz,...
%         'MaxNDiscr', FeedoptLimits.MaxNDiscr,...
%         'MaxNCoeff', FeedoptLimits.MaxNCoeff,...
% coder.varsize('cfg.source', [1, Inf], [0, 1]);
    
coder.cstructname(cfg, 'FeedoptConfig');
end
