function cfg = FeedoptDefaultConfig()
cfg = struct(...
		'NDiscr', int32(20),...
		'NBreak', int32(10),...
        'UseDynamicBreakpoints',false,... % Use a variable number of breakpoints for different lengths
        'UseLinearBreakpoints',false,...   % Use a linear distribution of breakpoints (else sinspace)
        'DynamicBreakpointsDistance', 0.1,... % Distance between two breakpoints in mm
		'NHorz', int32(5),...
		'vmax', 150,...
		'amax', [20000,20000,20000],...
		'jmax', [1500000,1500000,1500000],...
		'SplineDegree', int32(4),...
        'CutOff', 0.1,...
        'LSplit', 3.0,...
        'LThreshold', 0.3,...
        'CuspThreshold', 45,...
        'v_0', 0.1, 'at_0', 0,...
        'v_1', 0.1, 'at_1', 0,...
        'dt', 1e-4, ...
        'ZeroStartAccLimit', 0.01, ...
        'ZeroStartJerkLimit', 1, ...
        'ZeroStartVelLimit', 0.5, ...
        'source', repmat(char(0), [1, 1024]),...
        'DebugCutZero', false,...
        'SkipCompressing', false,...
        'CollTolDeg', 1e-6,...
        'NGridLengthSpline', 10,...
        'LogFileName', 'logs/logs');
%     coder.varsize('cfg.source', [1024, 1], [0,1]);;
%         'MaxNHorz', FeedoptLimits.MaxNHorz,...
%         'MaxNDiscr', FeedoptLimits.MaxNDiscr,...
%         'MaxNCoeff', FeedoptLimits.MaxNCoeff,...
% coder.varsize('cfg.source', [1, Inf], [0, 1]);
    
coder.cstructname(cfg, 'FeedoptConfig');
end
