function [ cfg ] = FeedoptDefaultConfig()

coder.inline("never");

tol_col_compress_deg    = 10;
tol_col_smooth_deg      = 10;

% Computation of Gauss-Legendre knots and weights for numerical integration
GaussLegendreN = 5;  % number of evaluation points
[GaussLegendreX, GaussLegendreW] = lgwt(GaussLegendreN, -1, 1); % normalized to integration interval [-1, 1]
GaussLegendreX = flipud(GaussLegendreX);

LP = struct(...
    'Type', 'LP', ...
    'EnableFindReasonInfeasibility', true,...
    'ACC_RAMP_OVER_WINDOWS', 1.0 - 1E-3,...
    'VEL_RAMP_OVER_WINDOWS', 1.0 - 1E-3,...
    'SLACK_PENALTY', 10000, ...
    'USE_LINPROG', false);

if( ~coder.target('MATLAB') )
    coder.cstructname( LP,          StructTypeName.LPCfg );
end

cfg = struct(...
    'maskTot',  logical( [ 1, 1, 1, 0, 1, 1 ] ),... % [X,Y,Z,A,B,C]
    'maskCart', logical( 0 ),...                    % Do not modify
    'maskRot',  logical( 0 ),...                    % Do not modify
    'indCart', int32( 0 ), ...                      % Do not modify
    'indRot',  int32( 0 ),...                       % Do not modify
    'NumberAxis', int32( 0 ), ...                   % Do not modify
    'NCart',   int32( 0 ), ...                      % Do not modify
    'NRot',    int32( 0 ), ...                      % Do not modify
    'kin_params', reshape( [ 0, 0, 0, 24.8760; 0, 0, 0, 0; 0, -24.8760, 0, 0 ], [], 1 ), ...
    'kin_type', "xyzbc", ...
    'NDiscr', int32( 10 ),...
    'NBreak', int32( 5 ),...
    'UseDynamicBreakpoints',false,...       % Use a variable number of breakpoints for different lengths
    'UseLinearBreakpoints',false,...        % Use a linear distribution of breakpoints (else sinspace)
    'DynamicBreakpointsDistance', 0.1,...   % Distance between two breakpoints in mm
    'NHorz', int32( 5 ),...
    'fmax', 150,...
    'smax', 75000,...
    'vmax', [500,500,800,0, 40,50],... %[mm] [rad]
    'amax', [15000,15000,15000,0, 200,1000],...
    'jmax', [750000,750000,3000000,0,10000,50000],...
    'LeeSplineDegree', int32( 4 ),...
    'SplineDegree',    int32( 3 ),...
    'CutOff', 0.1,...
    'LSplit', 3.0,...
    'LSplitZero', 0.1,...
    'LThreshold', 5,...
    'CuspThreshold', 45,...
    'v_0', 0, 'at_0', 0,...
    'v_1', 0, 'at_1', 0,...
    'dt', 1e-4, ...
    'ZeroStartAccLimit', 0.01, ...
    'ZeroStartJerkLimit', 1E6, ...
    'ZeroStartVelLimit', 0.5, ...
    'source', repmat(char(0), [1, 1024]),...
    'DebugCutZero', false,...
    'Compressing', struct(...
    'Skip', false,...
    'ColTolCosLee',     cosd(tol_col_compress_deg)),...
    'ColTolCosSmooth',  cosd(tol_col_smooth_deg), ...
    'GaussLegendreN', GaussLegendreN, ...
    'GaussLegendreX', GaussLegendreX, ...
    'GaussLegendreW', GaussLegendreW, ...
    'opt', LP,...
    'LogFileName', 'logs/logs');

if ~coder.target( 'MATLAB' )
    coder.varsize( 'cfg.indCart',   StructTypeName.dimInd{ : } );
    coder.varsize( 'cfg.indRot',    StructTypeName.dimInd{ : } );
    coder.varsize( 'cfg.maskTot',   StructTypeName.dimMask{ : } );
    coder.varsize( 'cfg.maskCart',  StructTypeName.dimMask{ : } );
    coder.varsize( 'cfg.maskRot',   StructTypeName.dimMask{ : } );
    coder.varsize( 'cfg.kin_params',StructTypeName.dimKinParams{ : } );
    coder.cstructname( cfg,         StructTypeName.FeedoptCfg );
end

cfg = check_values( cfg );
end

function [ cfg ] = check_values( cfg )
    cfg.maskCart   = and( cfg.maskTot, logical( [ 1, 1, 1, 0, 0, 0 ] ) );
    cfg.maskRot    = and( cfg.maskTot, logical( [ 0, 0, 0, 1, 1, 1 ] ) );
    cfg.NumberAxis = int32( sum( cfg.maskTot ) );
    cfg.NCart      = int32( sum( cfg.maskCart ) );
    cfg.NRot       = cfg.NumberAxis - cfg.NCart;

    if( cfg.NCart > 0 )
        cfg.indCart = [ 1 : cfg.NCart ].';
    end

    if( cfg.NRot > 0 )
        cfg.indRot = [ 1 : cfg.NRot ].' + cfg.NCart;
    end
end
