function [] = generate_feedopt_c( cfg, output_root, debug )

if( nargin < 3 ), debug = false; end

% if( debug ), output_root = "toErase"; end

if( isfolder( output_root ) ), rmdir( output_root, 's' ); end

configType      = coder.OutputType('FeedoptDefaultConfig');
ctxType         = coder.OutputType('InitFeedoptPlan');
resampleType    = coder.OutputType('ResampleState');
C               = coder.OutputType('constrCurvStructType');
splineType      = coder.OutputType('bspline_create');

global sqrt_calls sin_calls cos_calls cot_calls DebugConfig
sqrt_calls = 0;
sin_calls = 0;
cos_calls = 0;
cot_calls = 0;
DebugConfig = 0;

P0 = [0,0,0]';
trafo = false; HSC = false;
Doff = 0.0;

if( ~debug  )
    codegen('-config', cfg,'-d', output_root, '-o', 'opencn_matlab',...
        'constrCurvStructType',...
        'FeedoptDefaultConfig',...
        'InitFeedoptPlan', '-args', configType,...
        'EvalCurvStruct', '-args', {ctxType, C, coder.typeof(0.0, [1, Inf], [0, 1])},...
        'CalcTransition', '-args', {ctxType, C, C},...
        'linspace', '-args', {0,1,100}, ...
        'ConstrLineStruct', '-args', {trafo, HSC, P0, P0 P0, Doff, P0, P0, P0, P0, P0, P0, 1.0, ZSpdMode.NN},...
        'ConstrHelixStruct', '-args', {trafo, HSC, P0, P0 P0, Doff, P0, P0, P0, P0, P0, P0, P0, 1.0, P0, 1.0, 1.0, 1.0, ZSpdMode.NN},...
        'ConstrHelixStructFromArcFeed', '-args', {trafo, HSC, P0, P0 P0, Doff, 0,0,0,  0,0,0,  0,0,0,  P0, P0, P0, P0, 0,[0,0,0]'},...
        'bspline_create', '-args', {int32(4), linspace(0,1,10)},...
        'ResampleState', '-args', 0,...
        'resampleCurv', '-args', {resampleType, splineType, ZSpdMode.NN, ...
        coder.typeof(0.0, [Inf, 1], [1,0]), ...
        0.0, 0.0 , 1.0, 0.0 },...
        'EvalPosition', '-args', {C, C, 0},...
        'bspline_copy', '-args', splineType,...
        'ConfigSetSource', '-args', {configType, coder.typeof(' ', [1, 1024], [0, 1])},...
        'FeedoptPlan', '-args', ctxType...
        );

else
    codegen('-config', cfg,'-d', output_root, '-o', 'opencn_matlab',...
        'constrGcodeInfoStructType',...
        'constrGcodeInfoStruct', '-args', paramsDefaultGCodeInfo( StructTypeName.MEX ),...
        'constrBaseSplineType',...
        'constrBaseSpline', '-args', paramsDefaultBaseSpline( StructTypeName.MEX ),...
        'constrSplineType',...
        'constrSpline', '-args', paramsDefaultSpline( StructTypeName.MEX ),...
        'constrCurvStructType',...
        'constrCurvStruct', '-args', paramsDefaultCurv( StructTypeName.MEX ),...
        'constrHelixStruct', '-args', paramsDefaultHelix( StructTypeName.MEX ),...
        'constrHelixStructFromArcFeed', '-args', paramsDefaultHelixFromArcFeed( StructTypeName.MEX ), ...
        'constrLineStruct', '-args', paramsDefaultLine( StructTypeName.MEX ), ...
        'constrTransP5Struct', '-args', paramsDefaultTransition( StructTypeName.MEX ),...
        'angles2deg', '-args', coder.typeof( zeros( 1, 1 ), [ Inf, Inf ], [ 1, 1 ] ),...
        'angles2rad', '-args', coder.typeof( zeros( 1, 1 ), [ Inf, Inf ], [ 1, 1 ] ),...
        'anglesNormDin', '-args', paramsDefaultAnglesNormDim( StructTypeName.MEX ),...
        'FeedoptDefaultConfig',...
        'initFeedoptPlan', '-args', configType...
    );
end

end