
function [] = generate_kinematics_c( cfg, output_root, debug )
[R, P] = varTypeKinematic;

if( nargin < 3 ), debug = false; end

if( debug ), output_root = "toErase"; end

if( isfolder( output_root ) ), rmdir( output_root, 's' ); end

if( ~debug  )
    codegen('-config', cfg,'-d', output_root, '-o', 'opencn_matlab',...
        'kin_forward_xyzbc', '-args', {R, P},...
        'kin_inverse_xyzbc', '-args', {R, P},...
        'kin_forward_jacobian_xyzbc', '-args', {R, R, P},...
        'kin_inverse_jacobian_xyzbc', '-args', {R, R, P},...
        'kin_forward_jacobian_1pd_xyzbc', '-args', {R, R, R, P},...
        'kin_inverse_jacobian_1pd_xyzbc', '-args', {R, R, R, P},...
        'kin_forward_jacobian_2pd_xyzbc', '-args', {R, R, R, R, P},...
        'kin_inverse_jacobian_2pd_xyzbc', '-args', {R, R, R, R, P} );
else
     codegen('-config', cfg,'-d', output_root, '-o', 'opencn_matlab',...
        'kin_forward_xyzbc', '-args', {R, P},...
        'kin_inverse_xyzbc', '-args', {R, P},...
        'kin_forward_jacobian_xyzbc', '-args', {R, R, P},...
        'kin_inverse_jacobian_xyzbc', '-args', {R, R, P},...
        'kin_forward_jacobian_1pd_xyzbc', '-args', {R, R, R, P},...
        'kin_inverse_jacobian_1pd_xyzbc', '-args', {R, R, R, P},...
        'kin_forward_jacobian_2pd_xyzbc', '-args', {R, R, R, R, P},...
        'kin_inverse_jacobian_2pd_xyzbc', '-args', {R, R, R, R, P} );
end

end