
function [] = generate_kinematics_c( cfg, output_root, debug )
[R, P] = varTypeKinematic;

if( nargin < 3 ), debug = false; end

if( debug ), output_root = "toErase"; end

if( isfolder( output_root ) ), rmdir( output_root, 's' ); end

if( ~debug  )
    codegen('-config', cfg,'-d', output_root, '-o', 'opencn_matlab',...
        'MGD', '-args', {R, P},...
        'MGI', '-args', {R, P},...
        'J_ar', '-args', {R, P},...
        'J_arP', '-args', {R, R, P},...
        'J_arPP', '-args', {R, R, R, P} );
else
    codegen('-config', cfg,'-d', output_root, '-o', 'opencn_matlab',...
        'MGD', '-args', {R, P},...
        'MGI', '-args', {R, P},...
        'J_ar', '-args', {R, P},...
        'J_arP', '-args', {R, R, P},...
        'J_arPP', '-args', {R, R, R, P} );
end

end