
function [] = generate_kinematics_c( cfg, output_root, debug )
[R, P] = varTypeKinematic;

if( nargin < 3 ), debug = false; end

if( debug ), output_root = "toErase"; end
 
if( isfolder( output_root ) ), rmdir( output_root, 's' ); end

if( ~debug  )
    codegen('-config', cfg,'-d', output_root, '-o', 'kinematics',...
        KinematicsTypeName.get_fun_name( KinFunctionName.MGD ) ,    '-args', {R, P},...
        KinematicsTypeName.get_fun_name( KinFunctionName.MGI ),     '-args', {R, P},...
        KinematicsTypeName.get_fun_name( KinFunctionName.J_ar ),    '-args', {R, P},...
        KinematicsTypeName.get_fun_name( KinFunctionName.JP_ar ),   '-args', {R, R, P},...
        KinematicsTypeName.get_fun_name( KinFunctionName.J2P_ar ),  '-args', {R, R, R, P}, ...
        KinematicsTypeName.get_fun_name( KinFunctionName.J_ra ),    '-args', {R, P},...
        KinematicsTypeName.get_fun_name( KinFunctionName.JP_ra ),   '-args', {R, R, P},...
        KinematicsTypeName.get_fun_name( KinFunctionName.J2P_ra ),  '-args', {R, R, R, P} ...
        );
else
        codegen('-config', cfg,'-d', output_root, '-o', 'formatCommandAxeC',...
        "formatCommandAxeC" ,       '-args', { 0, 0, 0 }, ...
        "formatCommandAxeCDiff" ,   '-args', { 0, 0, 0, false }...
        );
%     codegen('-config', cfg,'-d', output_root, '-o', 'kinematics',...
%         KinematicsTypeName.get_fun_name( KinFunctionName.MGD ) ,    '-args', {R, P},...
%         KinematicsTypeName.get_fun_name( KinFunctionName.MGI ),     '-args', {R, P},...
%         KinematicsTypeName.get_fun_name( KinFunctionName.J_ar ),    '-args', {R, P},...
%         KinematicsTypeName.get_fun_name( KinFunctionName.JP_ar ),   '-args', {R, R, P},...
%         KinematicsTypeName.get_fun_name( KinFunctionName.J2P_ar ),  '-args', {R, R, R, P}, ...
%         KinematicsTypeName.get_fun_name( KinFunctionName.J_ra ),    '-args', {R, P},...
%         KinematicsTypeName.get_fun_name( KinFunctionName.JP_ra ),   '-args', {R, R, P},...
%         KinematicsTypeName.get_fun_name( KinFunctionName.J2P_ra ),  '-args', {R, R, R, P} ...
%         );
end

end