clear; clc;

% the current folder must be 'opencn/agency/usr/matlab/common'

% please choose the target first ( only 1 target is generated at the time )
generate_for_arm_32 = false;
generate_for_x86_64 = true;
generate_for_arm_64 = false;

% please choose the libraries to generate ( All can be generated )
generate_all = false;

if( ~generate_all )
    generate_Feedopt   = false;
    generate_kinematic = true;
end

[cfg, output_root] = generate_c_config(generate_for_arm_32, generate_for_arm_64, generate_for_x86_64, 1);

if( isfolder( output_root ) ), rmdir( output_root, 's' ); end

output_root = output_root + "/matlab/generated" + "/Feedopt";


% A coder.OutputType object represents the type of an entry-point (codegen) function output variable.
% Use coder.OutputType to specify an input for another entry-point (codegen) function.
% Important: Pass the input by using the codegen '-args' option.
% Do not pass a coder.OutputType object as an input to a generated MEX function.

configType = coder.OutputType('FeedoptDefaultConfig');
ctxType = coder.OutputType('InitFeedoptPlan');
resampleType = coder.OutputType('ResampleState');
C = coder.OutputType('constrCurvStructType');
splineType = coder.OutputType('bspline_create');

global sqrt_calls sin_calls cos_calls cot_calls DebugConfig
sqrt_calls = 0;
sin_calls = 0;
cos_calls = 0;
cot_calls = 0;
DebugConfig = 0;

P0 = [0,0,0]';
trafo = false; HSC = false;
Doff = 0.0;

% 'codegen options function -args {func_inputs}' generates C or C++ code
% from a MATLAB function (codegen entry-point) with inputs of type func_inputs.
% Use the options argument to specify settings such as the code generation configuration object.

% Important: Matlab Crash (2021b, Update 2, Coder version 5.3 on Linux Ubuntu)
% if 'EvalCurvStruct' is removed from this list

DEBUG = true;

if( ~DEBUG  )
    codegen('-config', cfg,'-d', output_root, '-o', 'opencn_matlab',...
        'constrCurvStructType',...
        'FeedoptDefaultConfig',...
        'InitFeedoptPlan', '-args', configType,...
        'EvalCurvStruct', '-args', {ctxType, C, coder.typeof(0.0, [1, Inf], [0, 1])},...
        'CalcTransition', '-args', {ctxType, C, C},...
        'linspace', '-args', {0,1,100}, ...
        'ConstrLineStruct', '-args', {trafo, HSC, P0, P0 P0, Doff, P0, P0, P0, P0, P0, P0, 1.0, ZSpdMode.NN},...
        'ConstrHelixStruct', '-args', {trafo, HSC, P0, P0 P0, Doff, P0, P0, P0, P0, P0, P0, P0, 1.0, P0, 1.0, 1.0, 1.0, ZSpdMode.NN},...
        'ConstrHelixStructFromArcFeed', '-args', {trafo, HSC, P0, P0 P0, Doff, 0,0,0,  0,0,0,  0,0,0,  P0, P0, P0, P0, 0,[0,0,0]'},...
        'bspline_create', '-args', {int32(4), linspace(0,1,10)},...
        'ResampleState', '-args', 0,...
        'resampleCurv', '-args', {resampleType, splineType, ZSpdMode.NN, ...
        coder.typeof(0.0, [Inf, 1], [1,0]), ...
        0.0, 0.0 , 1.0, 0.0 },...
        'EvalPosition', '-args', {C, C, 0},...
        'bspline_copy', '-args', splineType,...
        'ConfigSetSource', '-args', {configType, coder.typeof(' ', [1, 1024], [0, 1])},...
        'FeedoptPlan', '-args', ctxType...
        );

else
    toErase = "toErase";
    if( isfolder( toErase ) ), rmdir( toErase, 's' ); end
    mkdir( toErase );
    codegen('-config', cfg,'-d', toErase, '-o', 'opencn_matlab',...
        'constrGcodeInfoStructType',...
        'constrGcodeInfoStruct', '-args', paramsDefaultGCodeInfo( StructTypeName.MEX ),...
        'constrBaseSplineType',...
        'constrBaseSpline', '-args', paramsDefaultBaseSpline( StructTypeName.MEX ),...
        'constrSplineType',...
        'constrSpline', '-args', paramsDefaultSpline( StructTypeName.MEX ),...
        'constrCurvStructType',...
        'constrCurvStruct', '-args', paramsDefaultCurv( StructTypeName.MEX ),...
        'constrHelixStruct', '-args', paramsDefaultHelix( StructTypeName.MEX ),...
        'constrHelixStructFromArcFeed', '-args', paramsDefaultHelixFromArcFeed( StructTypeName.MEX ), ...
        'constrLineStruct', '-args', paramsDefaultLine( StructTypeName.MEX ), ...
        'constrTransP5Struct', '-args', paramsDefaultTransition( StructTypeName.MEX ),...
        'angles2deg', '-args', coder.typeof( zeros( 1, 1 ), [ Inf, Inf ], [ 1, 1 ] ),...
        'angles2rad', '-args', coder.typeof( zeros( 1, 1 ), [ Inf, Inf ], [ 1, 1 ] ),...
        'anglesNormDin', '-args', paramsDefaultAnglesNormDim( StructTypeName.MEX ),...
        'FeedoptDefaultConfig',...
        'initFeedoptPlan', '-args', configType...
    );
%     toErase = "toErase";
%     if( isfolder( toErase ) ), rmdir( toErase, 's' ); end
%     mkdir( toErase );
%     codegen('-config', cfg,'-d', output_root, '-o', 'opencn_matlab',...
%         'constrGcodeInfoStructType',...
%         'constrGcodeInfoStruct', '-args', paramsDefaultGCodeInfo( StructTypeName.MEX ),...
%         'constrBaseSplineType',...
%         'constrBaseSpline', '-args', paramsDefaultBaseSpline( StructTypeName.MEX ),...
%         'constrSplineType',...
%         'constrSpline', '-args', paramsDefaultSpline( StructTypeName.MEX ),...
%         'constrCurvStructType',...
%         'constrCurvStruct', '-args', paramsDefaultCurv( StructTypeName.MEX ),...
%         'constrHelixStruct', '-args', paramsDefaultHelix( StructTypeName.MEX ),...
%         'constrHelixStructFromArcFeed', '-args', paramsDefaultHelixFromArcFeed( StructTypeName.MEX ), ...
%         'constrLineStruct', '-args', paramsDefaultLine( StructTypeName.MEX ), ...
%         'constrTransP5Struct', '-args', paramsDefaultTransition( StructTypeName.MEX ),...
%         'angles2deg', '-args', coder.typeof( zeros( 1, 1 ), [ Inf, Inf ], [ 1, 1 ] ),...
%         'angles2rad', '-args', coder.typeof( zeros( 1, 1 ), [ Inf, Inf ], [ 1, 1 ] ),...
%         'anglesNormDin', '-args', paramsDefaultAnglesNormDim( StructTypeName.MEX ) );
>>>>>>> 628ddae114382a1f0119d134e8f35f84e6768ef4
end

if( generate_all || generate_kinematic )
    if( ~ DEBUG  )
        codegen('-config', cfg,'-d', output_root, '-o', 'opencn_matlab',...
                'MGD', '-args', {0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0},...
                'MGI', '-args', {0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0},...
                'J_ar', '-args', {0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0},...
                'J_arP', '-args', {0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0},...
                'J_arPP', '-args', {0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0} );
    
    else
        toErase = "toErase";
        mkdir( toErase );
        %     codegen('-config', cfg,'-d', toErase,'modeIncremental', '-args', {CDef.P0, CDef.P0},'-o', 'modeIncremental');
    end