function [] = generate_feedopt_c( cfg, output_root, debug )

if( nargin < 3 ), debug = false; end

if( debug ), output_root = "toErase"; end

if( isfolder( output_root ) ), rmdir( output_root, 's' ); end

configType      = coder.OutputType('FeedoptDefaultConfig');
ctxType         = coder.OutputType('initFeedoptPlan');
resampleType    = coder.OutputType('ResampleState');
C               = coder.OutputType('constrCurvStructType');
splineType      = coder.OutputType('bspline_create');

global sqrt_calls sin_calls cos_calls cot_calls DebugConfig
sqrt_calls = 0;
sin_calls = 0;
cos_calls = 0;
cot_calls = 0;
DebugConfig = 0;

P0 = [0,0,0]';
trafo = false; HSC = false;
Doff = 0.0;

if( ~debug  )
    codegen('-config', cfg,'-d', output_root, '-o', 'opencn_matlab',...
        'constrGcodeInfoStructType',...
        'constrGcodeInfoStruct', '-args', paramsDefaultGCodeInfo( StructTypeName.MEX ),...
        'constrBaseSplineType',...
        'constrBaseSpline', '-args', paramsDefaultBaseSpline( StructTypeName.MEX ),...
        'constrSplineType',...
        'constrSpline', '-args', paramsDefaultSpline( StructTypeName.MEX ),...
        'constrCurvStructType',...
        'constrCurvStruct', '-args', paramsDefaultCurv( StructTypeName.MEX ),...
        'constrHelixStruct', '-args', paramsDefaultHelix( StructTypeName.MEX ),...
        'constrHelixStructFromArcFeed', '-args', paramsDefaultHelixFromArcFeed( StructTypeName.MEX ), ...
        'constrLineStruct', '-args', paramsDefaultLine( StructTypeName.MEX ), ...
        'constrTransP5Struct', '-args', paramsDefaultTransition( StructTypeName.MEX ),...
        'angles2deg', '-args', coder.typeof( zeros( 3, 1 ) ),...
        'angles2rad', '-args', coder.typeof( zeros( 3, 1 ) ),...
        'anglesNormDin', '-args', paramsDefaultAnglesNormDim( StructTypeName.MEX ),...
        'FeedoptDefaultConfig',...
        'initFeedoptPlan', '-args', configType,...
        'FeedoptPlan', '-args', ctxType...
        );
else
    codegen('-config', cfg,'-d', output_root, '-o', 'opencn_matlab',...
        'constrGcodeInfoStructType',...
        'constrGcodeInfoStruct', '-args', paramsDefaultGCodeInfo( StructTypeName.MEX ),...
        'constrBaseSplineType',...
        'constrBaseSpline', '-args', paramsDefaultBaseSpline( StructTypeName.MEX ),...
        'constrSplineType',...
        'constrSpline', '-args', paramsDefaultSpline( StructTypeName.MEX ),...
        'constrCurvStructType',...
        'constrCurvStruct', '-args', paramsDefaultCurv( StructTypeName.MEX ),...
        'constrHelixStruct', '-args', paramsDefaultHelix( StructTypeName.MEX ),...
        'constrHelixStructFromArcFeed', '-args', paramsDefaultHelixFromArcFeed( StructTypeName.MEX ), ...
        'constrLineStruct', '-args', paramsDefaultLine( StructTypeName.MEX ), ...
        'constrTransP5Struct', '-args', paramsDefaultTransition( StructTypeName.MEX ),...
        'angles2deg', '-args', coder.typeof( zeros( 3, 1 ) ),...
        'angles2rad', '-args', coder.typeof( zeros( 3, 1 ) ),...
        'anglesNormDin', '-args', paramsDefaultAnglesNormDim( StructTypeName.MEX ),...
        'FeedoptDefaultConfig',...
        'initFeedoptPlan', '-args', configType,...
        'FeedoptPlan', '-args', ctxType...
        );

%     codegen('-config', cfg,'-d', output_root, '-o', 'opencn_matlab',...
%         'FeedoptDefaultConfig',...
%         'initFeedoptPlan', '-args', configType,...
%         'FeedoptPlan', '-args', ctxType...
%         );

%     codegen('-config', cfg,'-d', output_root, '-o', 'opencn_matlab',...
%         'constrGcodeInfoStructType',...
%         'constrGcodeInfoStruct', '-args', paramsDefaultGCodeInfo( StructTypeName.MEX ),...
%         'constrBaseSplineType',...
%         'constrBaseSpline', '-args', paramsDefaultBaseSpline( StructTypeName.MEX ),...
%         'constrSplineType',...
%         'constrSpline', '-args', paramsDefaultSpline( StructTypeName.MEX ),...
%         'constrCurvStructType',...
%         'constrCurvStruct', '-args', paramsDefaultCurv( StructTypeName.MEX ),...
%         'constrHelixStruct', '-args', paramsDefaultHelix( StructTypeName.MEX ),...
%         'constrHelixStructFromArcFeed', '-args', paramsDefaultHelixFromArcFeed( StructTypeName.MEX ), ...
%         'constrLineStruct', '-args', paramsDefaultLine( StructTypeName.MEX ), ...
%         'constrTransP5Struct', '-args', paramsDefaultTransition( StructTypeName.MEX ),...
%         'angles2deg', '-args', coder.typeof( zeros( 3, 1 ) ),...
%         'angles2rad', '-args', coder.typeof( zeros( 3, 1 ) ),...
%         'anglesNormDin', '-args', paramsDefaultAnglesNormDim( StructTypeName.MEX )...
%         );

end

end