clc; clear;

[ outputDir ] = setup();
%% Matlab symbolic tool box
R   = sym( 'R',  [5, 1], 'real' );
Rp  = sym( 'Rp', [5, 1], 'real' );
Rpp = sym( 'Rpp',[5, 1], 'real' );
P   = sym( 'P',  [3, 4], 'real' );

% Kinematic basic models
[ MGD ] = forwardKinematicModel_Factory( R, P );
[ MGI ] = backwardKinematicModel_Factory( R, P );

% Jacobians
J_ar   = simplify( jacobian( MGI, R ) );
JP_ar  = simplify( jacobian( J_ar  * Rp, R ) );
J2P_ar = simplify( jacobian( JP_ar * Rp, R ) + jacobian( JP_ar * Rpp, Rp ) );

J_ra   = simplify( jacobian( MGD, R) );
JP_ra  = simplify( jacobian( J_ra  * Rp, R ) );
J2P_ra = simplify( jacobian( JP_ra * Rp, R) + jacobian( JP_ra * Rpp, Rp ) );

%% Matlab code generation
TO_REPLACE  = 'TO_REPLACE';

% Backward kinematics
fileName    = outputDir + ...
              KinematicsTypeName.get_fun_name( KinFunctionName.MGI ) + ".m";
matlabFunction( MGI, 'vars', {R, P}, 'file', fileName, 'Comments', TO_REPLACE );
write_comments( fileName, TO_REPLACE, KinFunctionName.MGI );

% Forward kinematics
fileName    = outputDir + ...
              KinematicsTypeName.get_fun_name( KinFunctionName.MGD ) + ".m";
matlabFunction( MGD, 'vars', {R, P}, 'file', fileName, 'Comments', TO_REPLACE );
write_comments( fileName, TO_REPLACE, KinFunctionName.MGD );

% Jacobian ( backward )
fileName    = outputDir + ...
              KinematicsTypeName.get_fun_name( KinFunctionName.J_ar ) + ".m";
matlabFunction( J_ar,  'vars',  {R, P}, 'file', fileName, 'Comments', TO_REPLACE );
write_comments( fileName, TO_REPLACE, KinFunctionName.J_ar );

% Jacobian ( forward )
fileName    = outputDir + ...
              KinematicsTypeName.get_fun_name( KinFunctionName.J_ra ) + ".m";
matlabFunction( J_ra,  'vars',  {R, P}, 'file', fileName, 'Comments', TO_REPLACE );
write_comments( fileName, TO_REPLACE, KinFunctionName.J_ra );

% Jacobian first derivative ( backward )
fileName    = outputDir + ...
              KinematicsTypeName.get_fun_name( KinFunctionName.JP_ar ) + ".m";
matlabFunction( JP_ar,  'vars',  {R, Rp, P}, 'file', fileName, 'Comments', TO_REPLACE );
write_comments( fileName, TO_REPLACE, KinFunctionName.JP_ar );

% Jacobian first derivative ( forward )
fileName    = outputDir + ...
              KinematicsTypeName.get_fun_name( KinFunctionName.JP_ra ) + ".m";
matlabFunction( JP_ra,  'vars',  {R, Rp, P}, 'file', fileName, 'Comments', TO_REPLACE );
write_comments( fileName, TO_REPLACE, KinFunctionName.JP_ra );

% Jacobian second derivative ( backward )
fileName    = outputDir + ...
              KinematicsTypeName.get_fun_name( KinFunctionName.J2P_ar ) + ".m";
matlabFunction( J2P_ar,  'vars',  {R, Rp, Rpp, P}, 'file', fileName, 'Comments', TO_REPLACE );
write_comments( fileName, TO_REPLACE, KinFunctionName.J2P_ar );

% Jacobian second derivative ( forward )
fileName    = outputDir + ...
              KinematicsTypeName.get_fun_name( KinFunctionName.J2P_ra ) + ".m";
matlabFunction( J2P_ra,  'vars',  {R, Rp, Rpp, P}, 'file', fileName, 'Comments', TO_REPLACE );
write_comments( fileName, TO_REPLACE, KinFunctionName.J2P_ra );

function [ outputDir ] = setup()

check_wkdir();
outputDir = "kinematics/gen_fun/";
path_mex = genpath( outputDir );
rmpath( path_mex );

if( isfolder( outputDir ) ), rmdir( outputDir, 's' ); end
mkdir( outputDir );
addpath( path_mex );

end

function [] = write_comments( fileName, to_replace, name )
[ comments ] = get_comments( name );
comments     = join( comments , "\n%" );
fid          = fopen( fileName, 'r' );
f            = fread( fid, '*char' )';
fclose( fid );
f            = regexprep( f, to_replace, comments );
fid          = fopen( fileName, 'w' );
fprintf( fid, '%s', f );
fclose( fid );
end

function [ c ] = get_comments( name )

comments.r_a        =  "\tr_a : 5 x 1 : pose vector( joint )";
comments.v_a        =  "\tv_a : 5 x 1 : speed vector( joint )";
comments.a_a        =  "\ta_a : 5 x 1 : acceleration vector( joint )";
comments.j_a        =  "\tj_a : 5 x 1 : jerk vector( joint )";
comments.r_r        =  "\tr_r : 5 x 1 : pose vector ( relative )";
comments.v_r        =  "\tv_r : 5 x 1 : speed vector ( relative )";
comments.a_r        =  "\ta_a : 5 x 1 : acceleration vector( relative )";
comments.j_r        =  "\tj_r : 5 x 1 : jerk vector( relative )";
comments.p          =  "\tp   : 5 x 1 : parameters";
comments.M          =  "\tM   : 5 x 5 : resulting matrix";
comments.inputs     = "INPUTS : ";
comments.outputs    = "OUTPUTS : ";
comments.codegen    = "#codegen";

switch( name )
    case KinFunctionName.MGI
        c = [ "Backward Kinematics ( Inverse Geometrique Model ) : ", ...
            comments.inputs, ...
            comments.r_r, ...
            comments.p ,...
            comments.outputs,...
            comments.r_a, ...
            comments.codegen];
    case KinFunctionName.MGD
        c = [ "Forward Kinematics ( Direct Geometrique Model )  : ", ...
            comments.inputs, ...
            comments.r_a, ...
            comments.p ,...
            comments.outputs,...
            comments.r_r, ...
            comments.codegen];
    case KinFunctionName.J_ar
        c = [ "Jacobian Kinematics ( backward ) : ", ...
            comments.inputs, ...
            comments.r_r, ...
            comments.v_r, ...
            comments.p ,...
            comments.outputs,...
            comments.M , ...
            comments.codegen];
    case KinFunctionName.J_ra
        c = [ "Jacobian Kinematics ( forward ) : ", ...
            comments.inputs, ...
            comments.r_a, ...
            comments.v_a, ...
            comments.p ,...
            comments.outputs,...
            comments.M , ...
            comments.codegen];
    case KinFunctionName.JP_ar
        c = [ "Jacobian first derivative ( backward ) : ", ...
            comments.inputs, ...
            comments.r_r, ...
            comments.v_r, ...
            comments.a_r, ...
            comments.p ,...
            comments.outputs,...
            comments.M , ...
            comments.codegen];
    case KinFunctionName.JP_ra
        c = [ "Jacobian first derivative ( forward ) : ", ...
            comments.inputs, ...
            comments.r_a, ...
            comments.v_a, ...
            comments.a_a, ...
            comments.p ,...
            comments.outputs,...
            comments.M , ...
            comments.codegen];
    case KinFunctionName.J2P_ar
        c = [ "Jacobian second derivative ( backward ) : ", ...
            comments.inputs, ...
            comments.r_r, ...
            comments.v_r, ...
            comments.a_r, ...
            comments.j_r, ...
            comments.p ,...
            comments.outputs,...
            comments.M , ...
            comments.codegen];
    case KinFunctionName.J2P_ra
        c = [ "Jacobian second derivative ( forward ) : ", ...
            comments.inputs, ...
            comments.r_a, ...
            comments.v_a, ...
            comments.a_a, ...
            comments.j_a, ...
            comments.p ,...
            comments.outputs,...
            comments.M , ...
            comments.codegen];
    otherwise
        error( string( name ) + " : Is not a valide function name" );
end
end