clear; clc;

GenerateGCodeInterpreter = true;
GenerateSimplex = true;
GenerateFeedoptPlanRun = false;
GenerateSpline = true;

cfg = coder.config('mex');
cfg.GenCodeOnly = false;
cfg.FilePartitionMethod = 'SingleFile';
cfg.PreserveArrayDimensions = true;
cfg.GenerateReport = false;
cfg.TargetLang = 'C++';
cfg.CppNamespace = 'ocn';
% cfg.EnableDebugging = true;

cfg.EnableVariableSizing = true;
cfg.DynamicMemoryAllocation = 'Threshold';
% cfg.SILPILCheckConstantInputs = false;
% cfg.SILPILSyncGlobalData = false;
cfg.SaturateOnIntegerOverflow = false;
cfg.GlobalDataSyncMethod = 'NoSync';
% cfg.StackUsageMax = 8096*1024;
% cfg.MultiInstanceCode = true;
cfg.EnableJIT = false;

cfg.HighlightPotentialRowMajorIssues = true;
cfg.IntegrityChecks = false;
cfg.ResponsivenessChecks = false;

cfg.EnableMemcpy = true;
cfg.InitFltsAndDblsToZero = true;
cfg.CppNamespace = 'ocn';

fcfg = coder.OutputType('FeedoptDefaultConfig');
fctx = coder.OutputType('InitFeedoptPlan');

C = coder.OutputType('ConstrCurvStructType');

global DebugActive sqrt_calls
DebugActive = false;
sqrt_calls = 0;

P0 = [0,0,0]';
trafo = false;
Doff = 0.0;

cfg.CustomInclude = [...
    '../../ ' ...
    '. '...
    'src '...cfg.c
    '../../rs274ngc '...
    '../../common/include '];

% fprintf('Mexing CopyCurvStruct\n');
% codegen('-config', cfg, '-d', 'gen_mex/copycurvstruct', ...
%     'CopyCurvStruct', '-args', C,...
%     'ConstrCurvStructType',...
%     '-o', 'CopyCurvStruct_mex');


if GenerateFeedoptPlanRun
    fprintf('Mexing FeedoptPlanRun\n')
    codegen('-config', cfg, '-d', 'gen_mex/feedoptplanrun',...
        'ReadGCode', '-args', {ReadGCodeCmd.Load, coder.typeof(' ', [1,1024], [0, 1])},...
        'ConstrLineStruct', '-args', {trafo, P0, P0 P0, Doff, P0, P0, P0, P0, P0, P0, 1.0, ZSpdMode.NN},...
        'ConstrHelixStruct', '-args', {trafo, P0, P0 P0, Doff, P0, P0, P0, P0, P0, P0, P0, 1.0, P0, 1.0, 1.0, 1.0, ZSpdMode.NN},...
        'ConstrHelixStructFromArcFeed', '-args', {trafo, P0, P0 P0, Doff, 0,0,0,  0,0,0,  0,0,0,  P0, P0, P0, P0, 0,[0,0,0]'},...
        'CopyCurvStruct','-args', C,...
        'ConstrCurvStructType',...
        'FeedoptPlanRun', '-args', fctx, ...
        'FeedoptDefaultConfig', ...
        'InitFeedoptPlan', '-args', fcfg,...
        '-o', 'FeedoptPlanRun_mex');
end


if GenerateGCodeInterpreter
    fprintf('Mexing gcode interpreter\n')
    codegen('-config', cfg,'-d', 'gen_mex/readgcode', ...
        'ReadGCode', '-args', {ReadGCodeCmd.Load, coder.typeof(' ', [1,1024], [0, 1])},...
        'ConstrLineStruct', '-args', {trafo, P0, P0 P0, Doff, P0, P0, P0, P0, P0, P0, 1.0, ZSpdMode.NN},...
        'ConstrHelixStruct', '-args', {trafo, P0, P0 P0, Doff, P0, P0, P0, P0, P0, P0, P0, 1.0, P0, 1.0, 1.0, 1.0, ZSpdMode.NN},...
        'ConstrHelixStructFromArcFeed', '-args', {trafo, P0, P0 P0, Doff, 0,0,0,  0,0,0,  0,0,0,  P0, P0, P0, P0, 0,[0,0,0]'},...
        'CopyCurvStruct','-args', C,...
        'ConstrCurvStructType',...
        '-o', 'ReadGCode_mex');
end

if GenerateSimplex
    fprintf('Mexing simplex solver\n')
    codegen('-config', cfg,'-d', 'gen_mex/c_simplex', ...
        'c_simplex', '-args', {...
        coder.typeof(0.0, [Inf, Inf], [1,1]), ...
        coder.typeof(sparse(0.0), [Inf, Inf], [1,1]),... % A
        coder.typeof(0.0, [Inf, 1], [1,0]),...    % b
        coder.typeof(0.0, [Inf, Inf], [1,1]),... % Aeq
        coder.typeof(0.0, [Inf, 1], [1,0])});   % beq
end

if GenerateSpline
    fcfg = FeedoptDefaultConfig;
    fprintf('Mexing bspline_create\n')
    codegen('-config', cfg,'-d', 'gen_mex/bspline_create', ...
        'bspline_create', '-args', ...
        {fcfg.SplineDegree, coder.typeof(0.0, [1, Inf], [0, 1])},...
        '-o', 'bspline_create_mex');
    %fcfg.SplineDegree, linspace(0, 1, fcfg.NBreak)
    BlType = coder.OutputType('bspline_create');
    %
    fprintf('Mexing bspline_destroy\n')
    codegen('-config', cfg,'-d', 'gen_mex/bspline_destroy', ...
        'bspline_destroy', '-args', BlType,....
        'bspline_create', '-args', {fcfg.SplineDegree, coder.typeof(0.0, [1, Inf], [0, 1])},...
        '-o', 'bspline_destroy_mex');
    
    fprintf('Mexing bspline_base_eval\n')
    codegen('-config', cfg,'-d', 'gen_mex/bspline_base_eval', ...
        'bspline_base_eval', '-args', {BlType, coder.typeof(0.0,[1,Inf])},...
        'bspline_create', '-args', {fcfg.SplineDegree, coder.typeof(0.0, [1, Inf], [0, 1])},...
        '-o', 'bspline_base_eval_mex');
    
    fprintf('Mexing bspline_eval\n')
    codegen('-config', cfg,'-d', 'gen_mex/bspline_eval', ...
        'bspline_eval', '-args', ...
        {BlType, coder.typeof(0.0, [1, Inf], [1, 0]), 0.5},...
        'bspline_create', '-args', {fcfg.SplineDegree, coder.typeof(0.0, [1, Inf], [0, 1])},...
        '-o', 'bspline_eval_mex');
    
    % fprintf('Mexing bspline_fit\n')
    % codegen('-config', cfg,'-d', 'gen_mex/bspline_fit', ...
    %     'bspline_fit', '-args', ...
    %     {Bl,...
    %     coder.typeof(0.0, [1, Inf], [1, 0]), ...    % u
    %     coder.typeof(0.0, [3, Inf], [1, 0]),...     % points
    %     });
    
%     bspline_destroy(Bl);
end
%
