addpath '.'
pathOfInterest = { 
    'advanced_pg',...
    'Feedopt',...
    'gen_mex',...
    'generate',...
    'kinematics',...
    'Tests',...
    'types/',...
    'utils/',...
    'Validate_OpenCN',...
    };

% pathOfInterest = { 
%     'advanced_pg',...
%     'Feedopt',...
%     'gen_mex',...
%     'generate',...
%     'kinematics',...
%     'Tests',...
%     'types/',...
%     'utils/',...
%     'Validate_OpenCN',...
%     };

if( exist( "dev" , 'dir' ) ), addpath( "dev/" ); end

for t = 1 : length( pathOfInterest )
    genPath = genpath( pathOfInterest{ t } );
    addpath( genPath );
end

files2Open = { "ocn_assert.m", "FeedoptDefaultConfig.m", "basic_example.m" };

for f_ = files2Open
    edit( f_{ : } );
end

dbstop in ocn_assert at 17
