addpath '.'
pathOfInterest = { 
    'Feedopt',...
    'gen_mex',...
    'generate',...
    'kinematics',...
    'Tests',...
    'types/',...
    'utils/',...
    'Validate_OpenCN',...
    };

if( exist( "dev" , 'dir' ) ), addpath( "dev/" ); end

for t = 1 : length( pathOfInterest )
    genPath = genpath( pathOfInterest{ t } );
    addpath( genPath );
end

