close all; clear; clc;
disp("------------------------------------------------------------------");
disp("Analyse Data");
disp("------------------------------------------------------------------");

data = importfile('log_test_G57_clearance_1_20230906_171448.csv');

targetPosition  = "targetposition";

axisNames       = { "x", "y", "z", "b", "c" };

fieldNnames     = targetPosition + axisNames;

figure('Name', 'Sampler results');
[N, M]  = size(data.Variables);
dt      = 1e-2;

time    = [ 0 : dt : (N -1)* dt ];
count   = 0;
for f_ = fieldNnames
    count = count + 1;
    subplot( 5, 1, count );
    plot( time, data.(f_));
    ylabel( f_ );
    if( count == 1 ), title("Sampler Results"); end
end

xlabel( "Time [s]" );

function data = importfile(filename, dataLines)
%IMPORTFILE Import data from a text file
%  LOGTESTG57CLEARANCE120230906171448 = IMPORTFILE(FILENAME) reads data
%  from text file FILENAME for the default selection.  Returns the data
%  as a table.
%
%  LOGTESTG57CLEARANCE120230906171448 = IMPORTFILE(FILE, DATALINES)
%  reads data for the specified row interval(s) of text file FILENAME.
%  Specify DATALINES as a positive scalar integer or a N-by-2 array of
%  positive scalar integers for dis-contiguous row intervals.
%
%  Example:
%  logtestG57clearance120230906171448 = importfile("/home/hugo/Documents/E2C/opencn/agency/usr/matlab/common/Bugs/AxisNotFollowingGcode/log_test_G57_clearance_1_20230906_171448.csv", [1, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 07-Sep-2023 08:38:09

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [1, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 17);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = " ";

% Specify column names and types
opts.VariableNames = ["targetpositionx", "targetpositiony", "targetpositionz", "targetpositionb", "targetpositionc", "currentposX", "currentposY", "currentposZ", "currentposB", "currentposC", "poserror0", "poserror1", "poserror2", "poserror3", "poserror4", "dataselector", "machiningfinished"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";
opts.ConsecutiveDelimitersRule = "join";
opts.LeadingDelimitersRule = "ignore";

% Specify variable properties
opts = setvaropts(opts, ["targetpositionx", "targetpositiony", "targetpositionz", "targetpositionb", "targetpositionc", "currentposX", "currentposY", "currentposZ", "currentposB", "currentposC", "poserror0", "poserror1", "poserror2", "poserror3", "poserror4", "dataselector", "machiningfinished"], "ThousandsSeparator", ",");

% Import the data
data = readtable(filename, opts);

end