
function [] = generate_kinematics_c( cfg, output_root, debug )

if( nargin < 3 ), debug = false; end

if( debug ), output_root = "toErase"; end
 
if( isfolder( output_root ) ), rmdir( output_root, 's' ); end

if( ~debug  )
    codegen('-config', cfg,'-d', output_root, '-o', 'kinematics',...
        KinematicsTypeName.get_fun_name( KinFunctionName.Forward ) ,...
        '-args', KinematicsTypeName.varTypeKinematic( KinFunctionName.Forward ),...
        KinematicsTypeName.get_fun_name( KinFunctionName.Inverse ),...
        '-args', KinematicsTypeName.varTypeKinematic( KinFunctionName.Inverse ),...
        KinematicsTypeName.get_fun_name( KinFunctionName.J_jt ),...
        '-args', KinematicsTypeName.varTypeKinematic( KinFunctionName.J_jt ),...
        KinematicsTypeName.get_fun_name( KinFunctionName.JP_jt ),...
        '-args', KinematicsTypeName.varTypeKinematic( KinFunctionName.JP_jt ),...
        KinematicsTypeName.get_fun_name( KinFunctionName.J2P_jt ),...
       '-args', KinematicsTypeName.varTypeKinematic( KinFunctionName.J2P_jt ),...
        KinematicsTypeName.get_fun_name( KinFunctionName.J_tj ),...
       '-args', KinematicsTypeName.varTypeKinematic( KinFunctionName.J_tj ),...
        KinematicsTypeName.get_fun_name( KinFunctionName.JP_tj ),...
       '-args', KinematicsTypeName.varTypeKinematic( KinFunctionName.JP_tj ),...
        KinematicsTypeName.get_fun_name( KinFunctionName.J2P_tj ),...
        '-args', KinematicsTypeName.varTypeKinematic( KinFunctionName.J2P_tj )...
        );
else
        codegen('-config', cfg,'-d', output_root, '-o', 'formatCommandAxeC',...
        "formatCommandAxeC" ,       '-args', { 0, 0, 0 }, ...
        "formatCommandAxeCDiff" ,   '-args', { 0, 0, 0, false }...
        );
end

end