
function [] = generate_kinematics_c( cfg, output_root, debug )

if( nargin < 3 ), debug = false; end

if( debug ), output_root = "toErase"; end
 
if( isfolder( output_root ) ), rmdir( output_root, 's' ); end

if( ~debug  )
    codegen('-config', cfg,'-d', output_root, '-o', 'kinematics',...
        KinematicsTypeName.get_fun_name( KinFunctionName.MGD ) ,...
        '-args', KinematicsTypeName.varTypeKinematic( KinFunctionName.MGD ),...
        KinematicsTypeName.get_fun_name( KinFunctionName.MGI ),...
        '-args', KinematicsTypeName.varTypeKinematic( KinFunctionName.MGI ),...
        KinematicsTypeName.get_fun_name( KinFunctionName.J_ar ),...
        '-args', KinematicsTypeName.varTypeKinematic( KinFunctionName.J_ar ),...
        KinematicsTypeName.get_fun_name( KinFunctionName.JP_ar ),...
        '-args', KinematicsTypeName.varTypeKinematic( KinFunctionName.JP_ar ),...
        KinematicsTypeName.get_fun_name( KinFunctionName.J2P_ar ),...
       '-args', KinematicsTypeName.varTypeKinematic( KinFunctionName.J2P_ar ),...
        KinematicsTypeName.get_fun_name( KinFunctionName.J_ra ),...
       '-args', KinematicsTypeName.varTypeKinematic( KinFunctionName.J_ra ),...
        KinematicsTypeName.get_fun_name( KinFunctionName.JP_ra ),...
       '-args', KinematicsTypeName.varTypeKinematic( KinFunctionName.JP_ra ),...
        KinematicsTypeName.get_fun_name( KinFunctionName.J2P_ra ),...
        '-args', KinematicsTypeName.varTypeKinematic( KinFunctionName.J2P_ra )...
        );
else
        codegen('-config', cfg,'-d', output_root, '-o', 'formatCommandAxeC',...
        "formatCommandAxeC" ,       '-args', { 0, 0, 0 }, ...
        "formatCommandAxeCDiff" ,   '-args', { 0, 0, 0, false }...
        );
end

end