function JP_jt = kin_xyzbc_tt_JP_jt(in1,in2,in3)
%kin_xyzbc_tt_JP_jt
%    JP_jt = kin_xyzbc_tt_JP_jt(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 9.1.
%    09-Oct-2023 10:15:21

%Jacobian first derivative ( Inverse Kinematics ) : 
%INPUTS : 
%	r_t    (5x1) : pose vector ( piece frame )
%	v_t    (5x1) : speed vector ( piece frame )
%	a_t    (5x1) : acceleration vector( piece frame )
%	p      (3x5) : parameters
%OUTPUTS : 
%	M      (5x5) : resulting matrix
%#codegen
b = in1(4,:);
c = in1(5,:);
offB1 = in3(10);
offC1 = in3(13);
offB3 = in3(12);
offC2 = in3(14);
offC3 = in3(15);
offP1 = in3(7);
offP2 = in3(8);
offP3 = in3(9);
tp1 = in2(1,:);
tp2 = in2(2,:);
tp3 = in2(3,:);
tp4 = in2(4,:);
tp5 = in2(5,:);
x = in1(1,:);
y = in1(2,:);
z = in1(3,:);
t2 = cos(b);
t3 = cos(c);
t4 = sin(b);
t5 = sin(c);
t6 = offC1.*t3;
t7 = offC2.*t3;
t8 = offP1.*t3;
t9 = offP2.*t3;
t10 = t3.*x;
t11 = t3.*y;
t12 = offC1.*t5;
t13 = offC2.*t5;
t14 = offP1.*t5;
t15 = offP2.*t5;
t16 = t5.*x;
t17 = t5.*y;
t18 = -t13;
t19 = -t15;
t20 = -t17;
t21 = t7+t9+t11+t12+t14+t16;
t22 = t6+t8+t10+t18+t19+t20;
mt1 = [-t3.*t4.*tp4-t2.*t5.*tp5,t3.*tp5,-t2.*t3.*tp4+t4.*t5.*tp5,0.0,0.0,-t2.*t3.*tp5+t4.*t5.*tp4,-t5.*tp5,t2.*t5.*tp4+t3.*t4.*tp5,0.0,0.0,t2.*tp4,0.0,-t4.*tp4,0.0,0.0,t2.*tp3-offB1.*t2.*tp4-offB3.*t4.*tp4-offC3.*t4.*tp4-offP3.*t4.*tp4-t3.*t4.*tp1+t4.*t5.*tp2-t2.*t6.*tp4-t2.*t8.*tp4-t2.*t10.*tp4+t4.*t7.*tp5+t4.*t9.*tp5+t2.*t13.*tp4+t4.*t11.*tp5+t2.*t15.*tp4+t4.*t12.*tp5+t2.*t17.*tp4+t4.*t14.*tp5+t4.*t16.*tp5-t4.*tp4.*z,0.0];
mt2 = [-t4.*tp3+offB1.*t4.*tp4-offB3.*t2.*tp4-offC3.*t2.*tp4-offP3.*t2.*tp4-t2.*t3.*tp1+t2.*t5.*tp2+t2.*t7.*tp5+t4.*t6.*tp4+t2.*t9.*tp5+t4.*t8.*tp4+t2.*t11.*tp5+t4.*t10.*tp4+t2.*t12.*tp5+t2.*t14.*tp5+t2.*t16.*tp5+t4.*t18.*tp4+t4.*t19.*tp4+t4.*t20.*tp4-t2.*tp4.*z,0.0,0.0,-t2.*t3.*tp2-t2.*t5.*tp1-t2.*t22.*tp5+t4.*t21.*tp4,t3.*tp1-t5.*tp2-t7.*tp5-t9.*tp5-t11.*tp5-t12.*tp5-t14.*tp5-t16.*tp5,t3.*t4.*tp2+t4.*t5.*tp1+t2.*t21.*tp4+t4.*t22.*tp5,0.0,0.0];
JP_jt = reshape([mt1,mt2],5,5);
