function J_jt = kin_xyzbc_tt_J_jt(in1,in2)
%kin_xyzbc_tt_J_jt
%    J_jt = kin_xyzbc_tt_J_jt(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.1.
%    09-Oct-2023 10:15:20

%Jacobian Kinematics ( Inverse Kinematics ) : 
%INPUTS : 
%	r_j    (5x1) : pose vector( joint space )
%	v_j    (5x1) : speed vector( joint space )
%	p      (3x5) : parameters
%OUTPUTS : 
%	M      (5x5) : resulting matrix
%#codegen
b = in1(4,:);
c = in1(5,:);
offB1 = in2(10);
offC1 = in2(13);
offB3 = in2(12);
offC2 = in2(14);
offC3 = in2(15);
offP1 = in2(7);
offP2 = in2(8);
offP3 = in2(9);
x = in1(1,:);
y = in1(2,:);
z = in1(3,:);
t2 = cos(b);
t3 = cos(c);
t4 = sin(b);
t5 = sin(c);
t6 = offC2.*t3;
t7 = offP2.*t3;
t8 = t3.*y;
t9 = offC1.*t5;
t10 = offP1.*t5;
t11 = t5.*x;
t12 = t6+t7+t8+t9+t10+t11;
J_jt = reshape([t2.*t3,t5,-t3.*t4,0.0,0.0,-t2.*t5,t3,t4.*t5,0.0,0.0,t4,0.0,t2,0.0,0.0,-offB1.*t4+offB3.*t2+offC3.*t2+offP3.*t2+t2.*z-offC1.*t3.*t4+offC2.*t4.*t5-offP1.*t3.*t4+offP2.*t4.*t5-t3.*t4.*x+t4.*t5.*y,0.0,-offB1.*t2-offB3.*t4-offC3.*t4-offP3.*t4-t4.*z-offC1.*t2.*t3+offC2.*t2.*t5-offP1.*t2.*t3+offP2.*t2.*t5-t2.*t3.*x+t2.*t5.*y,1.0,0.0,-t2.*t12,offC1.*t3-offC2.*t5+offP1.*t3-offP2.*t5+t3.*x-t5.*y,t4.*t12,0.0,1.0],[5,5]);
