function [ CStrct ] = constrCurvStruct( gcodeInfoStruct, toolStruct, ...
                      spline, R0, R1, Cprim, delta, evec, theta, pitch, ...
                      CoeffP5, Coeff ) 
%#codegen
% Construct a struct for the curves.
%
% Inputs :
% gcodeInfoStruct   : Struct containing the information from the Gcode
% toolStruct        : Struct containing the information of the tool
% spline            : Base spline basis
% R0                : Vector of the pose ( position + orientation ) at starting time
% R1                : Vector of the pose ( position + orientation ) at ending time
% Cprim             : Corrected center for the circle
% delta             : Difference between the radii
% evec              : Unit vector in the linear direction for the helix
% theta             : Rotation angle of the helix
% pitch             : Linear step for the helix
% CoeffP5           : Coefficient of the 5th order polynom
% Coeff             : Coeffs of the feedrate planning
%
% Ouputs:
% CStrct    : The resulting structure

coder.inline("never");

CStrct = struct(...
    'Info',                 gcodeInfoStruct, ...
    'tool',                 toolStruct,...
    'sp',                   spline,...
    'R0',                   R0, ...
    'R1',                   R1, ...
    'CorrectedHelixCenter', Cprim, ...
    'delta',                delta, ...
    'evec',                 evec,...
    'theta',                theta,...
    'pitch',                pitch,...
    'CoeffP5',              CoeffP5,...
    'sp_index',             uint32(1),...
    'i_begin_sp',           int32(0),...
    'i_end_sp',             int32(0),...
    'index_smooth',         int32(0),...
    'UseConstJerk',         false,...
    'ConstJerk',            0,...
    'Coeff',                Coeff,...
    'a_param',              1,...
    'b_param',              0 ...
    );

if ~coder.target( 'MATLAB' )
    coder.varsize( 'CStrct.Coeff',      StructTypeName.dimCoeffOpt{ : } );
    coder.varsize( 'CStrct.R0' ,        StructTypeName.dimR{ : } );
    coder.varsize( 'CStrct.R1' ,        StructTypeName.dimR{ : } );
    coder.varsize( 'CStrct.CoeffP5' ,   StructTypeName.dimCoeffP5{ : } );

    coder.cstructname( CStrct.Info,     StructTypeName.GCodeInfo ); 
    coder.cstructname( CStrct.tool,     StructTypeName.Tool ); 
    coder.cstructname( CStrct.tool.offset, StructTypeName.Axes ); 
    coder.cstructname( CStrct.sp,       StructTypeName.Spline );
    coder.cstructname( CStrct.sp.Bl,    StructTypeName.BaseSpline );    
    coder.cstructname( CStrct,          StructTypeName.Curve );
end

