function [ GCodeInfoStrct ] = constrGcodeInfoStruct( Type, ...
    ZSpdMode, trafo, HSC, G91, G91_1 , FeedRate, SpindleSpeed, ...
    gcode_source_line ) %#codegen
% Construct a struct containing the information from the Gcode.
% 
% Inputs :
% Type      : Type of curve
% ZSpdMode  : Zero speed mode
% trafo     : Flag for the trafo directive (true : on, false : off)
% HSC       : High speed cutting (true : on, false : off)
% Feedrate  : Feedrate of the spindle
% SpindleSpeed : Rotation speed of the spindle
% gcode_source_line : Line of the gcode
% G91       : Flag for incremental mode (true : on, false : off)
% G91_1     : Flag for incremental mode for arc center (true : on, false : off)
% 
% Outputs :
% CStrct    : The resulting structure

GCodeInfoStrct = struct( 'Type', Type, ...
                'zspdmode', ZSpdMode, ...
                'TRAFO', trafo, ...
                'HSC', HSC, ...
                'FeedRate', FeedRate,...
                'SpindleSpeed', SpindleSpeed,...
                'gcode_source_line', gcode_source_line, ...
                'G91', G91, ...
                'G91_1', G91_1 ...
                );

coder.cstructname( GCodeInfoStrct, StructTypeName.GCodeInfo );

end